### ISSUE TITLE
Documentation links to source are broken

### ISSUE THREAD

**Issue by tvt173** [gdsfactory/gdsfactory#1]
When clicking the link to [source] on any of the functions listed in the pp module, I get a 404 not found error. Not sure if this problem is present in other modules as well, or just this one

https://gdsfactory.readthedocs.io/en/latest/pp.html

**Comment by joamatab** [comment]
nice catch Troy,

I fixed it so now it shows not the link but the actual code

https://gdsfactory.readthedocs.io/en/latest/
