### ISSUE TITLE
new_uid removed from port.copy() but not completely from component_reference.py

### ISSUE THREAD

**Issue by wyywyy23** [gdsfactory/gdsfactory#1036]
In commit [7f740cb6879489026e4577fb29a1e53319a41ad0](https://github.com/gdsfactory/gdsfactory/commit/7f740cb6879489026e4577fb29a1e53319a41ad0) 
new_uid was removed from port.copy() as an argument.

In component_reference.py [line 445](https://github.com/gdsfactory/gdsfactory/blob/b2a4ee75c52532f8d25d6eb1aee049a2df9001b1/gdsfactory/component_reference.py#L445) 
new_uid is still passed as an argument, causing myref.ports not accessible in some cases.

Would suggest removing the new_uid argument from line 445 of component_reference.py

**Comment by joamatab** [comment]
Thank you Yuyang!
