### ISSUE TITLE
Run linting for notebooks as well

### ISSUE THREAD

**Issue by nikosavola** [gdsfactory/gdsfactory#1092]
**Is your feature request related to a problem? Please describe.**
It seems linting is currently run in CI with
```bash
flake8 .
```
The numerous notebooks in the repo could be linted as well, though some rules need relaxing.

**Describe the solution you'd like**
Combine a tool like [nbQA](https://github.com/nbQA-dev/nbQA) for linting the notebooks as well as regular code with essentially the same tool (flake8).

**Comment by joamatab** [comment]
Hi Niko,

Awesome, yes i love the idea :)

do you want me to send a PR for this?

**Comment by nikosavola** [comment]
> do you want me to send a PR for this?

I can also implement this, but if you are itching to do this you can do it as well. I'm just writing down all the features that come to mind as issues.

**Comment by joamatab** [comment]
I added it as a pre-commit hook
https://github.com/gdsfactory/gdsfactory/blob/main/.pre-commit-config.yaml

at the moment is running only black
