### ISSUE TITLE
Show schematic symbols

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#1108]
after the tech refactor https://github.com/gdsfactory/gdsfactory/pull/1102 

the schematic symbols in `notebooks/gdsfactory/20_schematic_driven_layout.ipynb` do not show correctly

![image](https://user-images.githubusercontent.com/4514346/211169822-eefb672d-358d-4870-aa5a-857b23e29679.png)

@thomasdorch 
@tvt173

**Comment by thomasdorch** [comment]
See #1116
