### ISSUE TITLE
Remove duplicate names in LayerViews

### ISSUE THREAD

**Issue by thomasdorch** [gdsfactory/gdsfactory#1111]
**Issue:**
We currently have a few dither patterns in our [.lyp file](https://github.com/gdsfactory/gdsfactory/blob/main/gdsfactory/generic_tech/klayout/tech/layers.lyp) that have different patterns, but share the same name. Though this is allowed in KLayout, since they are accessed by index rather than name, the LayerViews class indexes by name and does not support it. 

**Fix:**
All we need to do is rename the patterns so that each pattern name is unique.
The duplicated names are:
```
DOTS
LINES_H_DENSE
LINES_H_BOLD
LINES_DIAG_R
DOTS_SPARSE
LINES_H_BOLD
FILLED
dots1
stipple5
hZigZag
dot1
dot2
triangle
vZigZag
vCurb
```

**Comment by joamatab** [comment]
Thank you Thomas,

this should fix it 
https://github.com/gdsfactory/gdsfactory/pull/1112
