### ISSUE TITLE
Component.to_3d

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#1114]
Since the technology refactor in `generic_tech` `Component.to_3d`  works on notebooks but not on the teminal

![image](https://user-images.githubusercontent.com/4514346/211216914-d3d2d14b-1fd1-480e-a419-e57201baecce.png)

![image](https://user-images.githubusercontent.com/4514346/211220526-dfbf1f63-c5e8-416e-95b4-ed5d5b1ff1eb.png)

@thomasdorch

**Comment by joamatab** [comment]
the difference seems to be due to color_rgb being different

**Comment by thomasdorch** [comment]
See #1115, it looks like the color needs to be between 0 and 1, not 0 and 255.

**Comment by joamatab** [comment]
Awesome, thank you Thomas!
