### ISSUE TITLE
simplify cloud deployment

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#1141]
How could we simplify cloud deployment of gdsfactory?

For example, we could add https://github.com/proppy/rad-lab/tree/tuning/radlab-launcher

@proppy
@HelgeGehring 
@flaport

**Comment by proppy** [comment]
I should already part of it, see: https://github.com/proppy/rad-lab/blob/tuning/modules/silicon_design/scripts/build/images/provision/environment.yml#L33

**Comment by joamatab** [comment]
nice!

How about including a radlab documentation entry on the gdsfactory docs?

**Comment by proppy** [comment]
@joamatab following up on the "one click"'ish deployment idea, I think it would possible to leverage https://github.com/marketplace/google-cloud-build with the https://github.com/proppy/rad-lab-deploy repo; rather than the rad-lab UI/CLI.

Do you want to give it a try?
