### ISSUE TITLE
How can we reduce size of femwell modes?

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#1152]
Femwell modes are quite big for caching

How can we reduce size of femwell modes?

each simulation of 4 modes takes around 10MB of disk space

![image](https://user-images.githubusercontent.com/4514346/212563777-7ef86b43-7479-443a-b930-71bbbf552044.png)

@HelgeGehring 
@simbilod

**Comment by sebastian-goeldi** [comment]
If you can access and pass them as file descriptors, I'd suggest to store them in a tar.gz or tar.bz2 and access them through [tarfile](https://docs.python.org/3.10/library/tarfile.html#tarfile.TarFile.extractfile)

And example can be seen here https://stackoverflow.com/questions/37474767/read-tar-gz-file-in-python#37474813

**Comment by simbilod** [comment]
The biggest thing would be to save the mesh instead of the basis function objects, and rebuild the basis when loading from the mesh + function arguments (with element type and order)

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by joamatab** [comment]
Thank you for the PR Simon,

it still fails, you can run `simulation/fem/mode_solver.py` twice, 

the first time it will cache on your computer, the second one will fail
