### ISSUE TITLE
Fix docs in main

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#1162]
Docs are failing on main
https://github.com/gdsfactory/gdsfactory/actions/runs/3941880531/jobs/6744867149

_Originally posted by @joamatab in https://github.com/gdsfactory/gdsfactory/issues/1160#issuecomment-1385837903_

@simbilod

**Comment by Jan-David-Black** [comment]
This Issue seems to be fixed. Can we close it?

**Comment by joamatab** [comment]
yes, thank you Jan-David
