### ISSUE TITLE
speed up dev environment

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#1170]
How could we speed up gdsfactory dev environment?

https://github.dev/gdsfactory/gdsfactory

@basnijholt
@proppy
@HelgeGehring 
@simbilod

**Comment by proppy** [comment]
I think having some colab environment for immediate testing could be good, and some conda based installer (like discussed with https://github.com/hdl/conda-eda/issues/245) for workstation installation.

wdyt?

**Comment by joamatab** [comment]
I was playing with this and looks great

https://github.com/codespaces

**Comment by proppy** [comment]
See also https://cloud.google.com/workstations, potentially related to #1141 #250

**Comment by simbilod** [comment]
Note that the plugins do not come installed when launching a codespace -- is this intended?

![image](https://user-images.githubusercontent.com/46427609/213521297-219646a0-e795-4060-8b50-c8e0900ed1e2.png)
![image](https://user-images.githubusercontent.com/46427609/213521325-1a5c5f62-a6b5-4a85-addf-06c84cfb97b2.png)
![image](https://user-images.githubusercontent.com/46427609/213521357-ffa673d3-f191-47f2-ac67-268bef97422b.png)

**Comment by Jan-David-Black** [comment]
As far as I can see codespace sharing is only possible within organizations. Are you able to access the codespace I created for https://github.com/gdsfactory/gdsfactory/issues/1181 : https://jan-david-black-probable-succotash-pq54456x6qx27v64.github.dev/

**Comment by joamatab** [comment]
no, i can't 

for live sharing you can use VSCode extension

I have done pair programming using that

![image](https://user-images.githubusercontent.com/4514346/213787950-1408257e-dd20-4537-aa72-c30c8c12565f.png)
