### ISSUE TITLE
Interactive documentation

### ISSUE THREAD

**Issue by simbilod** [gdsfactory/gdsfactory#1171]
How difficult would it be to implement live Jupyterbook documentation notebooks directly in the docs, [similar to femwell](https://helgegehring.github.io/femwell/photonics/mode_solver.html)?

This would be very handy for small simulations, literature-type notebooks like implantation, playing with layouts, etc.

@HelgeGehring

**Comment by joamatab** [comment]
yes, that's a great idea, we can try with the ubc pdk docs first, and see if it works :)
