### ISSUE TITLE
improve Ipython widget for klayout

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#1225]
How can we improve functionality for ipywidgets and ipyevents?

See code in `gdsfactory/widgets`

At the moment only zoom works

TODO:

- [ ] build move, so you can click and drag, similar to [klayout](https://www.klayout.de/)

Someday:

- [ ] Built in turn on/off layers, similar to [kweb](https://github.com/gdsfactory/kweb)

![image](https://user-images.githubusercontent.com/4514346/216795303-7558bc1e-2732-4bdf-9b5a-3de9bea2f66f.png)

**Comment by tvt173** [comment]
functionality is in there but commented out... i think @sebastian-goeldi and i determined that it has something to do with the timer klayout is using which seems to need to be called continuously in the background

**Comment by sebastian-goeldi** [comment]
https://github.com/KLayout/klayout/blob/master/src/layview/layview/layLayoutView_noqt.h#L67

;)

**Comment by joamatab** [comment]
Thank you Thomas! @thomasdorch 

https://github.com/gdsfactory/gdsfactory/pull/1312

**Comment by thomasdorch** [comment]
I haven't been able to get kweb to run to to see how it works yet but does dragging/scrolling work in it?

**Comment by sebastian-goeldi** [comment]
Yes, in kweb all of this works. I mean dragging is not implemented. But you can scroll left right with [Ctrl]/[Alt]+MouseWheel and zoom with MouseWheel

**Comment by joamatab** [comment]
yes, you can try this notebook

https://gdsfactory.github.io/gdsfactory/notebooks/workflow/jupyter_notebooks.html

**Comment by tvt173** [comment]
i'm a bit unclear on all of this right now... what's the status on kweb vs the jupyter widget and when/how are we using one vs the other?

p.s. if we continue to use the widget, it would be nice to filter the layer list so that only those present in the layout are listed. otherwise the list is very long and unmanageable

**Comment by joamatab** [comment]
kweb works well only when using one notebook, that's why is not used mainstream, and only used here
https://gdsfactory.github.io/gdsfactory/notebooks/workflow/jupyter_notebooks.html

I agree that list only present layers would be nice

**Comment by tvt173** [comment]
i see... what's the issue when you have multiple notebooks?

**Comment by sebastian-goeldi** [comment]
The problem isn't per se multiple notebooks. It's that it doesn't handle multiple instances yet. This shouldn't be hard, just need a small status that identifies it as a kweb and see make a call there to see whether kweb is running.

What I see more as a show stopper is that kweb currently will only run on localhost. This kills it if you were to run it on colab or any non-local jupyter(like). And there is no way ( to my knowledge) to get the url of a jupyternotebook.

The way that could work is with the jupyter proxy extensions. But that's where we are going to territories where it becomes heavy on users.

So, I would opt to bring the widget up to the features of kweb.

**Comment by tvt173** [comment]
was just browsing the web for solutions for the kweb issue.... this one looks promising
https://colab.research.google.com/notebooks/snippets/advanced_outputs.ipynb#scrollTo=_7dYIo63EdgL

or this one for jupyterhub
https://docs.bokeh.org/en/latest/docs/user_guide/output/jupyter.html#jupyterhub
