### ISSUE TITLE
data orchestration pipeline

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#1227]
For the data analysis pipeline it would be great to define the analysis of the data, from raw data to processed results as well as aggregated data

How could we build a data pipeline using a tool like dagster?

https://github.com/dagster-io/dagster

@mithro 
@poppy

**Comment by mithro** [comment]
I think you mean @proppy

**Comment by mithro** [comment]
Netflix released a thing called Papermill which looks like a pretty interesting option? See https://github.com/nteract/papermill

Apache Airflow is also a common option.

**Comment by proppy** [comment]
See:
https://pyvideo.org/pydata-la-2019/data-and-etl-with-notebooks-in-papermill.html
https://pyvideo.org/pydata-la-2019/data-and-etl-with-notebooks-in-papermill.html

That's basically what we use with:
https://github.com/proppy/rad-lab-deploy/blob/tuning/rad-lab/modules/silicon_design/scripts/build/notebooks/examples/digital/serv/tuning.md

**Comment by joamatab** [comment]
we moved dagster plugin into gplugins


https://github.com/gdsfactory/gplugins
