### ISSUE TITLE
Define `RoutingStep` for steps in routing tools

### ISSUE THREAD

**Issue by 95-martin-orion** [gdsfactory/gdsfactory#1255]
**Is your feature request related to a problem? Please describe.**
`get_(route|bundle)_from_steps` both accept a parameter `steps` of type `Optional[List[Dict[str, float]]]`. The allowed values for this parameter are not clear from context - aside from careful inspection of the code, the only way to discover allowed dict keys is to try them.

**Describe the solution you'd like**
Define a data class `RoutingStep` that captures and documents the allowed parameters for a routing step, then modify the `steps` parameters described above to accept `Optional[List[RoutingStep]]`.

**Comment by joamatab** [comment]
The tricky part is that Steps can be different from manhattan and non-manhattan router

For non-manhattan router

```
STEP_DIRECTIVES = {
    "x",
    "y",
    "dx",
    "dy",
    "ds",
    "exit_angle",
    "cross_section",
    "connector",
    "separation",
}
```
