### ISSUE TITLE
import_gds fails if settings is empty dict in .yml

### ISSUE THREAD

**Issue by gdspaul** [gdsfactory/gdsfactory#1256]
If I have a GDS file and a YML metadata file for a component, and I try to import it with import_gds(read_metadata=True), it will crash if the YML file has an empty settings dict in it like this:
```
settings: {}
```
I think the bug is line 114 of import_gds.py,
```
            component.settings = Settings(**OmegaConf.to_container(metadata.settings))
```
which should probably only run if the settings dict is non-empty.

**Comment by joamatab** [comment]
thank you Paul, closing this as fixed it, thanks for reporting this and for your suggested fix
