### ISSUE TITLE
secret bug in gf.cell

### ISSUE THREAD

**Issue by gdspaul** [gdsfactory/gdsfactory#1282]
In the code quoted below from `cell.py`, I know this never happens, but if you DO pass any args or kwargs to `cell_without_validator`, it will crash.  The documentation for cell() indicates that it accepts a number of keyword arguments.

Purpose: I'm interested in manipulating the caching behavior of cells; I implemented a decorator that looks for a FILE cache of the component gds and yml and loads that.  This is actually very handy for saving time assembling large layouts, but gdsfactory caching gets confused by my decorator.

```
def cell(func: _F, *args, **kwargs) -> _F:
    # ...
    return cell_without_validator(validate_arguments(func), *args, **kwargs)
```

**Comment by joamatab** [comment]
Hi Paul, can you share the code to reproduce?

**Comment by tvt173** [comment]
agreed that this is a bug and improper documentation of the `cell` decorator function. kwargs which are documented are not actually kwargs to the decorator itself, but they are injected into the signature of the wrapped function.

i.e. this fails
```python
@cell(cache=False)
def my_cell():
   ...
```

but this works
```python
my_cell(cache=False)
```

I believe this is the intended behaviour, but the docs are misleading
![image](https://user-images.githubusercontent.com/3070522/219257823-6805bdf2-7339-473b-8e55-f76fb128d352.png)

it should say that these kwargs are injected into the resulting functions. they are not actually kwargs to the decorator itself

**Comment by gdspaul** [comment]
Exactly @tvt173 .  The documentation is wrong, but also _technically_ the code is wrong because if args or kwargs is **non-empty** then it will crash.  Like I said, it's almost impossible to make this happen.  But updating the docs would be nice.  Thanks guys.  :-)

**Comment by joamatab** [comment]
yes, 

Troy already mentioned that the decorator docs were wrong

let me know if this makes it more clear
https://github.com/gdsfactory/gdsfactory/pull/1287

**Comment by gdspaul** [comment]
My favorite part:
![image](https://user-images.githubusercontent.com/121980307/219424780-07365183-56ce-46d9-84bf-f50baac61c3c.png)

Impeccable service as always, Mr. Matres!
