### ISSUE TITLE
reduce size of git repo

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#1300]
How can we reduce the size of the GIT repo?

At some point we commited some unnecessary data

**Comment by sebastian-goeldi** [comment]
Most often I have seen this one mentioned for this use: https://github.com/rtyley/bfg-repo-cleaner

**Comment by tvt173** [comment]
yes, i've used BFG a few times for this... works like a charm. you'll need to do it locally once then force-push the repo. this could be disruptive to those who pull later though just to warn (like any operation re-writing git history)

**Comment by joamatab** [comment]
I tried and i got this

https://github.com/rtyley/bfg-repo-cleaner/issues/36

![image](https://user-images.githubusercontent.com/4514346/220176419-cc249ee5-ce2f-4b3f-8443-28ad2d7e3f93.png)

**Comment by sebastian-goeldi** [comment]
You have to force push, otherwise it worn't work, and also you might need to temporarily remove protections agains force push

**Comment by joamatab** [comment]
`git push -f` did not work either

`git remote update` worked

https://christoph.ruegg.name/blog/git-howto-mirror-a-github-repository-without-pull-refs.html

I think the repo went down from 278Mb to 14MB, Im going to delete some more files, such as old images

**Comment by joamatab** [comment]
the repo is 11Mb now :tada: 

![image](https://user-images.githubusercontent.com/4514346/220191501-b46c2f33-ec62-460b-8891-d8095288fde2.png)

**Comment by joamatab** [comment]
for some reason the repo size went back to 117MB

![image](https://user-images.githubusercontent.com/4514346/220795676-c19aeb82-6e13-4f4c-a876-d212b0e042c1.png)

**Comment by joamatab** [comment]
it should be fixed again by moving docs not in a branch
