### ISSUE TITLE
Add check to avoid uncached intermediate cells

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#1306]
This example shows the danger of using intermediate cells

```
import gdsfactory as gf


@gf.cell
def dangerous_intermediate_cells(width=0.5):
    """Example that will show the dangers of using intermediate cells."""
    c = gf.Component("safe")

    c2 = gf.Component(
        "dangerous"
    )  # This should be forbidden as it will create duplicated cells
    c2 << gf.components.hline(width=width)
    c << c2

    return c


@gf.cell
def using_dangerous_intermediate_cells():
    """Example on how things can go wrong.

    Here we try to create to lines with different widths
    they end up with two duplicated cells and a name collision on the intermediate cell
    """
    c = gf.Component()
    r2 = c << dangerous_intermediate_cells(width=0.5)
    r3 = c << dangerous_intermediate_cells(width=2)
    r3.movey(5)
    return c


if __name__ == "__main__":
    PDK = gf.get_generic_pdk()
    PDK.activate()
    c = using_dangerous_intermediate_cells()
    c.show()

```

Because of the name collision you end up with two waveguides with the same width, and you were expecting different widths

![image](https://user-images.githubusercontent.com/4514346/219975140-dea08ab3-0b99-49e2-aab8-301ed571aa86.png)

One possible solution is to add a check that makes sure that all dependencies have properly been decorated with `cell` and therefore cached

```
    for component in c.get_dependencies(recursive=True):
        if not component._locked:
            print(
                f"Component {component.name!r} was NOT properly locked. "
                "You need to write it into a function that has the @cell decorator."
            )
```

@tvt173 
@RehabSayed-G
@elamdf

**Comment by tvt173** [comment]
IMHO this should be done as a gds write option.

i.e. add a new gds write option `on_uncached_cell` with possible values
- `warn`: warns when writing a GDS with any dependencies not in the cache
- `error`: similar to above, but throw an error
- `flatten`: flattens references to those cells (similar to the `flatten_invalid_refs` flag), thus silently fixing the problem

I think the best way to check if a cell is properly cached should be
```python
if cell is not CACHE[cell.name]:
    # take appropriate action
```

that will check not only if the cell of that name is in the cache, but also that the cell in the cache _is_ that cell
