### ISSUE TITLE
add_ref(x_reflection) not working

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#1310]
How can we fix the gdstk.Reference(x_reflection)?

```
c = gf.Component('demo')
c.add_ref(gf.components.C(), x_reflection=True)
c.show()
```

![image](https://user-images.githubusercontent.com/4514346/219986996-8a174950-02ae-4638-8d75-6e2dbe9be9ba.png)

@heitzmann

**Comment by heitzmann** [comment]
@joamatab The argument `x_reflection` mirrors across the x axis, equivalent to gdsfactory's `mirror((0, 0), (1, 0))`, so there's no bug in the gdstk implementation:

```python
import gdstk

c0 = gdstk.Cell("0").add(*gdstk.text("F", 4, (0, 0)))

c1 = gdstk.Cell("1").add(
        gdstk.Reference(c0),
        gdstk.Reference(c0, origin=(5, 0), x_reflection=True)
    )

c1.write_svg("x_reflection.svg")
```
![x_reflection](https://user-images.githubusercontent.com/5938451/220096927-730b203f-b36b-43a8-8df0-118a63fde595.svg)

**Comment by joamatab** [comment]
Thank you Lucas

you are right, it's correct :)

```
import gdsfactory as gf

c = gf.Component('demo')
r1 = c.add_ref(gf.components.C(), x_reflection=True)
r2 = c.add_ref(gf.components.C(), x_reflection=False)
r2.movex(20)
c
```


![image](https://user-images.githubusercontent.com/4514346/220156197-46c00aee-e433-46d9-a78c-773755f24961.png)
