### ISSUE TITLE
documentation build timeout after 6 hours

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#1330]
Documentation is taking more than 6 hours to buil
it usually takes around 23 minutes and now it's not finishing in the max  6 hour limit from GitHub

in the `docs/conf.py` we are having 60 seconds timeout 

https://github.com/gdsfactory/gdsfactory/actions/workflows/pages.yml

@simbilod

**Comment by joamatab** [comment]
I think is coming from the model extraction notebook, where we use `%capture` magic

i noticed that capture has the side effect of errors are not properly catched

Maybe also does not get affected by timeout?


Im running the notebook `02_model_extraction.ipynb` locally and pushing the data to gdslib, so we can leverage the cache to get rid of the timeout

**Comment by joamatab** [comment]
Removed `%%capture` from suspected notebooks

https://github.com/gdsfactory/gdsfactory/pull/1328

**Comment by simbilod** [comment]
oof I see. These notebooks have a lot of computation because they loop over inputs, maybe we should deactivate them for now?

**Comment by joamatab** [comment]
The issue is coming from the ipython widget,

it makes it run of memory and kernel dies


@thomasdorch

**Comment by joamatab** [comment]
i disabled the execution until we figure out how to fix this
