### ISSUE TITLE
have ipynb and py versions of the notebooks under /docs

### ISSUE THREAD

**Issue by simbilod** [gdsfactory/gdsfactory#1342]
@joamatab is it possible to also generate the ipynb notebooks in the docs?

Right now, when a user clones the repo, they only get the .py version of the documentation and have to compile the notebook with jupytext themselves

It would be great if when cloning the repo you can also just run notebooks

**Comment by joamatab** [comment]
yes,

see #1340 
there is a line on the `Makefile` that can  `make notebook`  as well as `make jupytext` in case someone wants to keep using notebooks, 

`make notebook` makes the notebooks
`make jupytext` convert notebooks to python in case you modified the notebooks


I was going to recommend using https://marketplace.visualstudio.com/items?itemName=donjayamanne.vscode-jupytext
to open the python files

**Comment by simbilod** [comment]
My use case was a little different, as I was having people log in into a JupyterLab custer with a preset environment, clone the repo and then directly run notebooks

I guess I can install jupytext and have them compile the notebooks, or compile them myself somewhere for them to copy

**Comment by joamatab** [comment]
there is also a jupyterlab jupytext extension that will also allow you to edit directly the py file

**Comment by simbilod** [comment]
It was painful but I got people to run make notebooks :)

**Comment by joamatab** [comment]
Is there not extension for jupytext  on jupyter lab? 

@proppy

**Comment by tvt173** [comment]
Yes, in fact, just pip installing jupytext should be enough, according to
the docs

**Comment by joamatab** [comment]
yes, it does

![](https://i.imgur.com/ZfPTDlU.png)
