### ISSUE TITLE
notebook images failing

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#1346]
since we switch to jupyterbook notebooks are failing to show layouts in klayout. On previous theme they were showing [fine](https://gdsfactory.github.io/skywater130/notebooks/intro.html)

Some attempts to fix
- https://github.com/gdsfactory/gdsfactory/pull/1345

other ideas:

- https://github.com/s-holst/GDS2WebGL

@minrk
@tvt173 
@thomasdorch 
@sebastian-goeldi 
@proppy

**Comment by joamatab** [comment]
I also tried using plotly  but I get `Stream has unknown format`

```
            gdspath = component.write_gds(logging=False)
            lyp_path = gdspath.with_suffix(".lyp")

            layer_views = get_layer_views()
            layer_views.to_lyp(filepath=lyp_path)

            layout_view = lay.LayoutView()
            layout_view.load_layout(str(gdspath))
            layout_view.max_hier()
            layout_view.load_layer_props(str(lyp_path))

            import plotly.express as px

            img = layout_view.get_pixels(800, 600)
            fig = px.imshow(img)
            fig.show()

```

**Comment by sebastian-goeldi** [comment]
have you tried with png_data instead of the pixels? this gives you only a pixelbuffer afaik.

**Comment by joamatab** [comment]
yes, the issue is coming from `layout_view.load_layout(str(gdspath))` not sure why it does not work

**Comment by klayoutmatthias** [comment]
I think that again is the plugin registration. 

The stream readers are packed in separate shared objects which are looked up relative to the "db" library. If there is no such stream reader plugin lib, the load fails with "stream has unknown format".

Matthias

**Comment by klayoutmatthias** [comment]
Here is a sane file structure from a python module build of mine (shortened):

```
klayout/   <-- module root
├── db
│   ├── __init__.py
│   └── pcell_declaration_helper.py
├── dbcore.cpython-310-x86_64-linux-gnu.so   <-- dbcore python import library
├── db_plugins
│   ├── lib_cif_dbpi.cpython-310-x86_64-linux-gnu.so    <-- stream readers
│   ├── lib_dxf_dbpi.cpython-310-x86_64-linux-gnu.so
│   ├── lib_gds2_dbpi.cpython-310-x86_64-linux-gnu.so
│   ├── lib_lefdef_dbpi.cpython-310-x86_64-linux-gnu.so
│   ├── lib_magic_dbpi.cpython-310-x86_64-linux-gnu.so
│   ├── lib_mebes_dbpi.cpython-310-x86_64-linux-gnu.so
│   ├── lib_net_tracer_dbpi.cpython-310-x86_64-linux-gnu.so
│   ├── lib_oasis_dbpi.cpython-310-x86_64-linux-gnu.so
│   └── lib_pcb_dbpi.cpython-310-x86_64-linux-gnu.so
├── lib_db.cpython-310-x86_64-linux-gnu.so   <-- KLayout kernel, db classes
```

So "db_plugin" needs to be next to the `lib_db.cpython-310-x86_64-linux-gnu.so` library and needs to be filled with the stream reader plugin so's.

If you have this structure and it still does not work, LD_DEBUG is your friend.

Matthias

**Comment by proppy** [comment]
did you make sure to import:
```
import klayout.db
```
before importing:
```
import klayout.lay
```
see:
https://github.com/KLayout/klayout/issues/1146#issuecomment-1345643295

**Comment by joamatab** [comment]
That worked great! thank you proppy!

I also think i identified the issue with the widget,
https://github.com/gdsfactory/gdsfactory/commit/714c6f142e3aaba7c9fbc1e227aa277e948fd818

And Im sending a PR of a version that uses a static image instead of a widget

**Comment by joamatab** [comment]
it's fixed, we just needed to pin to an older version of ipywidgets

https://gdsfactory.github.io/gdsfactory/notebooks/00_geometry.html

Sending a PR that make ti even better

**Comment by klayoutmatthias** [comment]
Ah, well ... sorry, did not thing about "import klayout.db" ... but you're right. That will load the stream readers.

**Comment by proppy** [comment]
@klayoutmatthias would it make sense to do it systematically in `klayout.lay` `__init__.py`? If yes, I'd be  happy to file an issue and start working on it!

**Comment by klayoutmatthias** [comment]
Yes, that definitely makes sense!

I have included that already in the wip branch (https://github.com/KLayout/klayout/pull/1301/files/a3ff671eb9b998b17f5474b29bb8ad437e93c0c9..04626f9c2beff9750edf45cda6da4e6de6e78953). It will go into 0.28.6.

Matthias
