### ISSUE TITLE
Running FDTD Lumerical simulation on a component

### ISSUE THREAD

**Issue by vangapandu95** [gdsfactory/gdsfactory#1353]
I am exploring the GDSFactory's capabilities especially to interface it with Lumerical FDTD
While referring to the plugin content listed on "https://gdsfactory.github.io/gdsfactory/notebooks/lumerical/1_fdtd_sparameters.html", I got the impression that by writing the line of a code you can create an FDTD layout in Lumerical and run the simulations and get the data written all in single step without having to import the GDS file into an FDTD window and placing the ports manually and run the FDTD. Please correct me if this is not correct.
For example, I would like to run FDTD simulation of the bezier bend. In the figure shown below, I get the layout opened in the KLayout window when bezier.py script is run in VSCode. Can I simulate this bezier curve in FDTD lumerical on my computer by adding more code to the bezier.py file? Is there any reference that'd help me how to proceed?
![Bezier_FDTD_Ansys](https://user-images.githubusercontent.com/54287784/221338904-14e39e58-cd9e-45cd-a139-43881df7f81d.PNG)

**Comment by joamatab** [comment]
Yes, here is the tutorial on going from layout to sparameters 

https://gdsfactory.github.io/gdsfactory/notebooks/lumerical/1_fdtd_sparameters.html

**Comment by vangapandu95** [comment]
Thanks Joaquin!
My first attempt was to run the script file (write_sparameters_lumerical.py) in the lumerical folder of the GDSfactory directory. It gave me an error lumapi module not fond. So I used sys.append('api path of lumerical') and added it to the script. The code ran and the FDTD window seems to just open but then closed abruptly with an error.
It seems that the errors are coming from the lumapi.py file(line #242), due to a path/environment issue. Since this is a file in lumerical installation folder, I dont know if I am missing something here. 
![Lum_GDSFac_1](https://user-images.githubusercontent.com/54287784/221376464-ada68a9e-105a-480d-a0b7-4083074ca25f.PNG)
![Lum_GDSFac_2](https://user-images.githubusercontent.com/54287784/221376465-a34529f8-f6df-447c-96fe-c53e056564bb.PNG)

**Comment by joamatab** [comment]
This works great for me
![image](https://user-images.githubusercontent.com/4514346/221449416-4f06cb79-c59c-4e86-926f-e3f676269bbc.png)

You can contact Lumerical support 

@mgao-Ansys
@Zeqin-Lu
@121comeon

**Comment by joamatab** [comment]
@unrealfancy
@moogie
