### ISSUE TITLE
fix the notebooks that show model building 

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#1368]
How can we fix the notebooks that show model building with ray?

![image](https://user-images.githubusercontent.com/4514346/222020870-f8e326b5-72f3-4fcb-88d5-f9e085d17d8d.png)

`ModuleNotFoundError: No module named 'gdstk'`

@simbilod 

I can disable the execution until fixed

**Comment by simbilod** [comment]
got it. How can I reproduce and modify the build environment? This all works locally for me

**Comment by joamatab** [comment]
I think the way is written is using the system python

you can try running the notebook by itself

**Comment by simbilod** [comment]
closing to reopen in gplugins
