### ISSUE TITLE
docs not building

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#1370]
How can we make the docs build again?

There seems to be an issue with jupyterbook

@HelgeGehring

**Comment by HelgeGehring** [comment]
I had the same problem yesterday and fixed it in femwell, have a look at the docs.yml workflow there, copying that should help :)

**Comment by joamatab** [comment]
never mind, is fixed now, 

I think we should ask jupyterbook to make a release instead of relying on master :) which does not seem very stable
