### ISSUE TITLE
kweb notebook

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#1374]
- [kweb notebook has some issues](https://gdsfactory.github.io/gdsfactory/notebooks/workflow/jupyter_notebooks.html)

so i disabled the execution until we fix them

@sebastian-goeldi

**Comment by sebastian-goeldi** [comment]
Not sure what the issue is, I think now it might be working again? And I don't think this will work in the docs anyways

**Comment by joamatab** [comment]
We have some try Except to be able to default to klayout images with an environment variable

**Comment by sebastian-goeldi** [comment]
Is it the filexistserror? If that's the case, it should be becouse `~/.gdsfactory` exists but is a file and not directory

**Comment by joamatab** [comment]
Yes,  it is trying to create a directory inside .Gdsfactory folder
