### ISSUE TITLE
 keep the polarity on spirals with doped slabs on the bends

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#1432]
How can we keep the polarity on spirals with doped slabs on the bends?

```
import gdsfactory as gf

if __name__ == "__main__":
    c = gf.components.spiral_inner_io(
        cross_section=gf.cross_section.pin, waveguide_spacing=25, radius=30
    )
    c.show()

```

![image](https://user-images.githubusercontent.com/4514346/225480942-0a5bec19-7398-4904-8f1d-15f705ee3480.png)

@SkandanC

**Comment by simbilod** [comment]
![image](https://user-images.githubusercontent.com/46427609/225496132-7051da0e-ef99-48f4-9665-f598d4f1826b.png)

```
if __name__ == "__main__":

    c = gf.components.spiral_inner_io(
        cross_section=gf.cross_section.pin, 
        waveguide_spacing=25, 
        radius=30, 
        cross_section_bend=gf.partial(gf.cross_section.pin, mirror=True),
        asymmetric_cross_section=True
    )
    c.show()

```

See #1049 and #1433

**Comment by simbilod** [comment]
It would be nice to take another look at the general solution at some point https://github.com/gdsfactory/gdsfactory/issues/1049#issuecomment-1366908027
