### ISSUE TITLE
Windows and Linux full python installer builds have been failing

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#1502]
Windows and Linux builds have been failing

![image](https://user-images.githubusercontent.com/4514346/228858752-9ba8800e-6d50-4eea-a9c4-353e6c7fc366.png)

@SkandanC 
@jaimergp

**Comment by jaimergp** [comment]
You are running out of memory in those solves.

You can try to install `conda-libmamba-solver` and export `CONDA_SOLVER=libmamba`. I'll put a small PR to get it started.

**Comment by jaimergp** [comment]
See #1502
