### ISSUE TITLE
Improve maskprep documentation

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#1504]
how can we clean min gaps and acute angles on slab/cladding layers?

I've been trying doing it at the cell level but is hard to get all the cases right, specially when routing between cells
using bbox layers instead of cladding_layers can help but not always

https://gdsfactory.github.io/gdsfactory/notebooks/dataprep.html#remove-acute-angles

I think it would be better doing it at the top level in most cases,
However with klayout python API is a bit slow because single core, What do you think of using a ruby DRC script instead and running multicore

the other option is doing this hierarchically on every cell
https://github.com/gdsfactory/kfactory/blob/main/src/kfactory/utils/violations.py#L4-L20

```python
from gdsfactory.generic_tech import LAYER
import numpy as np 


import kfactory as kf
from kfactory.utils.violations import fix_spacing

filepath = PATH.build / "d00.gds"
lib = kf.kcell.KLib()
lib.read(filename=str(filepath))

layers = (LAYER.WGCLAD, LAYER.SLAB150)
distances = np.array((0.5,) * len(layers)) * 1e3  # convert um to Database units

for layer, distance in zip(layers, distances):
    for cell in lib.each_cell_bottom_up():
        # print(cell, distance, layer)
        layer_index = kf.klib.layer(layer[0], layer[1])
        fix = kf.utils.violations.fix_spacing(lib[cell], distance, layer_index)
        lib[cell].shapes(layer_index).insert(fix)

lib.write(str(PATH.build / "D00.gds"))
```

or at the top level

```python
    for layer, distance in tqdm(zip(layers, distances)):
        for cell in lib.each_cell_bottom_up():
            # print(cell, distance, layer)
            layer_index = kf.klib.layer(layer[0], layer[1])
            fix = kf.utils.violations.fix_spacing(lib[cell], distance, layer_index)
            lib[cell].shapes(layer_index).insert(fix)

    lib.write(str(PATH.build / "D00.gds"))


```

@sebastian-goeldi 
@SkandanC

**Comment by joamatab** [comment]
yes, in both cases the script did not finish in 10-20min on a 5x5mm layout

how can we speed it up?

**Comment by sebastian-goeldi** [comment]
That is very slow. It should finish in the order of 1min maximum

**Comment by joamatab** [comment]
Actually after 1.5hours the github action got cancelled :)

**Comment by sebastian-goeldi** [comment]
That probably mean an iterator wasn't advamced when it should.

**Comment by joamatab** [comment]
moving it to this issue

https://github.com/gdsfactory/gplugins/issues/32
