### ISSUE TITLE
Manhatanize a layer?

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#1509]
How can we manhatanize a layer?

See for example how BPG does it

[BPG](https://github.com/BerkeleyPhotonicsGenerator/BPG/tree/master/BPG/compiler)

@SkandanC 
@lucas-flexcompute 
@mdecea

**Comment by joamatab** [comment]
![image](https://user-images.githubusercontent.com/4514346/229382185-e64567c6-470e-4f9e-b621-e49a0c7dc015.png)

**Comment by sebastian-goeldi** [comment]
I have C++ code that can do it, but it needs a shared memory interface, not very suitable. Is there even still a big need for manhattanization? Most photonic pdks support freeform nowadays, don't they?

**Comment by joamatab** [comment]
How would you fix acute angles on slabs/claddings/enclosures?

if min_gap is 0.5 we can manhattanize with 1um gap and then we never have gaps below that

![image](https://user-images.githubusercontent.com/4514346/229382872-99fd4ec5-2a60-47e6-900c-c43e5e4d4e9a.png)

**Comment by sebastian-goeldi** [comment]
The klayout/kfactory script should be able to very easily fix it. Can you show me a code piece where it doesn't? I have fixed tons of these kinds of errors withit before, and it shouldn't be slow, especially if you call it on specific cells
