### ISSUE TITLE
update tidy3d plugin to latest version

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#1521]
how can we update to the latest tidy3d 2.0.2?

at the moment we get

```python
---> 46 hash_to_id = {d["task_name"][:32]: d["task_id"] for d in web.get_tasks()}
     47 filepath = str(dirpath / f"{sim_hash}.hdf5")
     48 job = web.Job(simulation=sim, task_name=task_name)

KeyError: 'task_name'
```

ideally we can also bring back the threading so we can submit multiple sims and make them blocking

@tyler-flex
@lucas-flexcompute 
@momchil-flex

**Comment by tylerflex** [comment]
> ideally we can also bring back the threading so we can submit multiple sims and make them blocking

Can you elaborate on what you mean here? I dont recall us supporting that ever, but gdsfactory did at some point right? 

Note that in the newest versions:
* one can set `verbose=False` in the web functions, which should alleviate any issues with rich console and multiple tasks in your threading implementation.
* we added a new function [`run_async`](https://docs.flexcompute.com/projects/tidy3d/en/latest/_autosummary/tidy3d.web.run_async.html?highlight=run_async) is introduced with a similar syntax as `web.run()` that uses asyncio under the hood to do parallel handling of simulations.  It also includes a custom progress bar. You could test this out and see an example at the [end of this notebook](https://docs.flexcompute.com/projects/tidy3d/en/latest/notebooks/WebAPI.html).

Let us know if you have any other requests.
