### ISSUE TITLE
Maybe we can import component with sidewall angle into lumerical application by layerbulider?

### ISSUE THREAD

**Issue by sdy-zju** [gdsfactory/gdsfactory#1533]
**Is your feature request related to a problem? Please describe.**

Now,the sidewall angle of  components on some material platform, such as LN, is not 90 degree, for which we need to take it into consideration when import GDSII into Lumerical application. Then we can get a more accurate simulation model and 
And sidewall angle is a parameter in LayerStack, however I cannot find where it is used.  Maybe we can make the most of it,.

**Describe the solution you'd like**
Layberbuilder can easily help us import GDS with different layers, it just have the parameter sidewallangle. And it is also  callable by python api, for which I think it is hopeful to be added into GDSfactory as a new GDS importing method.
Limited by my programming abilities, I can't commit a fork on my own.

![image](https://user-images.githubusercontent.com/35566168/230699673-a0869a42-39c0-4395-9ad7-811aebb5b078.png)

**Comment by joamatab** [comment]
This should be moved to gplugins

https://gdsfactory.github.io/gplugins/
