### ISSUE TITLE
I cannot use "control click" in VS code to access gdsfactory modules

### ISSUE THREAD

**Issue by yefanren** [gdsfactory/gdsfactory#1540]
I cannot use the "control click" method in VS code to access any of the gdsfactory modules. Can anyone give a little guidance for me? Many thanks!

**Comment by simbilod** [comment]
2 things:

(1) Is the Python extension installed?

![image](https://user-images.githubusercontent.com/46427609/231182586-51789fd7-d6ed-4535-aa90-2b6601531835.png)

(2) Is your VSCode file pointing to the right Python environment? This should be at the bottom right of the editor. For instance, mine is called "layout" here (it's a conda environment but should also work with virtualenv)

![image](https://user-images.githubusercontent.com/46427609/231182890-37afd7ea-3376-4f8b-af4b-749238830101.png)
