### ISSUE TITLE
Transition as a CrossSection

### ISSUE THREAD

**Issue by simbilod** [gdsfactory/gdsfactory#1545]
It used to be that we could give a Transition object anywhere a cross-section was accepted.

This allows stuff like:

```
    Xtrans = gf.path.transition(cross_section1=X1, cross_section2=X2, width_type="sine")
    c = gf.components.bend_circular(cross_section=Xtrans)
    c.show(show_ports=True)
```

![image](https://user-images.githubusercontent.com/46427609/231650433-e46f0bdb-1ef5-4b26-b049-0435c6338477.png)

To achieve this I had to locally undo this PR #1366 . The current syntax is much simpler, but does not allow the above since Transition and gf.path.transition do not have all the attributes of CrossSection. For instance, for the bend above on main we now get `AttributeError: 'Transition' object has no attribute 'radius'`

What's the best way to bring it back? I think keeping the current Transition as it is, and inheriting all CrossSection attributes from say cross_section1 could be enough.

@joamatab @tvt173

**Comment by joamatab** [comment]
yes, sounds good to me Simon, you can send a PR
