### ISSUE TITLE
femwell tests failing

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#1549]
https://github.com/gdsfactory/gdsfactory/actions/runs/4682732880/jobs/8296956797

@HelgeGehring

**Comment by simbilod** [comment]
we need to pin to an earlier version

**Comment by simbilod** [comment]
Actually that does not seem to be the problem, tidy3d is having issues

![image](https://user-images.githubusercontent.com/46427609/231869258-efe37856-2980-4400-aa7e-32b0b4c003c2.png)

**Comment by SkandanC** [comment]
Hmm, the tidy3d exception in the github logs seem different... Are these the same versions of tidy3d?
