### ISSUE TITLE
tidy3d credentials seem to be missing when building docs

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#1556]
tidy3d credentials seem to be missing when building docs

![image](https://user-images.githubusercontent.com/4514346/232472622-474fc2fd-2369-4a52-b408-1c639fc54d0a.png)

https://gdsfactory.github.io/gdsfactory/notebooks/workflow/3_cascaded_mzi.html

this seems releated to some docs failing recently

https://github.com/gdsfactory/gdsfactory/actions/runs/4720719696/jobs/8373111502

@tylerflex
@lucas-flexcompute 
@momchil-flex

**Comment by joamatab** [comment]
Where is tidy3d looking for the credentials?

is it still in `~/.tidy3d/auth.json`?

**Comment by tylerflex** [comment]
Hi @joamatab 

Yes, the file has moved to `~/.tidy3d/config` and it should contain 
```
apikey = "XXX"
```
where XXX is your API key (and the quotes are surrounding it).

Alternatively (might be easier in GitHub actions) you could set an environment variable of 
```
SIMCLOUD_APIKEY="XXX"
```

There's some more detailed instructions [here](https://docs.flexcompute.com/projects/tidy3d/en/latest/quickstart.html#linking-regiestration)

Let us know if that solves the issue!

**Comment by joamatab** [comment]
yes, it solved it, thank you Tyler
