### ISSUE TITLE
fast local density estimates

### ISSUE THREAD

**Issue by simbilod** [gdsfactory/gdsfactory#1576]
**Is your feature request related to a problem? Please describe.**

I've been doing local density estimation with KLayout booleans, for instance comparing the area of a rectangle of some size (related to the rule check) to the area of (this rectangle) & (my layout) on the layer to check, for a few rectangle positions. It works OK. 

**Describe the solution you'd like**

We could very efficiently generate the density histograms across **all positions** by leveraging image processing. For an acceptable estimate, we just pixelate the layout on a given layer (multiple layers can be multiple "color" channels), and then apply some convolutional filters (where kernel size maps to region size to check). This can be done very efficiently on hardware accelerators.

I can take a first stab later, unless someone knows more about this or already has something working :)

**Comment by SkandanC** [comment]
You could use jax.scipy.stats and its gaussian_kde. 

You can also make density maps in Klayout directly. I wrote a nice Ruby script in Klayout for this.

![image](https://user-images.githubusercontent.com/100642027/234165149-5c0bc7b6-abe4-4a13-bb24-daecf6f6fbc8.png)

**Comment by joamatab** [comment]
@SkandanC,

could you share your script for this?
