### ISSUE TITLE
improve gdsfactory webapp

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#1578]
We have a `gf web` to run gdsfactory on webapp mode. 

- [ ] improve web app for design
  - [ ] schematic capture https://github.com/gdsfactory/gdsfactory/issues/1832
  - [ ] 3D visualization https://gdsfactory.github.io/gdsfactory/notebooks/03_layer_stack.html#layerstack
  - [ ] Pyspice integration. Similar to [Siliwiz](https://app.siliwiz.com/)
  - [ ] database integration. See [gdatasea](https://github.com/gdsfactory/gdatasea)
  - [ ] select different PDKs, at the moment you need to either set environment variable. or run `gf web --pdk ubcpdk`

Roles:

- Designer: use webapp for design, verification and validation
- Manager: use webapp to monitor progress, browse PDK
- Foundry: use webapp to offer grant access to PDK

@Ealameda31
@sebastian-goeldi 
@tvt173

**Comment by SkandanC** [comment]
Do we know what kind of 3d Visualization we plan on adding? Something like the to_3d thing? afaik klayout doesnt have a full 3d viewer, unless there's sme salt package for it

**Comment by joamatab** [comment]
How about adding https://gdsfactory.github.io/gdsfactory/notebooks/03_layer_stack.html#layerstack

?

**Comment by Jan-David-Black** [comment]
What I would also love to see is an endpoint, that shows the "current" layout like klive does. And the option to show the cell hirachy.

**Comment by Jan-David-Black** [comment]
@joamatab, @SkandanC, @sebastian-goeldi   I have started to implement something like that here: https://github.com/Jan-David-Black/gdsfactory/tree/current_component_web I am however not so sure how to cleanly load in the new layout, when the file watcher senses a newly created/modified file:
Currently I am doing something in the lines of:
´´´python
def show_new_gds(self, filepath):
        self.url = self.gds_path = filepath
        self.update_gds()

def update_gds(self):
      self.layout_view.active_cellview().layout().clear()
      self.layout_view.load_layout(self.url)
      self.layout_view.max_hier()
´´´
That seems to trip up the layers though... (their ids for turning on/off from the frontend)

**Comment by sebastian-goeldi** [comment]
@Jan-David-Black I think you most likely want to do something similar to what klive is doing here https://github.com/gdsfactory/klive/blob/main/klayout/python/klive_server.py#L63 i.e. `self.layout_view.reload(cell_view_index)` the `cell_view_index` you can get by getting the active cell_view with `self.layout_view.active_cellview_index()`
