### ISSUE TITLE
API documentation is difficult to navigate

### ISSUE THREAD

**Issue by DanHickstein** [gdsfactory/gdsfactory#1603]
gdsfactory seems to do a great job with documentation in general! But I find navigating the API documentation to be a little difficult. For example, I'm using the the geometry.offset function. I can easily find this function in the [expected place in the source code](https://github.com/gdsfactory/gdsfactory/blob/main/gdsfactory/geometry/offset.py). And there is a docstring describing how to use the function. 

But, when I go to the [API documentation](https://gdsfactory.github.io/gdsfactory/api.html), I literally cannot find the documentation for this function. Shouldn't this docstring be in the API docs somewhere?

**Comment by joamatab** [comment]
Thank you for pointing that out Dan,

I added some more entries to the API documentation

let me know if it's better with this PR https://github.com/gdsfactory/gdsfactory/pull/1606

**Comment by DanHickstein** [comment]
Thanks @joamatab! 

The API docs seem similar though. For example, I still don't see the "geometry.offset" function listed.

On the main page, the "Sphinx docs to GH pages" badge says "Failing", so perhaps there is some issue with synchronizing to GH pages? 

![image](https://user-images.githubusercontent.com/1107796/235538896-18c6f51c-27b5-4597-a486-c1521349d720.png)

**Comment by joamatab** [comment]
can you check again? yes, it takes 20 min to build the docs, and during those 20min the workflow shows up as failing :)

https://gdsfactory.github.io/gdsfactory/api.html

**Comment by DanHickstein** [comment]
It works now! Thanks :)
