### ISSUE TITLE
improve `plot_netlist()`

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#1656]
How can we make `plot_netlist` go from here

![image](https://github.com/gdsfactory/gdsfactory/assets/4514346/6662e514-9387-46cf-a265-3ec19ca8e203)

to there

![image](https://github.com/gdsfactory/gdsfactory/assets/4514346/a0e5d676-68fb-4e1d-809e-aa7682f783af)

https://gdsfactory.github.io/gdsfactory/notebooks/20_schematic_driven_layout.html

ideally we also add a flag `ignore_placements` where we ignore placement information from the layouts

**Comment by tvt173** [comment]
If you just want to display the bokeh plot, I think you need to extract the netlist from your layout, convert it to a SchematicConfiguration object, then call this method on it:
https://github.com/gdsfactory/gdsfactory/blob/main/gdsfactory/circuitviz.py#L460

**Comment by tvt173** [comment]
Alternatively, create a new `SchematicEditor` object, and populate it with the info from the extracted netlist, and call `.visualize()`. This would probably be better if you intend to edit and save your schematic (placements, etc.)-- i.e. make it read/write, and not read-only
