### ISSUE TITLE
`port_symmetries` on `gtidy3d.write_sparameters` seem broken

### ISSUE THREAD

**Issue by Jan-David-Black** [gdsfactory/gdsfactory#1681]
**Describe the bug**
When using port symmetries it seems to execute the wrong simulations and not copy over the s-parameters correctly

**To Reproduce**
```python
c = gf.components.mmi2x2()
symmetry = {
  "o1": {
    "s11": ["s22","s33","s44"], "s21": ["s12","s34","s43"], "s31": ["s13","s24","s42"], "s41": ["s14","s23","s32"],
  }
}
df = gt.write_sparameters(c, overwrite=True, port_symmetries=symmetry, is_3d=False, verbose=True)
```

**Expected behavior**
Execute a single simulation (not three) and copy the s-parameters as advised by the dict.

**Suggested fix**
I will open a PR

**Comment by Jan-David-Black** [comment]
Additionally it seems to break with the old s-parameter notation. So either we should autoconvert from the old notation to the new one (assuming fundamental mode), or we should fix the docs...

**Comment by joamatab** [comment]
it seems still has issues

![image](https://github.com/gdsfactory/gdsfactory/assets/4514346/6229afa5-7927-4321-9819-b13257bd60b4)

**Comment by lucas-flexcompute** [comment]
The problem seems to be the name of the ports. The names coming from the component are `'o1', 'o2'`, but the [symmetry definition](https://github.com/gdsfactory/gdsfactory/blob/23a8aa14c4df1c1253f7983196bec9d812bd0ee2/gdsfactory/simulation/port_symmetries.py#L1) uses another naming scheme, so [this if clause](https://github.com/gdsfactory/gdsfactory/blob/23a8aa14c4df1c1253f7983196bec9d812bd0ee2/gdsfactory/simulation/gtidy3d/write_sparameters.py#L181) is never true.

**Comment by Jan-David-Black** [comment]
I had been "fixing" the issue according to the [doc string] (https://github.com/gdsfactory/gdsfactory/blob/23a8aa14c4df1c1253f7983196bec9d812bd0ee2/gdsfactory/simulation/gtidy3d/write_sparameters.py#L87). There the port names are used as keys. The format specifying the excite port actually makes sense to me, so we would have to adjust the symmetry definitions. What do you think @joamatab?

**Comment by Jan-David-Black** [comment]
- [ ]  And we should add some tests to avoid breakage in the future :)

**Comment by joamatab** [comment]
we have tests for the tidy3d plugin and are failing at the moment

**Comment by Jan-David-Black** [comment]
Interesting... I'll have to check why the tests passed on my machine...

**Comment by Jan-David-Black** [comment]
Regarding the top level keys of the symmetry dicts: do we stick to using the excitation port?

**Comment by joamatab** [comment]
when you work on a fork that has no credentials for tidy3d it skips those tests

I think i found a fix, see PR
