### ISSUE TITLE
Default installation `python -m pip install gdsfactory` requires kfactory

### ISSUE THREAD

**Issue by sebastian-goeldi** [gdsfactory/gdsfactory#1713]
**Describe the bug**
The default installation now requires kfactory due to the default import of `difftest`. This results in a package that when installed freshly doesn't work and crashes on import.

**To Reproduce**
`python -m pip install gdsfactory` in a fresh environment

**Expected behavior**
The package should install in a working condition by default

**Suggested fix**
Either add kfactory as a dependency or make the import of difftest not default and add a warning when trying to import without having kfactory installed

**Comment by joamatab** [comment]
Hi Sebastian,

In the difftest I added try, except
https://github.com/gdsfactory/gdsfactory/pull/1712

How does that sounds?

**Comment by sebastian-goeldi** [comment]
LGTM :+1:
