### ISSUE TITLE
design region not visible

### ISSUE THREAD

**Issue by kdotom** [gdsfactory/gdsfactory#1734]
The adjoint example on this page:
https://gdsfactory.github.io/gdsfactory/notebooks/meep/001_meep_sparameters.html

produces the correct final design in the simulation object, but when plotting with
`optimized_component.plot()`
the design region is not output. The same behavior applies when writing a gds.

All lines of code have been used exactly. Is there any extra action that is necessary? / Any geometry type conversion, etc.?

**Comment by drinwater** [comment]
Hi,

`optimized_component.plot()` is supposed to plot the gdsfactory Component. It's only the optimized Component.

-SkandanC

**Comment by kdotom** [comment]
Thanks for the note.
`opt.sim.plot2D()`
plots the full device
![img](https://github.com/gdsfactory/gdsfactory/assets/8495107/05c67367-43f1-47a5-91b5-b3436273c0ad)
this confirms that the simulations worked.

However,
`optimized_component.plot()`
appears to just plot the waveguides
<img width="407" alt="adj2" src="https://github.com/gdsfactory/gdsfactory/assets/8495107/0ae031ff-619f-4823-83a6-43fe7841796b">

**Comment by kdotom** [comment]
Just found it. Thresholding issue. I interpreted `threshold_offset_from_max` as the normalized weights. This appears to be in terms of epsilon. Leaving a note in case it's helpful. Thanks!
