### ISSUE TITLE
add examples on routing from Strip to rib waveguides

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#1742]
how can we add examples on how to route from strip to rib waveguides?

Also, maybe Silicon to Silicon nitride

@tvt173

**Comment by threaddy** [comment]
Maybe a good starting point for strip to rib: [https://ieeexplore.ieee.org/document/5752805](url)

**Comment by tvt173** [comment]
sure, i'd be happy to help make an example... we should start by registering a default rib-strip transition in the generic pdk. is this what I should use?
https://gdsfactory.github.io/gdsfactory/components.html#taper-strip-to-ridge

**Comment by joamatab** [comment]
yes, that one looks good to me

**Comment by joamatab** [comment]
see https://gdsfactory.github.io/gdsfactory/notebooks/rib_strip_autotransition.html
