### ISSUE TITLE
Klayout gdsfactory plugin installation

### ISSUE THREAD

**Issue by dominauta** [gdsfactory/gdsfactory#1756]
Plugin installation fails with the error in the attached image

![imagen](https://github.com/gdsfactory/gdsfactory/assets/125756930/2a6186b2-712b-485a-b5d8-76b5f0092841)

**Comment by joamatab** [comment]
Hi David, i got a windows laptop and was not able to reproduce this,

it may be specific for your computer setup,

maybe open klayout as administrator and see if this works

**Comment by dominauta** [comment]
Indeed seems it was something related to my settings. Thanks
