### ISSUE TITLE
Pdk.activate() clears cache regardless if this Pdk is already active

### ISSUE THREAD

**Issue by alibillalhammoud** [gdsfactory/gdsfactory#1772]
**Issue**
Pdk.activate() does not check the active Pdk (to see if it is already active). This results in cache being cleared regardless if the Pdk is already active.

**To Reproduce**
I included a short python script that reveals this issue.
[files.zip](https://github.com/gdsfactory/gdsfactory/files/11749257/files.zip)

**Expected Behavior**
The expected behavior is for Pdk.activate() to check if this Pdk is already the active Pdk.

**Fix**
I suggest we check the `_ACTIVE_PDK` global variable to see if it is `self` after line 255 in [pdk.py](https://github.com/gdsfactory/gdsfactory/blob/main/gdsfactory/pdk.py#L255). We can do something like this:
```
global _ACTIVE_PDK
if self is _ACTIVE_PDK:
    return
```

**Comment by tvt173** [comment]
yes, @alibillalhammoud , I agree. this would be a nice improvement. could you please submit an MR?
