### ISSUE TITLE
fix schematic editor

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#1779]
how can we allow schematic editor to show it in the docs?

![image](https://github.com/gdsfactory/gdsfactory/assets/4514346/27000cc4-75df-4486-90b6-1f653bcc0498)

See docs
https://github.com/gdsfactory/gdsfactory/actions/runs/5283520410/jobs/9559878377

How can we integrate [SDL](https://gdsfactory.github.io/gdsfactory/notebooks/20_schematic_driven_layout.html) it as part of `gf web`?

@sebastian-goeldi 
@tvt173 
@Jan-David-Black

**Comment by joamatab** [comment]
fixed by https://github.com/gdsfactory/gdsfactory/pull/1788

**Comment by joamatab** [comment]
For some reason it still does not work on my vscode

@SkandanC

**Comment by tvt173** [comment]
@joamatab which extension are you using to run these jupytext notebooks in vscode? I can't get the notebooks to run in vscode at all

**Comment by joamatab** [comment]
good point,

we can add this jupytext to the developer docs

https://gdsfactory.github.io/gdsfactory/layout.html

**Comment by tvt173** [comment]
hmm that's the one i was trying to, but it didn't work for me. i'll have to try again later. works for me in jupyterhub though
