### ISSUE TITLE
Run DRC checks from gdsdrawpy library

### ISSUE THREAD

**Issue by rviktor85** [gdsfactory/gdsfactory#1835]
### Discussed in https://github.com/gdsfactory/gdsfactory/discussions/1834

<div type='discussions-op-text'>

<sup>Originally posted by **rviktor85** July  4, 2023</sup>
Using gdsfactory we can set different DRC rules and obtain the corresponding rule file that can be run using KLayout GUI app. But is it possible to run DRC check using gdsfactory or somehow using KLayout API? 

Also, this can be a good idea for the enhancement of gdsfactory library if this does not exist.</div>

**Comment by joamatab** [comment]
we have some functions in gdsfactory/geometry/check_width.py, that can natively use the klayout python API to run DRC, 

this is one way of doing it is a bit harder (compared to the ruby-like DRC wrapper than klayout examples are) but may give you more flexibility
