### ISSUE TITLE
Extend `MaterialSpec` for arbitrary properties

### ISSUE THREAD

**Issue by nikosavola** [gdsfactory/gdsfactory#1857]
**Is your feature request related to a problem? Please describe.**
Currently, `MaterialSpec` can be used define the refractive index for materials. Would be nice if it could be extended to support other  attributes, such as, loss tangents.

**Describe the solution you'd like**
Extend `MaterialSpec` to support arbitrary properties such that a `LayerStack`s alongside a group of `MaterialSpec`s (maybe a new `MaterialStack`?) would give all possible layer and material properties. This would be useful for simulation workflows.

**Comment by simbilod** [comment]
I had started something similar a while back, but a different (purely optical) solution was one instead. Feel free to get inspiration

https://github.com/simbilod/gdsfactory/tree/material_database/gdsfactory/database/materials
