### ISSUE TITLE
Generalize `background_tag` to 3D meshing

### ISSUE THREAD

**Issue by nikosavola** [gdsfactory/gdsfactory#1860]
**Is your feature request related to a problem? Please describe.**
Both 2D meshes, xy and uz, support a tag for the background of a mesh along with padding. 
https://github.com/gdsfactory/gdsfactory/blob/e8075ea63e5c909e661e998a4fd6d6fa58667369/gdsfactory/simulation/gmsh/xy_xsection_mesh.py#L33
https://github.com/gdsfactory/gdsfactory/blob/e8075ea63e5c909e661e998a4fd6d6fa58667369/gdsfactory/simulation/gmsh/uz_xsection_mesh.py#L161

This could be expanded to the xyz mesh with a corresponding padding with an extra dimension. This would be useful to, for example, include air as default in the background.

**Describe the solution you'd like**
Add a 3D background to 
https://github.com/gdsfactory/gdsfactory/blob/e8075ea63e5c909e661e998a4fd6d6fa58667369/gdsfactory/simulation/gmsh/xyz_mesh.py#L44
 with the same API of a `background_tag` and `background_padding`.

**Comment by simbilod** [comment]
Yes this should be easy to do by adding generating a layer on padded bbox at runtime, and assigning it a new layerstack entry that goes from -vertical_padding to +vertical_padding above the layers present in the CAD
