### ISSUE TITLE
Create a 3D meshing tutorial

### ISSUE THREAD

**Issue by nikosavola** [gdsfactory/gdsfactory#1886]
**Is your feature request related to a problem? Please describe.**
There could be a tutorial showcasing 3D meshing. Currently there are ones for both types of 2D meshes

![image](https://github.com/gdsfactory/gdsfactory/assets/7860886/af7ffdfa-d679-4a5b-8607-5ae594a7e5af)

**Describe the solution you'd like**
Make tutorial for 3D meshing.

Ideally there would be a nice interactive widget.

**Comment by joamatab** [comment]
Nice, PRs welcome for this :)

**Comment by simbilod** [comment]
[Meshwell ](https://simbilod.github.io/meshwell/)(the 3D meshing backend) has docs but it would be nice to document the gdsfactory interface to it

**Comment by joamatab** [comment]
i'll close this, and we can open it again on https://github.com/gdsfactory/gplugins
