### ISSUE TITLE
Port layer type is List for fanout_component

### ISSUE THREAD

**Issue by thomasdorch** [gdsfactory/gdsfactory#1909]
I recently ran into an issue where the `Component.get_ports_list` function no longer returns all of the ports with the correct `Layer`. I tracked the problem down to some ports now having their layers as `lists` rather than `tuples`, but the equality check in `get_ports_list`: 
```
ports = {p_name: p for p_name, p in ports.items() if p.layer == layer}
``` 
requires that they be `tuples`. This can be fixed by simply casting `p.layer` to a `tuple`, but that doesn't fix the reason that the port layers are `lists` sometimes. 

After a bit of digging, only the ports created by `fanout_component` are having their layers turned into `lists`, which seems to be due to the recent change in [66fc74b](https://github.com/gdsfactory/gdsfactory/commit/66fc74b75f8c231a45c7cd2134bfe4843e62397f#diff-cf624d378beea6257cc07489793e63baa5a2ef1fba7b06cc1fa5cc9208de0cea) to use `port.to_dict().copy()` over `port.settings.copy()`. This passes the port `dict` through the `clean_dict_json` function, which converts the `tuple` layer to a `list`.

I'm not sure whether it's best to just make a PR that adds a type cast for the layer to a `tuple` in `select_ports` or if we should maybe add an additional method like `to_dict_json` that specifically prepares the port for a json export instead of cleaning it by default? 

Maybe the best way to go is to just convert the layer from a `list` into `tuple` when creating the port (see #1910)

@joamatab

**Comment by joamatab** [comment]
Hi Thomas,

did your PR fixed the issue?

https://github.com/gdsfactory/gdsfactory/pull/1910
