### ISSUE TITLE
Use explicit `.j2` endings for component definition YAMLs

### ISSUE THREAD

**Issue by nikosavola** [gdsfactory/gdsfactory#1914]
**Is your feature request related to a problem? Please describe.**
Continuation to #1908.

Use explicit `.j2` endings for component definition YAMLs with Jinja2 features (or maybe for all?).
This enables Jinja2 linting (#1911) and syntax highlighting in IDEs.

**Describe the solution you'd like**
* Rename example component definitions with Jinja2 features to `.pic.yml.j2` or something similar ending with `.j2`
* Check what changes are needed in code to possibly parse both raw `.yml` and `.j2` endings

**Comment by nikosavola** [comment]
I guess in the meeting this was deferred. Instead the issue could be about hacking the current Jinja2 linter to check for custom file-endings. Honestly, this should be a feature in the package so that can be done upstream.

**Comment by joamatab** [comment]
Sounds good to me, feel free to send a PR

**Comment by nikosavola** [comment]
https://github.com/aristanetworks/j2lint/pull/68 now implements different file extensions
