### ISSUE TITLE
calculate sparameters at multiple wavelengths for tidy3d plugin 

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#192]
How can we calculate the Sparameters at more than 1 wavelength?

see example in  `gdsfactory/simulation/gtidy3d/get_results.py`

**Comment by tylerflex** [comment]
The ModeMonitors or FieldMonitors accept `freqs` as a list of frequencies to measure at. You can supply all frqueniues of interest and do the S matrix calculation the same way as before, just add `.sel(f=freq)` in the amplitude data measurement to select at the frequency of interest.

**Comment by joamatab** [comment]
awesome, thank you Tyler! this worked great!
