### ISSUE TITLE
dispersive materials seem to be missing in tidy3d plugin plot_eps

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#193]
`see gdsfactory/simulation/tidy3d/fixme/plot_material.py`

![image](https://user-images.githubusercontent.com/4514346/154816075-49e3dbb6-d52b-4511-a9a4-ae45552ef211.png)

**Comment by tylerflex** [comment]
Supply the frequency to plot_eps to evaluate the permittivity at, otherwise it evaluates at frequency -> \infty 
https://github.com/flexcompute/tidy3d/blob/develop/tidy3d/components/simulation.py#L578

**Comment by joamatab** [comment]
thank you Tyler, this worked great
