### ISSUE TITLE
Move maskprep_flat to plugins and rename

### ISSUE THREAD

**Issue by tvt173** [gdsfactory/gdsfactory#1956]
I find that the `gdsfactory.geometry.maskprep_flat` module is useful, but
- it is not well distinguished from the `maskprep` module, making it confusing which to use
- it has a bad name... beyond being ugly, it could be made untrue with certain enhancements to enable better hierarchical processing
- it better fits the description of a "plugin" since it is almost 100% a wrapper around klayout functionality and fairly tangential to the gdsfactory core

I propose we move it to gplugins. I'm open to name suggestions.

**Comment by joamatab** [comment]
moved it here

https://github.com/gdsfactory/gplugins/issues/32
