### ISSUE TITLE
text_rectangular justify keyword doesn't do anything

### ISSUE THREAD

**Issue by zobristnicholas** [gdsfactory/gdsfactory#1970]
**Describe the bug**
Text produced by `gf.components.text_rectangular` is always left justified regardless of the value of the `justify` keyword.

**To Reproduce**
```
c_left = gf.components.text_rectangular("text", justify="left")
c_left.show()  # properly left justified text

c_right = gf.components.text_rectangular("text", justify="right")
c_right.show()  # still left justified
```

**Expected behavior**
Justification should change.

**Suggested fix**
The for loop that fixes the justification in this function is not run because of the `component.absorb(ref)` a few lines up

**Comment by joamatab** [comment]
Thank you for the fix!
