### ISSUE TITLE
Update VTT logo in README

### ISSUE THREAD

**Issue by nikosavola** [gdsfactory/gdsfactory#1977]
**Describe the bug**
The VTT logo in the README is an older one

**Expected behavior**
Current logo should be used

**Suggested fix**
Change the logo to this one
![image](https://github.com/gdsfactory/gdsfactory/assets/7860886/4e9c28ec-49e9-4159-961f-657f48d099e5)

**Comment by joamatab** [comment]
fixed by https://github.com/gdsfactory/gdsfactory/commit/94716b9ed730f218c2f7dca55b1bd33bbf02c929
