### ISSUE TITLE
Class methods clickable or expose more information in docs

### ISSUE THREAD

**Issue by nikosavola** [gdsfactory/gdsfactory#1986]
**Is your feature request related to a problem? Please describe.**
Class methods in the generated API documentation don't show all information nor are they clickable for seeing the full definition

For example, the `get_netlist` method for https://gdsfactory.github.io/gdsfactory/_autosummary/gdsfactory.Component.html only shows this much information
![image](https://github.com/gdsfactory/gdsfactory/assets/7860886/124500c8-4ddb-4e41-aca7-c176363685b7)

while the actual docstrings contain this much
![image](https://github.com/gdsfactory/gdsfactory/assets/7860886/16cb4d97-b1d2-4107-a929-38c127631935)

**Describe the solution you'd like**
Make the methods clickable for full definition and maybe show more information like argument types.

**Comment by drinwater** [comment]
I like what we do with kfactory documentations for the API, where have the entire source code for each class and function, but this is in mkdocs, which ius different from jupyter. https://gdsfactory.github.io/kfactory/reference/kfactory/kcell/#:~:text=information%20in%20um-,Source%20code%20in%20src/kfactory/,-kcell.py


-SkandanC

**Comment by joamatab** [comment]
yes, i like it more too,

@HelgeGehring  has also been looking at this

https://myst-tools.org/docs/mystjs

**Comment by tvt173** [comment]
i think maybe that adding the `:recursive:` directive, as shown in this [SO post](https://stackoverflow.com/a/62613202/701803) might fix it...

![image](https://github.com/gdsfactory/gdsfactory/assets/3070522/0baebc6c-7b37-496e-89f4-c70c30567f36)

![image](https://github.com/gdsfactory/gdsfactory/assets/3070522/2eb0b1e6-d3bd-4bd6-b604-5143d3ed347a)

**Comment by joamatab** [comment]
i tried that but didn't work

**Comment by sebastian-goeldi** [comment]
The problem here is that you just specify **kwargs as an argument but then use specific arguments (not only kwargs which is misleading itself already). If you want the full arguments, you need to write all the args to the definition of the function or put the definition below the kwargs entry of the doc string args

**Comment by sebastian-goeldi** [comment]
> The problem here is that you just specify **kwargs as an argument but then use specific arguments (not only kwargs which is misleading itself already). If you want the full arguments, you need to write all the args to the definition of the function or put the definition below the kwargs entry of the doc string args

For most docstring collectors, they will look for args in the function definition and match to the docstring and not vice-versa afaik

**Comment by nikosavola** [comment]
I think the type information would also be useful. That is currently not visible for the ones where they are defined.

**Comment by joamatab** [comment]
We have been experimenting with myst here

https://github.com/joamatab/gdsfactory

https://joamatab.github.io/gdsfactory 

once we figure out how to better document the API we can consider it

@HelgeGehring

**Comment by nikosavola** [comment]
This issue still persists

**Comment by joamatab** [comment]
Closing as fixed by the current MkDocs/Zensical API documentation. `docs/api.md` renders `gdsfactory.Component` through mkdocstrings with source links, separate signatures, signature annotations, alphabetical members, and full docstrings. The built API contains anchored method entries and typed parameter tables (including `get_netlist`), replacing the old autosummary output shown here.
