### ISSUE TITLE
get_paths

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#1995]
how about replacing 

- `capacitance_path`
-  `modes_path` 
- `sparameters_path` 

with path dic?

that way we can have arbitrary simulation data paths without making `Pdk` class excessively complex

@nikosavola 
@tvt173

**Comment by tvt173** [comment]
we already have this `Paths` class defined in `gdsfactory.config`. why not just use that?

**Comment by joamatab** [comment]
yes, that's a good point
