### ISSUE TITLE
Corner + U case in auto router

### ISSUE THREAD

**Issue by tvt173** [gdsfactory/gdsfactory#2004]
**Is your feature request related to a problem? Please describe.**
There is one case of `get_bundle()` where one must make a bundle by either
A. Turning before crossing the final port and making a U back towards it (if there is enough room)
B.  Turning after crossing the final port and making a U back towards it

**Option A:**
![image](https://github.com/gdsfactory/gdsfactory/assets/3070522/80b9a071-2342-4070-b376-170e74f125f4)

**Option B:**
![image](https://github.com/gdsfactory/gdsfactory/assets/3070522/2c495e77-2290-4d30-89cc-1fecece0b1a8)

This is currently not supported, and will throw a RouteWarning. However, it would be nice to support it.

**Describe the solution you'd like**
Ideally, test if there is enough room for option A and use it if possible. Otherwise option B.

The case shown above represents two of the skipped `tests\routing\test_port_ordering.py` cases, with `make_bundle(angle=270, reverse_ports=True,)`

**Comment by joamatab** [comment]
yes, it would be great to support it

@SkandanC 
@sebastian-goeldi 
@damienbonneau

**Comment by joamatab** [comment]
Closing this as fixed

![image](https://github.com/user-attachments/assets/1960a248-e1fd-40c6-a6c7-b8a533c213cb)

**Comment by sebastian-goeldi** [comment]
I think it's currently not possible to choose the other option though. But I feel generally this is the better solution anyway, as this "avoids" having to route around the whole component. I believe though the other piece errors out even if another way would be available. But I feel that this is a corner case where the current solution is "good enough"
