### ISSUE TITLE
issue on "fill_rectangle"

### ISSUE THREAD

**Issue by wuzhonghan** [gdsfactory/gdsfactory#2039]
when I test the fill_rectangle_custom()  with margin=5, the code is below:

**mzi = gf.components.mzi()
c = gf.Component("component_with_fill")
layers = [(1, 0)]
c << fill_rectangle_custom(
    mzi,
    gf.components.rectangle(),
    avoid_layers=layers,
    margin=5,
    spacing=(4, 2),
    bbox=mzi.bbox,
)
c << mzi
c.show(show_ports=True)**

![image](https://github.com/gdsfactory/gdsfactory/assets/124678531/05c7f34e-238c-41bb-bf8a-22172dca0e58)
I find in some region the margin is less than 5, how can I fix this?

**Comment by joamatab** [comment]
thanks for reporting this

why not using the tiling [processor](https://gdsfactory.github.io/gdsfactory/notebooks/04_components_geometry.html#dummy-fill-tiling)?

@SkandanC

**Comment by SkandanC** [comment]
Hi,

I think tilin gprocdessor is only useful for large layouts, not for a single mzi. @sebastian_goeldi knows more.


________________________________

**Comment by joamatab** [comment]
yes, but since they are using GDS anyway to interface with kfactory 

however im not sure where there is issue coming from

@sebastian-goeldi

**Comment by sebastian-goeldi** [comment]
Shouldn't be a problem to use the tiling processor for even small things. There is some overhead to calculate the string and set up the processor, but that's in the order of 10-100ms would be my guess. So as long as you don't do it 10'000 times, no problem.

**Comment by wuzhonghan** [comment]
thanks for reply,

I will try tiling processor
