### ISSUE TITLE
gf.components.die unseparated corners

### ISSUE THREAD

**Issue by johnyb115** [gdsfactory/gdsfactory#2048]
Hi, I ran into the following issue, not necessarily a bug.
**Describe the bug**
When using the **gf.components.die**, it doesn't create separate cutmark corners as I would like, the top one is always connected with the dicing line, even when **draw_dicing_lane=False**. It behaves differently than in PHIDL, as shown in following code and screenshot.

**To Reproduce**
``` python
import phidl.geometry as pg
import gdsfactory as gf

die_GF = gf.components.die(
            size = (3000, 3000), # Size of die
            street_width = 100,   # Width of corner marks for die-sawing
            street_length = 700, # Length of corner marks for die-sawing
            die_name='GDSFACTORY DIE',
            text_size=200,
            layer = (2,0),
            bbox_layer = None,
            draw_corners=True,
            draw_dicing_lane=False,
            )

die_phidl = pg.basic_die(
            size = (3000, 3000), # Size of die
            street_width = 100,   # Width of corner marks for die-sawing
            street_length = 700, # Length of corner marks for die-sawing
            layer = (2,0),
            draw_bbox = False,
            bbox_layer = 99,
            die_name='PHIDL DIE',
            text_size=200,
            )

die_phidl_to_GF = gf.read.from_phidl(die_phidl)
comparison = gf.Component()
die_GF_ref = comparison << die_GF
die_phidl_ref = comparison << die_phidl_to_GF
comparison.distribute(elements='all', direction='x', spacing=200)
comparison.plot('qt')
```

![image](https://github.com/gdsfactory/gdsfactory/assets/106141684/7f5b4230-714c-491c-a13a-5324caafb4ee)

**Expected behavior**
I would expect unconnected corner cutmark when **draw_dicing_lane=False**, same as the PHIDL die in right side of the image.

**Comment by joamatab** [comment]
Thank you for reporting this Jan

let me know if this fix makes it better
https://github.com/gdsfactory/gdsfactory/issues/2048
