### ISSUE TITLE
Markdown linting not supported for Windows

### ISSUE THREAD

**Issue by drinwater** [gdsfactory/gdsfactory#2052]
https://github.com/gdsfactory/gdsfactory/blame/d3f1d5287487fde0ec0cc61da16930fd210be191/.pre-commit-config.yaml#L41

Recently we added markdown linting as a pre-commit hook, this hook is built on Ruby, so involves having to install Ruby (even if u dont use it for any other use case). Also, its not built for Windows, whih means git commit on Windows doesnt work without somehow bypassing pre-commit, which isnt a good idea imo.
https://github.com/markdownlint/markdownlint

@joamatab wdyt about not having markdown linting in pre-commit?

-SkandanC

**Comment by joamatab** [comment]
Sounds good, let's remove it

**Comment by joamatab** [comment]
Sounds good, let's remove it
