### ISSUE TITLE
the bug for CrossSection with bbox

### ISSUE THREAD

**Issue by LuYouxi** [gdsfactory/gdsfactory#2134]
When I use get_bundle for routing, the bbox option is added to the route. The offset mode of the bbox is different from the previous version. The offset of the bbox is added to the input and output of the arc and the straight.

```
from functools import partial

import gdsfactory as gf
from gdsfactory.cell import cell
from gdsfactory.component import Component
from gdsfactory.generic_tech import get_generic_pdk
from gdsfactory.port import Port

si_section = gf.Section(width=0.45, offset=0, layer="WG", port_names=['o1', 'o2'])
si_wg = gf.CrossSection(
    sections=[si_section], 
    radius=5, 
    bbox_layers=["WGCLAD"], 
    bbox_offsets=[5], 
    auto_widen=True, 
    auto_widen_minimum_length=50, 
    width_wide= 1,
)

c = gf.Component("sample_connect")
mmi1 = c << gf.components.mmi1x2()
mmi2 = c << gf.components.mmi1x2()
mmi2.move((100, 50))
route = gf.routing.get_route(mmi1.ports["o2"], mmi2.ports["o1"], cross_section=si_wg)
c.add(route.references)
c.show()

```
Version 7.8.0
![image](https://github.com/gdsfactory/gdsfactory/assets/35725059/de40d872-2c95-4c61-bcd1-b10a048c58b5)
![image](https://github.com/gdsfactory/gdsfactory/assets/35725059/25165aa4-c9fe-4f7f-b7d9-cd82ec62353f)

Before version 7.8.0
![image](https://github.com/gdsfactory/gdsfactory/assets/35725059/6b564168-6b81-4311-804b-695dc2b7cb30)
![image](https://github.com/gdsfactory/gdsfactory/assets/35725059/5a89f0df-8c78-48cd-92c7-dad3469d5fb6)

**Comment by joamatab** [comment]
yes

there was a problem on the previous behavior for bbox of bends that have angles different than 90, 180 and 270

what's the issue with the new behavior?

**Comment by LuYouxi** [comment]
> yes
> 
> there was a problem on the previous behavior for bbox of bends that have angles different than 90, 180 and 270
> 
> what's the issue with the new behavior?

hi joamatab, I think the old waveguide bbox behaved better. After all, no additional cladding is required at the junction between the waveguides. At the same time, this will avoid additional DRC errors.

**Comment by joamatab** [comment]
I see, thank you for reporting this!

This PR will bring the old behavior for the bends
https://github.com/gdsfactory/gdsfactory/pull/2154

**Comment by LuYouxi** [comment]
> I see, thank you for reporting this!
> 
> This PR will bring the old behavior for the bends and straights #2154

hi, I saw the modification of the straight waveguide and bend waveguide codes, but the offset parameter of bbox did not work, and the waveguide with bbox is still the same as version 7.8.0. I guess the implementation of add_bbox in cross_section should also be modified.
