### ISSUE TITLE
Extrude: backwards incompatibilities and issues

### ISSUE THREAD

**Issue by tvt173** [gdsfactory/gdsfactory#2137]
The updates to extrude and transition cause some deep issues for me due to backwards compatibility. I am working on a PR which fixes this, but I wanted to post an issue in the meantime to make sure everyone agrees with the changes.

In short, I have identified two major issues
- `extrude` and `get_cross_section` no longer tolerate `Transition` objects as inputs. This can cause deep issues, if you i.e. have a component (like a bend) which you want to be able to pass a transition to, rather than a CrossSection
- `extrude_transition` does not have a `@cell` decorator

This is my proposed fix:
- decorate `extrude_transition` with `@cell`
- move `extrude` and `extrude_transition`  into gdsfactory.components.extrude
- add a more generic `extrude` *function* (no cell decorator) back to gdsfactory.path. It will call either the `extrude` or `extrude_transition` component, depending on whether the input is a cross section or a transition
- add branch to handle transitions back to get_cross_section

This adds some additional complexity in exchange for backwards compatibility and flexibility to use Transitions in a wide range of scenarios. Let me know what you think.

@joamatab 
@skychil

**Comment by joamatab** [comment]
sounds good to me, 

let me know if this https://github.com/gdsfactory/gdsfactory/pull/2138 fixes things on your end
