### ISSUE TITLE
improve connectivity checks

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#2165]
How can we build kfactory-like connectivity checks? that way we don't need to rely on pins

```
    rdb = top_cell.connectivity_check()
    rdb.save('a.lyrdb')
```

@SkandanC 
@sebastian-goeldi

**Comment by sebastian-goeldi** [comment]
The only piece missing for you is to write the ports as a json, load & parse gds & port-json in kfactory and run it on the cell. Would also work with a json label ofc

**Comment by joamatab** [comment]
where can i find an example of the JSON format for the ports?

**Comment by sebastian-goeldi** [comment]
Sorry, missed this. I don't have a current way of doing it. I meant you should sgore it along the gds. You can orient youself on how kfactory writes ports into the gds.
