### ISSUE TITLE
automatic detect routing crossings and place a waveguide crossing instead

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#218]
Maybe call the function `get_route_with_crossings` or something like that

![image](https://user-images.githubusercontent.com/4514346/157068612-9f0db1c4-b0be-4a92-9a0c-26c14d300b9e.png)

**Comment by tvt173** [comment]
i've implemented something very similar in a different platform once upon a time... I think in gdsfactory it may be even more straightforward. i would
1. first compose the basic routes, without crossings
2. collect all the paths from all the routing segments, and find points of intersection. something like Shapely can do this quickly and efficiently
3. insert crossings at those intersection points
4. replace the original (straight) routing segments with shorter segments on either side feeding into the crossing

you will need to be careful at (2) that only straights are being crossed and at (4) that your crossings fit when placing, but I think for now you can simply throw a `RoutingError` in those cases, and you should be good to go!

**Comment by joamatab** [comment]
I saw this PR by Juan Villegas implementing this

https://github.com/SiEPIC/SiEPIC-Tools/pull/176

@jevillegasd

**Comment by tvt173** [comment]
hi @joamatab this could be done fairly easily for yaml-based circuits, especially if you constrain it to only run on routes... i think it is a bit more tricky to do it generally, through multiple levels of hierarchy, but it could be done just as easily on a general circuit if you assume all routing components are placed at the top level.  here's some pseudocode:

```python
def replace_crossings(component, reflist = None, crossing_component='my_crossing'):
    if reflist is None:
        reflist = component.references
    straight_refs = [ref for ref in reflist if is_straight_component(ref.parent)]
    crossing = gf.get_component(crossing_component)
    half_length = crossing.size_info.width / 2  # assumes crossing is symmetric and cardinally oriented
    intersecting_pairs_points = get_intersecting_pairs(straight_refs)
    for r1, r2, intersection in intersecting_pairs_points:
        if min_distance(intersection, r1.ports) < half_length:
            raise ValueError('Not enough room to place crossing!')
        if min_distance(intersection, r2.ports) < half_length:
            raise ValueError('Not enough room to place crossing!')
        # assert that cross section of straights are compatible with crossing, and make crossing between original ports, with straight extensions as necessary
        place_crossing(component, r1.ports, r2.ports)
        component.references.remove([r1, r2])
   return component
```
