### ISSUE TITLE
10_layout_full.ipynb

### ISSUE THREAD

**Issue by lukasc-ubc** [gdsfactory/gdsfactory#2180]
The example provided on the gdsfactory web page doesn't work: https://colab.research.google.com/github/gdsfactory/gdsfactory-photonics-training/blob/main/notebooks/10_layout_full.ipynb#scrollTo=o09UQOsnYpQO

Running it results in error such as missing "trimesh" and "Could not connect to klive server"

**Comment by joamatab** [comment]
Hi Lukas,

for the 3D rendering error you need to `pip install gdsfactory[cad]`

for the `Could not connect to klive` warning you can ignore, klive only works when you have klayout open with the klayout server
