### ISSUE TITLE
schematic capture

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#219]
How can add schematic capture?

ideally we would enable a schematic driven flow

for that we only need instances and routes from our netlist driven flow

we convert the netlist from YAML into an XML
https://github.com/TeledyneLeCroy/SignalIntegrity

so we allow both GUI and code schematic driven flows

**Comment by joamatab** [comment]
You have two options for working with gdsfactory:

- **layout driven flow**: you code your layout using python functions, and then extract the YAML netlist to simulate the circuit.
- **netlist driven flow**: you start with the YAML definition of your circuit (instances, placements and routes). From the netlist you can simulate the circuit or generate the layout.


the schematic capture would be similar to the netlist but you don't need to define placements, then you can use some auto-place and route

**Comment by tvt173** [comment]
then a schematic just becomes a different view on the same netlist
