### ISSUE TITLE
Component.write_gds_with_metadata

### ISSUE THREAD

**Issue by jasminabrar** [gdsfactory/gdsfactory#2192]
What happened to this function?  I wrote a script a few months ago using function and now it doesn't work.
Does gdsfactory have a policy about not removing or changing things, namely keeping it backwards compatible?  It will be difficult to build projects if the core is changing.
My suggestion would be to put a label on a function "deprecated", and provide a date for when you plan to remove it from the code.  A window of 2 years would be reasonable, I think.
thank you
Lukas

**Comment by joamatab** [comment]
Hi Lukas,

we deprecated the function, and removed after a few months,

you are right, we should solidify the code

you can use `Component.write_gds(with_metadata=True)`
