### ISSUE TITLE
colab does not find klayout layermap file lyp

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#224]
How can we make colab find the klayout lyp?

so we get nice colors by default

@flaport 
@proppy
@tvt173 

![image](https://user-images.githubusercontent.com/4514346/157510542-e12fe2a2-2a75-4b25-ab5f-cb2141b340d3.png)

**Comment by tvt173** [comment]
@joamatab 

you need to declare it in your setup.py

example below

```python
setup(
    name="gdsfactory",
# ...
    package_data={
        "": ["*.gds", "*.yml", "*.lyp", "*.json"],
    },
# ...
)
```

**Comment by joamatab** [comment]
closing this issue as it is working now
