### ISSUE TITLE
enable `conda install gdsfactory`

### ISSUE THREAD

**Issue by tvt173** [gdsfactory/gdsfactory#226]
I would love to be able to `conda install gdsfactory`. it would greatly simplify installation on windows, where you typically need to `conda install gdspy` or have vscode build tools available for the full installation to work without issue

**Comment by joamatab** [comment]
Me too :)

Conda requires all dependencies to be Available on conda

There are only a few dependencies missing

**Comment by joamatab** [comment]
https://github.com/conda-forge/staged-recipes/pull/17625

**Comment by joamatab** [comment]
We got it working :tada: 

https://github.com/conda-forge/gdsfactory-feedstock

Just updated the docs 

I also bumped the version to 5.12.9 to see how fast are the updates to the conda package
