### ISSUE TITLE
Extract can generate empty cells

### ISSUE THREAD

**Issue by simbilod** [gdsfactory/gdsfactory#2289]
**Describe the bug**

Using component.extract with a layer argument on a cell that does not contain this layer populates an empty polygon:

**To Reproduce**

```
import gdsfactory as gf
from gdsfactory.typings import LayerSpecs, ComponentSpec
from gdsfactory.generic_tech import LAYER

@gf.cell
def layer_rectangles(component: ComponentSpec,
                        layers: LayerSpecs,
                     ):
    """Building a derived component of rectangles corresponding to the dimensions of select layers in another component."""

    c = gf.Component()

    for layer in layers:
        rectangle = c << gf.components.rectangle(
            size=[
                gf.get_component(component).extract(layers=(layer,)).xsize,
                gf.get_component(component).extract(layers=(layer,)).ysize,
            ],
            layer=layer,
        )

    return c

@gf.cell
def mycomponent(present_layers: LayerSpecs):
    c = gf.Component()

    for layer in present_layers:
        c << gf.components.circle(layer=layer)

    return c

original_component = mycomponent(present_layers = (LAYER.WG, LAYER.SLAB90))
original_component.show()
```

![image](https://github.com/gdsfactory/gdsfactory/assets/46427609/903679cb-16c2-4360-a8bf-e1aaa96e67fa)

```

derived_component = layer_rectangles(component = original_component, 
                        layers = (LAYER.WG, LAYER.SLAB150)
                        )
derived_component.show()
```

![image](https://github.com/gdsfactory/gdsfactory/assets/46427609/8b405b88-154d-44d3-83f9-6a6384c14263)

Note the empty polygon for SLAB150:

![image](https://github.com/gdsfactory/gdsfactory/assets/46427609/0ba18296-4512-464e-b2ad-f7f2992b145e)

**Expected behavior**

If the layer is not present, extract should do nothing or throw an error.

**Suggested fix**

The layers argument in .extract could be parsed when called to only iterate over present layers (set intersection)

**Comment by joamatab** [comment]
nice catch Simon,

sending  a PR fix for this
