### ISSUE TITLE
recognize hierarchical components in SiEPIC tools verification flow?

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#229]
SiePIC tools working now. which is nice for verification (find unconnected pins, extract interconnect netlist ..)

See `gdsfactory/samples/pdk/fab_a.py`

How can we recognize hierarchical components?

![image](https://user-images.githubusercontent.com/4514346/158028371-da06401c-fd87-4c06-92cc-15409ddd098a.png)

**Comment by thomasdorch** [comment]
Do the lower-level components need to be flattened? Removing the "absorb" calls in coupler_ring and coupler90 fixes this

<img width="962" alt="image" src="https://user-images.githubusercontent.com/53101766/158038625-aae64901-c7fe-4120-987b-e7a2d2c9c391.png">

**Comment by joamatab** [comment]
I see, thank you Thomas

**Comment by joamatab** [comment]
yes, that worked great, thank you Thomas,
