### ISSUE TITLE
text ‘M’, ‘W’ can not pass DRC

### ISSUE THREAD

**Issue by SkyLin1020** [gdsfactory/gdsfactory#2381]
**Describe the bug**
text ‘M’, ‘W’ can not pass DRC

**Expected behavior**
![image](https://github.com/gdsfactory/gdsfactory/assets/45063682/23728ad1-b3b3-4c74-9abe-8767fbc18429)
![image](https://github.com/gdsfactory/gdsfactory/assets/45063682/9a4db060-1dd4-4e70-b015-a63befc5955a)

**Comment by joamatab** [comment]
yes, you can try this one

https://gdsfactory.github.io/gdsfactory/components.html#text-rectangular

**Comment by SkyLin1020** [comment]
> yes, you can try this one
> 
> https://gdsfactory.github.io/gdsfactory/components.html#text-rectangular

thanks for the reply.
Excellent work!
