### ISSUE TITLE
bend_straight_bend cell defective when direction is 'cw' (missing test?)

### ISSUE THREAD

**Issue by thomaslima** [gdsfactory/gdsfactory#2389]
**Describe the bug**
The bend_straight_bend cell does not work when called with 'cw' direction.

**To Reproduce**
```python
from gdsfactory.components import bend_straight_bend

c = bend_straight_bend(direction="cw")
c.show()
```
Screenshot:
<img width="213" alt="image" src="https://github.com/gdsfactory/gdsfactory/assets/1088659/79268cf4-dbc1-4320-990a-f495a0a77e75">

**Expected behavior**
What would you like to happen?
Like this, but mirrored:
<img width="417" alt="image" src="https://github.com/gdsfactory/gdsfactory/assets/1088659/5523f227-0bfe-4477-b9cc-a36682a2df52">

**Suggested fix**
The code for the bend_straight_bend makes sense to me, so this must be an underlying bug either in the mirror or the connect methods.

```python
    c = Component()
    b = bend_euler(
        angle=angle,
        p=p,
        with_arc_floorplan=with_arc_floorplan,
        npoints=npoints,
        direction=direction,
        cross_section=cross_section,
    )
    b1 = c.add_ref(b)
    b2 = c.add_ref(b)
    s = c << straight(length=straight_length, cross_section=cross_section)
    s.connect("o1", b1.ports["o2"])
    b2.mirror()
    b2.connect("o1", s.ports["o2"])
    c.add_port("o1", port=b1.ports["o1"])
    c.add_port("o2", port=b2.ports["o2"])
    return c
```

**Comment by simbilod** [comment]
fixed in #2390 

this seems to be a very old cell. You could also look into [routing functions](https://gdsfactory.github.io/gdsfactory/notebooks/04_routing.html)
