### ISSUE TITLE
Improve gdsfactory cell-level booleans documentation

### ISSUE THREAD

**Issue by simbilod** [gdsfactory/gdsfactory#2429]
Reading the [gdsfactory geometry documentation](https://gdsfactory.github.io/gdsfactory/notebooks/04_components_geometry.html), one might think it is a good practice to use gdsfactory-level booleans to define Components/References using other Components/References

While this can be done, the gdsfactory cell naming/caching overhead and differences in behaviour between components and references introduces a lot of subtleties and unexpected behavior. Something that works at a given point in time might fail when the behaviour of cells is changed. I don't have a minimal example, but some cells I defined over a year ago before I knew better now fail after [#2420 ](https://github.com/gdsfactory/gdsfactory/pull/2421)

This should be made more explicit in the documentation, and users should be encouraged to use booleans at the polygon level

**Comment by joamatab** [comment]
Fixed by https://github.com/gdsfactory/gdsfactory/pull/2430

The issue was serialization of components didn't include a geometric hash
