### ISSUE TITLE
Consolidate warning logging

### ISSUE THREAD

**Issue by nikosavola** [gdsfactory/gdsfactory#2441]
**Is your feature request related to a problem? Please describe.**
gdsfactory appears to use the both `warnings.warn` and `loguru.logger` for warnings. Would make sense to use only one (and maybe only loguru as it is already a dependency so might as well use it).

**Describe the solution you'd like**
Refactor `warnings.warn` to `gdsfactory.config.logger` calls.

**Comment by wwwwwwzx** [comment]
You can redirect the all warnings from `warnings` module to `loguru` by adding the following line in `config.py`
```python
warnings.showwarning = lambda message, *args, **kwargs: logger.opt(depth=2).warning(message)
```
