### ISSUE TITLE
document interconnect Lumerical Ansys gdsfactory plugin

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#245]
it would be great having a notebook tutorial in the simulations section that shows how to use the interconnect plugin 

https://github.com/gdsfactory/gdsfactory/pull/237

**Comment by thomasdorch** [comment]
In the works!

**Comment by joamatab** [comment]
Awesome 😎

**Comment by joamatab** [comment]
Hi Thomas,

thanks for your PR #469 

When i run the notebook on my end

![image](https://user-images.githubusercontent.com/4514346/174865588-93bd40e5-6fdb-4573-85e3-f60be922b72e.png)

![image](https://user-images.githubusercontent.com/4514346/174864103-2ccbbb0f-063e-4ad7-b4bc-5139d2976317.png)


@thomasdorch

**Comment by thomasdorch** [comment]
The `failed to create element` sounds like the CML didn't install properly, is the EBeam library is shown under Design Kits?

**Comment by thomasdorch** [comment]
Okay so I think this was happening because the EBeam CML wasn't getting installed due to `initialize_design_kit` finding the `interconnect` path in gdslib and not installing it. This should be fixed with [this PR](https://github.com/gdsfactory/gdsfactory/pull/472)

**Comment by joamatab** [comment]
Awesome, thank you Thomas
