### ISSUE TITLE
port_name_prefix is ignored in add_ports_from_markers_center

### ISSUE THREAD

**Issue by simenmm** [gdsfactory/gdsfactory#2491]
I'm trying to use add_ports.add_ports_from_markers_center to automatically add ports to a library imported from gds files. I'm using port_name_prefix to set port names that are in accordance with the fab standard, not the gdsfactory standard. However, if port_type is not set, the prefix defaults to 'o'. To get the expected behavior, port_type has to be set to an arbitrary value in order to override.

**To Reproduce**

```
pin_layers = ('wg1', 'wg2', 'fiber', 'met1', 'met2')
port_prefixes = ['o', 'o', 'edge', 'dc', 'dc']
# port_types = ['optical', 'optical', 'optical', 'electrical', 'electrical']
port_types = ['OVERRIDE', 'OVERRIDE', 'OVERRIDE', 'OVERRIDE', 'OVERRIDE'] 
lays = [pdk.get_layer(layer=l) for l in pin_layers]

for i, lay in enumerate(lays):
            pcell = gf.add_ports.add_ports_from_markers_inside(component=pcell, pin_layer=lay, debug=True, short_ports=True, port_name_prefix=port_prefixes[i], port_type=port_types[i], skip_square_ports=True)
```

**Expected behavior**
I expect the port to be names after the specified port_prefix argument whenever it is used.

I tried commenting lines 158 and 159 in add_ports.py but it made no difference.

**Comment by joamatab** [comment]
fixed by https://github.com/gdsfactory/gdsfactory/pull/2503
