### ISSUE TITLE
add_ports_from_markers_center overwrites existing ports with same prefix

### ISSUE THREAD

**Issue by simenmm** [gdsfactory/gdsfactory#2492]
**Describe the bug**
I have multiple pin layers that should use the same port prefix. When I add ports automatically using add_ports_from_markers_center and loop over the layers, it starts counting from 1 every time, which causes conflicts when there are markers in multiple layers such as in vias or edge couplers.

**To Reproduce**
```
pin_layers = ('wg1', 'wg2', 'fiber', 'met1', 'met2')
port_prefixes = ['o', 'o', 'edge', 'dc', 'dc']
lays = [pdk.get_layer(layer=l) for l in pin_layers]

for i, lay in enumerate(lays):
            pcell = gf.add_ports.add_ports_from_markers_inside(component=pcell, pin_layer=lay, debug=True, short_ports=True, port_name_prefix=port_prefixes[i], skip_square_ports=True)
```

**Expected behavior**
When adding ports, check if there are existing ports with the same prefix, and count from the highest one instead of restarting.

**Suggested fix**
The following lines 160-163 in add_ports.py produces the behavior I want.
 
```
    port_no = sum([s.startswith(port_name_prefix) for s in component.ports.keys()])
    
    for i, p in enumerate(port_markers.polygons):
        port_name = f"{port_name_prefix}{i+1+port_no}" if port_name_prefix else str(i)
```

**Comment by joamatab** [comment]
Thank you Simen for the fix!

see https://github.com/gdsfactory/gdsfactory/pull/2503
