### ISSUE TITLE
Updated extrude leads to artefacts in small Euler bends

### ISSUE THREAD

**Issue by NicoHendrickx** [gdsfactory/gdsfactory#2527]
**Describe the bug**
As a result of the introduced rounding to nm in the extrude function (commit 94e7b076f9a5ad13978c649c073cbb7a94564dcd), artefacts appear for small angle Euler bends (and potentially more features).

**To Reproduce**
Example code:
```
from gdsfactory.components import bend_euler
import gdsfactory as gf

gf.clear_cache()
bend = bend_euler(0.2, 15, width=0.04)
bend.show()
```
Example behaviour:
<img width="1077" alt="Screenshot 2024-02-14 at 17 56 33" src="https://github.com/gdsfactory/gdsfactory/assets/10284442/da098501-f603-416b-b863-d5873eef3b9e">

**Expected behavior**
No artifacts should be present.

**Suggested fix**
This is caused as a result of the rounding of the path points before the extrusion. Can be fixed by doing the rounding on the polygon points instead:
Remove line 842:
`points = np.round(points, 3)`
Introduce new line 904:
`points_poly = np.round(points_poly, 3)`

This might probably lead to poor snapping, however.

**Comment by joamatab** [comment]
thank you for the fix Nico!

yes, that makes it look much better while keeping the ports on grid

![image](https://github.com/gdsfactory/gdsfactory/assets/4514346/cef7cba6-8747-40a6-a487-5e3e11b88ce3)
