### ISSUE TITLE
SiN waveguide design using AIM photonics 's PDK

### ISSUE THREAD

**Issue by SadiMJawadAhsan** [gdsfactory/gdsfactory#2549]
### Discussed in https://github.com/gdsfactory/gdsfactory/discussions/2548

<div type='discussions-op-text'>

<sup>Originally posted by **SadiMJawadAhsan** February 19, 2024</sup>
This is going to be my first project using gdsfactory. I am looking for any tutorial to import AIM photonics PDK and designing a waveguide using gdsfactory. I found a tutorial on YouTube but that is using UBC PDK I think. Any help is welcome.

Thanks</div>

**Comment by joamatab** [comment]
Hi,

I would not post any foundry information in public forums like this one, most foundries are very careful with their information to be accessible only under NDAs

therefore, as long as the PDKs are distributed under NDA we can't provide any tutorials in a public, you can contact the foundry to provide you with such tutorials
