### ISSUE TITLE
CrossSection bug with auto_widen

### ISSUE THREAD

**Issue by LuYouxi** [gdsfactory/gdsfactory#2564]
The taper waveguide structure generated is problematic when parameters of cladding and auto_wide are present in cladding function.

import gdsfactory as gf
si_section = gf.Section(width=0.45, offset=0, layer="WG", port_names=['o1', 'o2'])
si_cld_section = gf.Section(width=10, offset=0, layer="WGCLAD")

si_wg = gf.CrossSection(
    sections=[si_section, si_cld_section], 
    radius=5, 
    bbox_layers=["WGCLAD"], 
    bbox_offsets=[0], 
    auto_widen=True, 
    auto_widen_minimum_length=50, 
    width_wide= 1,
)

c = gf.Component("sample_connect")
mmi1 = c << gf.components.mmi1x2()
mmi2 = c << gf.components.mmi1x2()
mmi2.move((100, 50))
route = gf.routing.get_route(mmi1.ports["o2"], mmi2.ports["o1"], cross_section=si_wg)
c.add(route.references)
c.show()

![image](https://github.com/gdsfactory/gdsfactory/assets/35725059/7acc360f-e722-4071-8e8c-8c4ee3ebba66)

In past versions, the output of this script looked like this：
![image](https://github.com/gdsfactory/gdsfactory/assets/35725059/1890b4d2-cdbd-4bf6-b217-8270e972d64d)

**Comment by joamatab** [comment]
Thank you for reporting this,

can you try `pip install gdsfactory --upgrade`?


![image](https://github.com/gdsfactory/gdsfactory/assets/4514346/1b7d5b1b-96f9-40e6-8214-3bd4dac42ebf)


this should be fixed in the latest gdsfactory release 7.14.0

**Comment by LuYouxi** [comment]
> Thank you for reporting this,
> 
> can you try `pip install gdsfactory --upgrade`?
> 
> ![image](https://private-user-images.githubusercontent.com/4514346/308228725-1b7d5b1b-96f9-40e6-8214-3bd4dac42ebf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwODIzMDYsIm5iZiI6MTcwOTA4MjAwNiwicGF0aCI6Ii80NTE0MzQ2LzMwODIyODcyNS0xYjdkNWIxYi05NmY5LTQwZTYtODIxNC0zYmQ0ZGFjNDJlYmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjhUMDEwMDA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mjc1OTIxMjkxOGEwNjIxNWFjOGRjNDk3ZjlhMDk2Yjc0YzE1OWNmOWY0ZGNlNGZhNGI1ZDlmM2I5OTc4ODNjNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WVGdUivS1V_7Ak3RwJ_TkxU5dCYHPITHFk4X8YBn1Mk)
> 
> this should be fixed in the latest gdsfactory release 7.14.0

It has been repaired, thank you!
