### ISSUE TITLE
CrossSection 'sections' Type-Hinting Issue

### ISSUE THREAD

**Issue by lodoreds** [gdsfactory/gdsfactory#2635]
The docstring of `CrossSection` specifically asks to pass `sections` as a `Tuple[Sections]`, but pydantic won't allow the code to run if a tuple of Sections is passed. Instead, the code works with a `List[Sections]`. 

The following syntax leads to an error:
`cross_section=gf.CrossSection(sections=(gf.Section(width=1.0, layer=(1, 0), port_names=("o1", "o2"))), radius=10)`

The following syntax _does not_ lead to an error:
`cross_section=gf.CrossSection(sections=[gf.Section(width=1.0, layer=(1, 0), port_names=("o1", "o2"))], radius=10)`

Moreover, the pydantic error message is misleading, as it seems that  _all_ arguments are wrong:
pydantic_core._pydantic_core.ValidationError: 11 validation errors for CrossSection
sections.0
  Input should be a valid dictionary or instance of Section [type=model_type, input_value=('width', 1.0), input_type=tuple]
    For further information visit https://errors.pydantic.dev/2.6/v/model_type
sections.1
  Input should be a valid dictionary or instance of Section [type=model_type, input_value=('offset', 0), input_type=tuple]
    For further information visit https://errors.pydantic.dev/2.6/v/model_type
sections.2
  Input should be a valid dictionary or instance of Section [type=model_type, input_value=('insets', None), input_type=tuple]
    For further information visit https://errors.pydantic.dev/2.6/v/model_type
sections.3
  Input should be a valid dictionary or instance of Section [type=model_type, input_value=('layer', (1, 0)), input_type=tuple]
    For further information visit https://errors.pydantic.dev/2.6/v/model_type
sections.4
  Input should be a valid dictionary or instance of Section [type=model_type, input_value=('port_names', ('o1', 'o2')), input_type=tuple]
    For further information visit https://errors.pydantic.dev/2.6/v/model_type
sections.5
  Input should be a valid dictionary or instance of Section [type=model_type, input_value=('port_types', ('optical', 'optical')), input_type=tuple]
    For further information visit https://errors.pydantic.dev/2.6/v/model_type
sections.6
  Input should be a valid dictionary or instance of Section [type=model_type, input_value=('name', None), input_type=tuple]
    For further information visit https://errors.pydantic.dev/2.6/v/model_type
sections.7
  Input should be a valid dictionary or instance of Section [type=model_type, input_value=('hidden', False), input_type=tuple]
    For further information visit https://errors.pydantic.dev/2.6/v/model_type
sections.8
  Input should be a valid dictionary or instance of Section [type=model_type, input_value=('simplify', None), input_type=tuple]
    For further information visit https://errors.pydantic.dev/2.6/v/model_type
sections.9
  Input should be a valid dictionary or instance of Section [type=model_type, input_value=('width_function', None), input_type=tuple]
    For further information visit https://errors.pydantic.dev/2.6/v/model_type
sections.10
  Input should be a valid dictionary or instance of Section [type=model_type, input_value=('offset_function', None), input_type=tuple]
    For further information visit https://errors.pydantic.dev/2.6/v/model_type

**Comment by thomasdorch** [comment]
Hi, the issue here is that you're not actually passing it as a tuple. To create a tuple with just 1 element, you need to add a comma after the element, otherwise Python ignores the parenthesis and doesn't create a tuple:
```
cross_section=gf.CrossSection(sections=(gf.Section(width=1.0, layer=(1, 0), port_names=("o1", "o2")),), radius=10)
```
