### ISSUE TITLE
The gf.ponents.taper function has no effect on cross_section when it has a bbox parameter.

### ISSUE THREAD

**Issue by LuYouxi** [gdsfactory/gdsfactory#2637]
The gf.ponents.taper function has no effect on cross_section when it has a bbox parameter.
The code example is as follows:
import gdsfactory as gf

new_strip = gf.partial(
    gf.cross_section.cross_section,
    width=0.5,
    bbox_layers = ['WGCLAD'],
    bbox_offsets = [0],
    cladding_layers = ['WGCLAD'],
    cladding_offsets = [5],
)

taper = gf.components.taper(
    length = 10, 
    with1 = 0.5, 
    width2 =1,
    cross_section = new_strip
    )

taper.show()

![image](https://github.com/gdsfactory/gdsfactory/assets/35725059/668a04d2-8a5e-48d6-be18-e9e6acb148c5)

**Comment by joamatab** [comment]
thank you LuYouxi

see fix [here](https://github.com/gdsfactory/gdsfactory/pull/2641)
