### ISSUE TITLE
PDK Component Bugged: coupler_straight_asymmetric

### ISSUE THREAD

**Issue by KaylxJang** [gdsfactory/gdsfactory#2643]
Hi, I believe this component is defined incorrectly.

**To Reproduce**
Using the Generic PDK coupler_straight_asymmetric(), for example, the following parameters correctly define the input and output widths and gap:

`length: float = 10.0,
    gap: float = 0.1,
    width_top: float = 0.5,
    width_bot: float = 1,`
![image](https://github.com/gdsfactory/gdsfactory/assets/44301916/8548f5ad-9911-4d00-9721-042aa303174b)

But if the widths were flipped, the gap is wrong:

`length: float = 10.0,
    gap: float = 0.1,
    width_top: float = 1,
    width_bot: float = 0.5,`
![image](https://github.com/gdsfactory/gdsfactory/assets/44301916/fd9d745a-cde1-4be8-98ed-3b366505a0de)

The error is from under the coupler_straight_asymmetric function, line 30.
I believe the correct calculation is:
`top.movey(0.5 * (width_top + width_bot) + gap)`
instead of currently:
`top.movey(0.5 * abs(width_top - width_bot) + gap + width_top)`

This is a great PDK and gdsfactory is amazing, thanks for the support!

**Comment by joamatab** [comment]
awesome! thank you for reporting this and proposing the solution, see fix here

https://github.com/gdsfactory/gdsfactory/pull/2644
