### ISSUE TITLE
port positions wrong for `components.array` with `centered = True`

### ISSUE THREAD

**Issue by thanojo** [gdsfactory/gdsfactory#2651]
**Describe the bug**
When creating an array of components (this issue may also apply to other array-like structures in the generic pdk) with [`components.array`](https://github.com/gdsfactory/gdsfactory/blob/37642db3f51d158c8cb4bd62fa8751534b74b575/gdsfactory/components/array_component.py#L10) , using the `centered == True` flag results in the ports ending up in somewhat wrong positions (all equally offset from the expected positions, I haven't checked the exact offsets).

**To Reproduce**
```python
import gdsfactory as gf
C = gf.Component()
array = C << gf.components.array(gf.components.straight(length = 5), spacing = (10,10), columns = 2, rows = 2, centered = True)
C.add_ports(array.ports)
C.show(show_ports=True)
```

**Expected behavior**
The ports remain in the correct positions relative to the original components in the array

**Suggested fix**
Replace [lines 58-76](https://github.com/gdsfactory/gdsfactory/blob/37642db3f51d158c8cb4bd62fa8751534b74b575/gdsfactory/components/array_component.py#L58) with the following (original code commented out)
```python 
    old_center = ref.center
    ref.center = (0, 0) if centered else old_center
    center_shift = ref.center - old_center
    

    if add_ports and ref.ports:
        for col in range(int(columns)):
            for row in range(int(rows)):
                for port in component.ports.values():
                    name = f"{port.name}_{row+1}_{col+1}"
                    c.add_port(name, port=port)
                    # if centered:
                    #     c.ports[name].move(
                    #         (
                    #             (col - columns / 2 + 0.5) * spacing[0],
                    #             (row - rows / 2 + 0.5) * spacing[1],
                    #         )
                    #     )

                    # else:
                    c.ports[name].move((col * spacing[0], row * spacing[1]) + center_shift)
```

**Comment by joamatab** [comment]
awesome! thank you for the fix! 

see fix here

https://github.com/gdsfactory/gdsfactory/pull/2655
