### ISSUE TITLE
Text Justify Position

### ISSUE THREAD

**Issue by lzrbeamer** [gdsfactory/gdsfactory#2663]
The text function includes a 2um offset from the specified position when justify='left'. Example below shows justify='right' works as expected with the right edge located at x=0, while the justify='left' shows that the left edge is located at x=2um.

**To Reproduce**
import gdsfactory as gf
c = gf.Component('Top')
c << gf.components.text(text='000', size=20, position=(0, 0),  layer=(1,0), justify='right')
c << gf.components.text(text='000', size=20, position=(0, 30),  layer=(1,0), justify='left')
c.show()
 
![image](https://github.com/gdsfactory/gdsfactory/assets/155932576/5a91525f-c5ca-4cb1-9c4d-2d5c3629999e)

**Expected behavior**
I expect both the 'left' and 'right' justified elements to be at same location

**Suggested fix**
Replace 'pass' with label.xmin = position[0]

`@gf.cell
def text(
    text: str = "abcd",
    size: float = 10.0,
    position: Coordinate = (0, 0),
    justify: str = "left",
    layer: LayerSpec = "WG",
    layers: LayerSpecs | None = None,
) -> Component:
    """Text shapes.

    Args:
        text: string.
        size: in um.
        position: x, y position.
        justify: left, right, center.
        layer: for the text.
        layers: optional for duplicating the text.
    """
    scaling = size / 1000
    xoffset = position[0]
    yoffset = position[1]
    t = gf.Component()
    layers = layers or [layer]

    for line in text.split("\n"):
        label = gf.Component()
        for c in line:
            ascii_val = ord(c)
            if c == " ":
                xoffset += 500 * scaling
            elif 33 <= ascii_val <= 126:
                for poly in _glyph[ascii_val]:
                    xpts = np.array(poly)[:, 0] * scaling
                    ypts = np.array(poly)[:, 1] * scaling
                    for layer in layers:
                        label.add_polygon([xpts + xoffset, ypts + yoffset], layer=layer)
                xoffset += (_width[ascii_val] + _indent[ascii_val]) * scaling
            else:
                raise ValueError(f"No character with ascii value {ascii_val!r}")
        t.add_ref(label)
        yoffset -= 1500 * scaling
        xoffset = position[0]
    justify = justify.lower()
    for label in t.references:
        if justify == "left":
            #pass  ####Remove this 
            label.xmin = position[0] #### Suggested fix 
        elif justify == "right":
            label.xmax = position[0]
        elif justify == "center":
            label.move(origin=label.center, destination=position, axis="x")
        else:
            raise ValueError(
                f"justify = {justify!r} not in ('center', 'right', 'left')"
            )
    return t.flatten()`

**Comment by joamatab** [comment]
awesome! thank you for the fix! 

i can make a release with the new fix

https://github.com/gdsfactory/gdsfactory/pull/2666
