### ISSUE TITLE
Issue on page /_modules/gdsfactory/components/ring_single_bend_coupler.html

### ISSUE THREAD

**Issue by nikit-k-a** [gdsfactory/gdsfactory#2667]
In function "coupler_bend" there is an element (output waveguide):
`    output = gf.get_component(bend_euler, angle=angle_outer).mirror()
`
The parameter "cross_section" was not set explicitly here. This way, when you call "ring_single_bend_coupler" function with cross_section of arbitary width (0.3 um for example), there would be a mismatch with this euler output waveguide.

**Comment by joamatab** [comment]
Thank you Nikita!

see fix [here](https://github.com/gdsfactory/gdsfactory/pull/2668)
