### ISSUE TITLE
how to create two independent cells in gdsfactory?

### ISSUE THREAD

**Issue by wuzhonghan** [gdsfactory/gdsfactory#2673]
Hi,

I have a question：How to create two independent cells in gdsfactory?

in GDSTK, I can create two cells like below:

```
import gdstk

lib = gdstk.Library()

cell1 = lib.new_cell("FIRST")
cell2 = lib.new_cell("SECOND")

rect = gdstk.rectangle((0, 0), (2, 1))
cell1.add(rect)
cell2.add(rect)
```
![image](https://github.com/gdsfactory/gdsfactory/assets/124678531/a7c953c5-fb94-4819-b4f4-9c79f4988904)

How can I create two cells or more like this using gdsfactory?

**Comment by joamatab** [comment]
very similar in gdsfactory,

the main difference is that we always create a top cell

```python

import gdsfactory as gf

c = gf.Component('top')
cell1 = gf.Component("FIRST")
cell2 = gf.Component("SECOND")

rect = gf.c.rectangle((0, 0), (2, 1))
cell1.add_ref(rect)
cell2.add_ref(rect)
c.show()
````

**Comment by wuzhonghan** [comment]
> very similar in gdsfactory,
> 
> the main difference is that we always create a top cell
> 
> ```python
> import gdsfactory as gf
> 
> c = gf.Component('top')
> cell1 = gf.Component("FIRST")
> cell2 = gf.Component("SECOND")
> 
> rect = gf.components.rectangle(size=(2, 1))
> cell1.add_ref(rect)
> cell2.add_ref(rect)
> c.show()
> ```

Thanks, do you mean that I can only create cells like this?
![image](https://github.com/gdsfactory/gdsfactory/assets/124678531/94efcad2-bfcb-4add-aa7e-5bbee7f038a6)

**Comment by joamatab** [comment]
yes

**Comment by wuzhonghan** [comment]
thanks!
