### ISSUE TITLE
The broken promise of gds_import (cell name collisions overwriting previous imports in cache)

### ISSUE THREAD

**Issue by sequoiap** [gdsfactory/gdsfactory#2688]
**Describe the bug**
If you import two different GDS files with the same cell names, they overwrite each other, even with ``unique_names=True``.

**To Reproduce**
Let's create a few sample GDS files with name collisions to read back in:

```{python}
import gdstk

# Make the first component, a mock GC
lib = gdstk.Library()
toplevel = lib.new_cell("toplevel")
cell = lib.new_cell("tmp_cell")
shape = gdstk.Polygon([(-10, -50), (-0.25, 0), (0.25, 0), (10, -50)], 1, 0)
cell.add(shape)
toplevel.add(gdstk.Reference(cell))
lib.write_gds("gc.gds")

# Make the second component, a mock taper
lib = gdstk.Library()
toplevel = lib.new_cell("toplevel")
cell = lib.new_cell("tmp_cell")
shape = gdstk.Polygon([(-0.25, 0), (-0.05, 40), (0.05, 40), (0.25, 0)], 1, 0)
cell.add(shape)
toplevel.add(gdstk.Reference(cell))
lib.write_gds("taper.gds")
```

Let's wrap them as components as though we were building a PDK to distribute:

```
import gdsfactory as gf
from gdsfactory.generic_tech import get_generic_pdk

pdk = get_generic_pdk()
pdk.activate()

@gf.cell
def gc():
    c = gf.import_gds("gc.gds")
    c.add_port("o1", (0,0), 0.5, 90, layer=(1,10))
    return c

@gf.cell
def taper():
    c = gf.import_gds("taper.gds")
    c.add_port("o1", (0,0), 0.5, 270, layer=(1,10))
    return c
```

Now, if we add them to the same component when trying to build a circuit, the latter import has overwritten the former.

```
@gf.cell
def circuit1():
    c = gf.Component()
    gc0 = c << gc()
    tpr = c << taper()
    tpr.rotate(90)
    tpr.move((0, 10))
    return c

circuit1()
```

Instead of my mock GC next to a mock taper, my GC has been turned into a taper.

![image](https://github.com/gdsfactory/gdsfactory/assets/36747422/f81e6466-0b85-4ef6-991f-279366c9fc7e)

**Expected behavior**
I would expect to have two unique components, despite the cells in the two GDS files having overlapping names. I would have expected the ``unique_names`` argument that is by default ``True`` in ``import_gds`` file to have renamed the offending cells at import time so that the cache wouldn't get overwritten.

**Suggested fix**
I don't fully understand how caching works, or at what stage it occurs in ``import_gds``. However, it seems that the ``Component.rename`` function only even interacts with the cache if the new name is different from the original name. Since ``Component.name`` returns ``Component._cell.name``, ``rename`` always gets the same name as the existing name, so it never even interacts with the cache to check for duplicates.

Another interesting thing as I stepped through the code with a debugger, within the context of the ``rename`` function, the ``CACHE`` dictionary was **always** empty. Seemed strange.

**Comment by joamatab** [comment]
Hi Sequoia,

thanks for reporting this edge case, See [fix](https://github.com/gdsfactory/gdsfactory/pull/2689) here
