### ISSUE TITLE
gf.component.write_stl() by default draws convex_hull for invalid geometries

### ISSUE THREAD

**Issue by cjcarver** [gdsfactory/gdsfactory#2699]
When trying to export a component to a 3d format I ran into an issue where any closed loops in a geometry on a certain layer would not export as I intended. I realize now that since we don't represent holes in polygons with separated interior and exterior polygons, shapely will mark these as invalid. By default in `to_stl()` the `hull_invalid_polygons` parameter is set to True. 

For example this MZI `gf.components.mzi()`
![image](https://github.com/gdsfactory/gdsfactory/assets/46500432/e5f41b10-d1ca-4632-b530-93bf644539fc)

When we use `gf.Component.write_stl()` will turn into this
<img width="819" alt="image" src="https://github.com/gdsfactory/gdsfactory/assets/46500432/0ae8fa4d-0645-46eb-b241-fe080f84e0e3">

If we let invalid polygons through we get what I would have expected `gf.Component.write_stl(hull_invalid_polygons=False)` with no errors
<img width="782" alt="image" src="https://github.com/gdsfactory/gdsfactory/assets/46500432/b7a2ab96-aeb6-42f0-984d-79cb847c5517">

I suggest we change the default of `hull_invalid_polygons` to be False or remove this functionality entirely as I'm not sure the usefulness of it. Maybe I'm not considering some posible edge cases where this is useful but for example in `gf.Component.to_3d()` here we pretty much do same the thing but it just doesn't even have the option to hull invalid polygons. 

If for some reason we want to an option to make a polygon valid instead we could either use `shapely.validation.make_valid()` and convert it to a MultiPolygon or simply just run `polygon.buffer(0)` to make the polygon valid. The first option is probably better just in case there are holes inside of holes.

**Comment by joamatab** [comment]
Thank you Christian!

see PR

https://github.com/gdsfactory/gdsfactory/pull/2702
