### ISSUE TITLE
Scripts/gf-script.py file incorrect format for file-watcher

### ISSUE THREAD

**Issue by oz99** [gdsfactory/gdsfactory#2721]
# Bug Description
#### Upon attempting to use the file-watcher YAML and Python flow, the Scripts/gf-script.py file within the conda environment returns: 

gf watch --path c:\Users\Test\miniconda3\Lib\site-packages\gdsfactory\samples\demo\circuitssfactory\samples\demo\circuits
Traceback (most recent call last):
  File "c:\Users\Test\miniconda3\Scripts\gf-script.py", line 5, in <module>    
    from gdsfactory.gf import gf
ModuleNotFoundError: No module named 'gdsfactory.gf'

#### The gf-script.py file is the following: 

import re
import sys
from gdsfactory.gf import gf
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(gf())

**Comment by joamatab** [comment]
Hi Ozan, what version of gdsfactory are you using?

can you try `pip install gdsfactory --upgrade`?

**Comment by oz99** [comment]
Hey Joaquin, 

I'm using version 7.3.5. Upgrading via pip worked! Thanks

For those watching this later on note I originally installed gdsfactory via conda. 

![image](https://github.com/gdsfactory/gdsfactory/assets/61252138/2a58db0f-85bd-4039-b959-431ef903a0cb)

**Comment by joamatab** [comment]
yes, good point, we have been recommending people installing it with pip
