### ISSUE TITLE
PydanticUserError

### ISSUE THREAD

**Issue by chamithri-A** [gdsfactory/gdsfactory#2728]
I havent been able to fix this

Exception has occurred: PydanticUserError
A non-annotated attribute was detected: `substrate = LayerLevel(layer=(99999, 0), thickness=10.0, thickness_tolerance=None, zmin=-13.0, material='si', sidewall_angle=0.0, sidewall_angle_tolerance=None, width_to_z=0.0, z_to_bias=None, mesh_order=99, layer_type='grow', mode=None, into=None, doping_concentration=None, resistivity=None, bias=None, derived_layer=None, info={})`. All model fields require a type annotation; if `substrate` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.

For further information visit https://errors.pydantic.dev/2.7/u/model-field-missing-annotation

**Comment by fp-matt** [comment]
Hi @chamithri-A,

I also ran into this a recently, and from what I understand, pydantic is essentially a type checker - do you encounter the same error if you add type hints to your attributes?

for example, do you get the same error if you try putting

```
substrate: LayerLevel = LayerLevel(layer=(99999, 0), ...
```
