### ISSUE TITLE
Disk Resonator straight bus waveguide

### ISSUE THREAD

**Issue by gcharalampous** [gdsfactory/gdsfactory#2738]
**Describe the bug**
The disk resonator has a bug when the wrap_angle_deg=0

**To Reproduce**
import gdsfactory as gf
c = gf.components.disk(radius=10.0, gap=0.2, wrap_angle_deg=0.0, parity=1, cross_section='xs_sc')
c.plot()

**Expected behavior**
The disk resonator should get straight bus waveguide.

**Suggested fix**
Removed the extra set of parenthesis from the tuple

```
circle.move(
    origin=circle.center,
    destination=(straight_left.ports["o2"].center + (0, r_bend))
)
```

**Comment by joamatab** [comment]
awesome! thank you Georgios!

https://github.com/gdsfactory/gdsfactory/pull/2745
