### ISSUE TITLE
Grating coupler array generic PDK component does not utilize `cross_section` argument

### ISSUE THREAD

**Issue by jonbenfri** [gdsfactory/gdsfactory#2740]
When calling the `grating_coupler_array` function with a custom `cross_section` argument, the default cross-section string `'xs_sc'` is used.

The problem is in the `grating_coupler_array.py` file where the `cross_section` data should be passed:

https://github.com/gdsfactory/gdsfactory/blob/412377283731f0f69cd6728adb60a7e1ba35c6cc/gdsfactory/components/grating_coupler_array.py#L38

The fix would be to add `cross_section=cross_section` to the `get_component` call.

**Comment by joamatab** [comment]
i think the easiest solution is to pass both a grating coupler with the correct cross_section

this fix created issues in cspdk

[see](https://github.com/gdsfactory/gdsfactory/actions/runs/9081781521/job/24956525085)
