### ISSUE TITLE
fix kfactory dependency version

### ISSUE THREAD

**Issue by tvt173** [gdsfactory/gdsfactory#2775]
**Describe the bug**
The version requirements for kfactory are too loose. When installing gdsfactory with an old version of kfactory already installed, gdsfactory will fail on load.

**To Reproduce**
Try installing gdsfactory after installing kfactory 0.12 or lower.

**Expected behavior**
gdsfactory runs without issue

**Suggested fix**
Update the requirements... maybe `"kfactory[git,ipy]>=0.13.0,<0.14"` ?

@sebastian-goeldi
@joamatab

**Comment by joamatab** [comment]
Yes, we need a new kfactory release

**Comment by sebastian-goeldi** [comment]
I think I suggested @joamatab to use the following until we are close to release
`kfactory @ git+https://github.com/gdsfactory/kfactory.git#main`

**Comment by joamatab** [comment]
yes, we'll need to release a new kfactory before this gdsfactory release

**Comment by joamatab** [comment]
this should be fixed
