### ISSUE TITLE
xmin, ymin, setter are still in DBU

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#2795]
xmin, ymin, setter are still in DBU

![Image](https://github.com/gdsfactory/gdsfactory/assets/4514346/c44d274c-7d78-477c-a48a-64838fe64d2d)

@sebastian-goeldi

**Comment by sebastian-goeldi** [comment]
Damn :(.

But we can do the same thing as getarr. I thought that would already fix it, but probably not for the simple setters. I can make a pr later to fix it

**Comment by joamatab** [comment]
see fix here

https://github.com/gdsfactory/gdsfactory/pull/2794
