### ISSUE TITLE
fix get_netlist for InstanceArray

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#2823]
```
    component_type = "pad_array"
    c1 = cells[component_type]()
    n = c1.get_netlist(allow_multiple=True)
    yaml_str = OmegaConf.to_yaml(n, sort_keys=True)
    c1.delete()
    # print(yaml_str)
    c2 = gf.read.from_yaml(yaml_str)
    n2 = c2.get_netlist()
    d = jsondiff.diff(n, n2)
    print(d)
    c2.show()
```

the netlist extraction for arrays is not working correctly, 

- first, the instance ports are on top of each other (therefore need to use `allow_multiple=True`
- second, the recontrcuted pads are all on top of each other

@tvt173 
@sebastian-goeldi

**Comment by tvt173** [comment]
fixed via https://github.com/gdsfactory/gdsfactory/pull/2846
