### ISSUE TITLE
document issue

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#2834]
There is some issue in the docs with virtual instances

![Image](https://github.com/gdsfactory/gdsfactory/assets/4514346/56db55ed-96e9-4004-b658-08f5307045a5)

@sebastian-goeldi

**Comment by joamatab** [comment]
i fixed it by running show before plot



![Image](https://github.com/gdsfactory/gdsfactory/assets/4514346/9b41443a-1489-47d0-bedc-b2064a5dbb07)



why is that?

**Comment by sebastian-goeldi** [comment]
I think show calls `.insert_vinsts` and plot might not
