### ISSUE TITLE
Gdsfactory 8: cell.get_polygons() does not return datatypes

### ISSUE THREAD

**Issue by flaport** [gdsfactory/gdsfactory#2869]
**Describe the bug**
In gdsfactory<8 cell.get_polygons() returned (layer, datatype) tuples mapping to polygons. The current cell.get_polygons() only returns a layer index mapping to polygons. This is inconsistent with the previous version and moreover there is no way to retrieve the datatype from the polygons either.

**To Reproduce**
Try cell.get_polygons() and see for yourself.

**Expected behavior**
We want (layer, datatype) tuples as keys of the resulting dictionary

**Suggested fix**
Not sure. Haven't been able to figure it out.

@joamatab @sebastian-goeldi @tvt173

**Comment by sebastian-goeldi** [comment]
Can you inspect the exact type of the returned object?

To my knowledge it should be a `LayerEnum`, which has the desired info either with:

`layerindex.layer, layerindex.datatype`

Or you can directly cast it to a tuple for similar behavior to before

`tuple(layerindex)`

**Comment by flaport** [comment]
No it's just an integer. Currently I'm using the integer to get the layer tuple from cell.layout().layer_infos(), but it's not super convenient.
