### ISSUE TITLE
Spiral Features in v8.1 removed

### ISSUE THREAD

**Issue by Priyash-Barya** [gdsfactory/gdsfactory#2879]
I used to use spiral_external_io in my previous code which were based on 7.27 version. The recent update has made my previous code unusable as I cant find many of the spiral features like the spiral_external_io. How do use it in the latest version?

**Comment by joamatab** [comment]
Hi, 

have you taken a look at `gf.components.spiral`?  this component is equivalent to spiral_external_io in gdsfactory7
