### ISSUE TITLE
Naming Cells in Hierarchical Components

### ISSUE THREAD

**Issue by LIU-Yinyi** [gdsfactory/gdsfactory#2906]
**Describe the bug**
In gdsfactory v7, there is an **alias** option when `component.add_ref(cell, alias="<name>")` for improving readability, while it is deprecated in v8. As suggested by warning and migration guide, using **name** in a hierarchical cells may trigger the **kdb existing cellname** problem. 

**To Reproduce**
I built a framework in v7 for fast schematic-layout transform and simulation:

```python
# for simplicity, only show the relevant codes
class Circuit:
  def __init__(self):
    self.final_gds = gf.Component(self.__class__.__name__)
    self.instances = {}
    self.placement = {}
    self.exposed_ports = {}
    self.update()
```

For a customized MZI basic cell:
```python
class MZI(Circuit):
  def update(self):
    self.instances = {
      'wg1': gf.components.straight(...),
      'wg2': gf.components.straight(...),
      'mmi1': gf.components.mmi(...),
      'mmi2': gf.components.mmi(...),
    }

    # here work well in v7 but trigger error in v8
    for k, v in self.instances.items():
      ref = self.final_gds.add_ref(v, alias=k)
      self.placement[k] = ref
```

For hierarchy circuits:
```python
class MyChip(Circuit):
   def update(self):
     self.instances = {
       'mzi1': MZI(),
       'mzi2': MZI(),
     }
```
It works well in v7 but in v8, the error seems from `kfactory`:
```
File [/depends/miniconda3/envs/gds/lib/python3.11/site-packages/kfactory/kcell.py:787), in KCell.__init__(self, name, kcl, kdb_cell, ports)
    785 else:
    786     _name = name
--> 787 self._kdb_cell = kdb_cell or kcl.create_cell(_name)
    788 if _name == "Unnamed_!":
    789     self._kdb_cell.name = f"Unnamed_{self.cell_index()}"
...
   3658         f"Cellname {name} already exists. Please make sure the cellname is"
   3659         " unique or pass `allow_duplicate` when creating the library"
   3660     )

ValueError: Cellname MZI already exists. Please make sure the cellname is unique or pass `allow_duplicate` when creating the library
```

**Expected behavior**
Is there any method to manually reset the kdb or allow **alias** in kfactory? BTW, I often do optimization using my framework through Jupyter Notebook, and I found that any code rerun <ins>without resetting the python kernel</ins> will also trigger the **cellname already exists** problem. Any suggestions?

**Suggested fix**
It seems to require modification in `kfactory`.

**Comment by sebastian-goeldi** [comment]
This cannot be achieved with KLayout. The problem is that you create two cells with the same name.

You need to do some caching or similar to resolve that.

In general I wouldn't recommend building cells in classes. You needs to create unique names per Component() call or return an existing one. Caching would achieve the latter one.

You can try to use the `@gf.cell` decorator but I am not sure it will work in your case as I think the cache would be instance specific

**Comment by tvt173** [comment]
hi @LIU-Yinyi, if you must build your cell from a class, i recommend looking at the discussion here: https://github.com/gdsfactory/gdsfactory/issues/2294

the key is to always build your cells within a cell decorator. building your cell without wrapping it in `@gf.cell` is not very safe...

**Comment by sebastian-goeldi** [comment]
@LIU-Yinyi the `@cell` decorator should already take care of that for you. Indeed dicts and lists are a bit a nuisance, but it casts lists to tuples (and I think tuples of tuples in case of list of lists, but I am not entirely sure of that) and dicts use frozensets (and back in the function) https://docs.python.org/3/library/functions.html#func-frozenset

therefore, I would suggest to directly try the cell decorator and if it fails, open a new issue with a case where it fails. Note though, if you pass too complex objects, e.g. something with the `name` attribute it should be unique (i.e. singleton like behavior wrt its name)

**Comment by sebastian-goeldi** [comment]
You can also treat the new KLayout-backend like a "global" cache if you are sure names are enough to identify a component:

```python

try:
    c = gf.kcl[my_component_name]
except ValueError:
   c = gf.Component(my_component_name)
   # Construct component here ...
```

This is more or less a global cache as long as you know your componnent's name
