### ISSUE TITLE
Ability to use grid with circles (ellipses)

### ISSUE THREAD

**Issue by fizixmastr** [gdsfactory/gdsfactory#2940]
The grid function currently doesn't work with circles (or ellipses) and perhaps other shapes too. This seems to be because it is enforcing adding ports to all objects (I have verified that muting the add ports loop allows the grid to be made without issue). I have only been using GDSfactory for a few days, so I don't know if there is a better way implement this change, but I simply added a bool that turns off the ports loop.

**Comment by joamatab** [comment]
fixed by https://github.com/gdsfactory/gdsfactory/pull/3295
