### ISSUE TITLE
cross_section() and CrossSection init do not have same signature

### ISSUE THREAD

**Issue by tvt173** [gdsfactory/gdsfactory#297]
A `CrossSection` can have a callable as its width or offset, but this is not allowed in the signature of `cross_section()`. The signature of the cross_section function should be updated to match, or the function should be removed entirely if there is no reason to have both.

**Comment by joamatab** [comment]
thank you Troy!

i updated the cross_section signature

https://github.com/gdsfactory/gdsfactory/pull/299/files#diff-afb7944ac1faeba45adb5dab6e60c6e84dec68c225bddf629314184e73332c51
