### ISSUE TITLE
pip install gdsfactory[full] on macOS - Update Tutorial?

### ISSUE THREAD

**Issue by Jan-David-Black** [gdsfactory/gdsfactory#298]
I had some problems with installing gdsfactory[full] on macos

```bash
% pip install gdsfactory[full]
zsh: no matches found: gdsfactory[full]
```

as it turns out macOS does not like the syntax `gdsfactory[full]` thus one should use
```
% pip install "gdsfactory[full]"
```

Regards

**Comment by joamatab** [comment]
Thank you David

I updated the docs

https://github.com/gdsfactory/gdsfactory/pull/299/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
