### ISSUE TITLE
Inconsistent Port Type Definitions

### ISSUE THREAD

**Issue by Daasein** [gdsfactory/gdsfactory#2990]
#### Description:
In `gdsfactory`, there is an inconsistency in how port types are defined across different components. For example, when creating a rectangle component with `gf.components.rectangle(size=(10, 2), port_type='mechanical')`, the `port_type` parameter allows a single string ('mechanical'), which sets all port types to 'mechanical'. However, when creating a taper component with `gf.components.taper(port_types=('mechanical', 'mechanical'))`, the `port_types` parameter requires a tuple of strings. If a single string 'mechanical' is passed to `port_types`, it is treated as an iterable, causing the generated taper ports to be set to 'm' and 'e'.

#### Steps to Reproduce:
1. Create a rectangle with `gf.components.rectangle(size=(10, 2), port_type='mechanical')`.
2. Create a taper with `gf.components.taper(port_types='mechanical')`.

#### Expected Behavior:
The `port_types` parameter in `gf.components.taper` should accept a single string in the same manner as `port_type` in `gf.components.rectangle`, ensuring consistent and predictable behavior.

#### Actual Behavior:
Passing a single string 'mechanical' to `port_types` in `gf.components.taper` results in ports being set to 'm' and 'e' instead of the expected 'mechanical'.

#### Suggested Solution:
Standardize the handling of port type parameters across different components in `gdsfactory`. Either:
- Allow `port_types` to accept a single string and apply it to all ports, or
- Ensure clear documentation and type checking to prevent single strings from being treated as iterables.

**Comment by joamatab** [comment]
Thank you for catching this!

See issue addressed here https://github.com/gdsfactory/gdsfactory/pull/2991
