### ISSUE TITLE
grid_with_text example with text size

### ISSUE THREAD

**Issue by alexsludds** [gdsfactory/gdsfactory#302]
Hi folks,
I want to use the grid_with_text code to quickly laying out test structures, but I am confused how one puts in a text size to it. I noticed that it takes a text/text_rectangular object, but passing a size into this object throws errors.
Also, in general it would be great to add an example of the grid_with_text object.

Best,
-Alex

**Comment by joamatab** [comment]
Hi Aex,

let me know if this PR https://github.com/gdsfactory/gdsfactory/pull/305 makes it more clear

**Comment by alexsludds** [comment]
This clears it up for me,
Thank you Joaquin!

**Comment by joamatab** [comment]
Awesome 

Thank you Alex!
