### ISSUE TITLE
Enhancement Request: Implement `get_ports_list` for `ComponentReference`

### ISSUE THREAD

**Issue by Daasein** [gdsfactory/gdsfactory#3028]
Currently, the `get_ports_list` method is available for the `Component` class, which is highly useful for retrieving a list of ports with specific attributes. However, for the `ComponentReference` class, we can only obtain all ports using the `.ports` attribute. Implementing `get_ports_list` for `ComponentReference` would significantly enhance its usability, especially in scenarios involving complex transformations and routing requirements.

# Use Case
Consider a scenario where we have a large instance array, and several transformations have been applied to it. Each item in the array has four differently oriented ports. We need to perform a `route_bundle` operation from other parts to every port in this array that has an orientation of 180 degrees. 

Currently, we must write a loop to extract these ports from `reference.ports`, because calling `get_ports_list` on the array component returns ports that are not transformed. This process is cumbersome and error-prone.

# Proposed Solution:
Implement the `get_ports_list` method for the `ComponentReference` class. This method should:
- Allow filtering ports based on specific attributes (just like what `Component.get_ports_list()` do).
- Return ports with the correct transformations applied.

Benefits:
- Streamlined code: Avoids the need for manual loops and port extraction.
- Improved readability: Clear and concise port retrieval within complex transformations.
- Enhanced functionality: Leverages the existing `get_ports_list` capabilities within `ComponentReference`.

**Comment by sebastian-goeldi** [comment]
It is there ;)

`ref.ports.filter`

**Comment by joamatab** [comment]
you can also use `gf.port.get_ports_list()` which works both for Components and Instances
