### ISSUE TITLE
kdb.DPolygon

### ISSUE THREAD

**Issue by SMSajadi99** [gdsfactory/gdsfactory#3035]
Hello
I had a question for you, I just came across your nice project.
I did not understand a part of your tutorial:

```
gf.kdb.DPolygon
```
What does kdb mean and what does it do?

**Comment by joamatab** [comment]
Klayout DataBase

**Comment by SMSajadi99** [comment]
@joamatab thanks for attention, I had another question for you

```
add_polygon([(-8, -6), (6, 8), (7, 17), (9, 5)], layer=(1, 0))
```
and

```
gf.kdb.DPolygon
```

What is the difference between the above two methods (I feel they work the same, right?)
