### ISSUE TITLE
No Component Name in path.extrude

### ISSUE THREAD

**Issue by lodoreds** [gdsfactory/gdsfactory#3061]
**Issue**
In gf 6.8.1, a ComponentAllAngle contaning an extruded path cannot be shown because the extruded path is stored in a cell without name.

**To Reproduce**
The following generates `ValueError: Cannot insert a non-flattened VInstance into a VKCell when the name is 'None'. VKCell at r0 *1 0,0`.

```
from math import radians
import numpy as np
import gdsfactory as gf
from gdsfactory.component import ComponentAllAngle


def f(t, a=2):
    x = np.exp(-a * t)
    return np.round(x, 3) + x % 2


radius = 10

cross_section2 = gf.CrossSection(
    sections=[
        gf.Section(
            width=0,
            width_function=f,
            layer=(1, 0),
            port_names=("o1", "o2"),
        )
    ],
    radius=radius,
)

n_points = abs(int(45 / 360 * radius / 0.01))
t = np.linspace(0, radians(45) / 2, n_points)
x1 = radius * np.cos(t)
y1 = radius * np.sin(t)

p1 = gf.Path(path=np.array([x1, y1]).T)
c = gf.ComponentAllAngle(name="test")
b1 = c.create_vinst(gf.path.extrude(p1, cross_section=cross_section2, all_angle=True))

c.show()

```

**Suggested fix**
The issue is in line 817 of `path.py`, where `ComponentAllAngle` and `Component` are initialized without a name:
```
c = ComponentAllAngle() if all_angle else Component()
```

Providing a name solves the issue:
```
c = ComponentAllAngle(name="extruded_path") if all_angle else Component(name="extruded_path")
```

**Extra**
Without the `x % 2` in the width function I get `ValueError: dwidth needs to be even to snap to grid. Got 0.135`. 
Does that even matter for a ComponentAllAngle, since the polygon just snaps to some non-aligned points?
If no path can be instantiated with odd widths, then it would make sense to apply the modulo division directly in the path function, so that just any function could be used.

**Comment by sebastian-goeldi** [comment]
If you wrap your code into a function and decorate it with `gf.vcell` you will not have this problem. Or you just give your component a name with `c.name = "mynamehere" `


It would be an option to name a VKCell like your suggestion. It will come to haunt you when you do this twice though.

Wrt path width. It kinda matters. Do you want e.g. a path from (0,0) to (10,0) that produces a polygon that will result in the following?

`(0,5),(10,5),(0,-4.999),(10,-4.999)`

I wouldn't. I also don't like functions just rounding my numbers without informing me, but that is rather a matter lf taste, though I would always advocatefor accuracy over hidden behavior.

**Comment by lodoreds** [comment]
Thanks! By all means, vcell is the way to go, since it avoids duplicate names.  I just issued a pull request with the change.

Concering the path, that was just an example. In general, I would like to be able to draw any kind of shape with any width profile. As for rounding, we are talking about +-1 nm,  so that does not feel too critical, but I also understand the concern. However, since the action must to be performed for the code to work at all, that could also be taken care of by path itself, instead of being manually added by the user for every width profile.

**Comment by sebastian-goeldi** [comment]
Wait, no that's not what I meant. Imo it makes no sense to have cells named "path_....". So what you should do is name the returned VKCell:

```python
@vcell
def my_bend(...):
    return extrude_path(...)
```
This way you control the parameters (vs what feels like 200 parameters in path extrude) and you can easily choose the name of the resulting component.

+-1nm does matter in some cases though. I would advocate to have an optional flag for rounding then though.

**Comment by lodoreds** [comment]
I thought that was what you meant too, but it doesn't work (I tried, the code was originally a function that I simplified to explain the bug). The problem is not the cell in my bend, it's the cell returned by path.extrude.

**Comment by sebastian-goeldi** [comment]
not sure what you were doing exactly but this definitely works:

```python
import gdsfactory as gf
import numpy as np


def f(t: float, a: float = 2) -> float:
    x = np.exp(-a * t)
    return np.round(x, 3) + x % 2


@gf.vcell
def my_cell() -> gf.Component:
    radius = 10

    cross_section2 = gf.CrossSection(
        sections=[
            gf.Section(
                width=0,
                width_function=f,
                layer=(1, 0),
                port_names=("o1", "o2"),
            )
        ],
        radius=radius,
    )

    n_points = abs(int(45 / 360 * radius / 0.01))
    t = np.linspace(0, np.deg2rad(45) / 2, n_points)
    x1 = radius * np.cos(t)
    y1 = radius * np.sin(t)

    p1 = gf.Path(path=np.array([x1, y1]).T)
    return gf.path.extrude(p1, cross_section=cross_section2)


my_cell().show()
```

![image](https://github.com/user-attachments/assets/0740590d-2e68-4278-90f2-eb27064ce0a5)

**Comment by sebastian-goeldi** [comment]
Not sure what you were doing exactly, but this definitely works:

```python
import gdsfactory as gf
import numpy as np


def f(t: float, a: float = 2) -> float:
    x = np.exp(-a * t)
    return np.round(x, 3) + x % 2


@gf.vcell
def my_cell() -> gf.Component:
    radius = 10

    cross_section2 = gf.CrossSection(
        sections=[
            gf.Section(
                width=0,
                width_function=f,
                layer=(1, 0),
                port_names=("o1", "o2"),
            )
        ],
        radius=radius,
    )

    n_points = abs(int(45 / 360 * radius / 0.01))
    t = np.linspace(0, np.deg2rad(45) / 2, n_points)
    x1 = radius * np.cos(t)
    y1 = radius * np.sin(t)

    p1 = gf.Path(path=np.array([x1, y1]).T)
    return gf.path.extrude(p1, cross_section=cross_section2, all_angle=True)


my_cell().show()
```

![image](https://github.com/user-attachments/assets/478a9bfc-68fb-46a9-950e-4073d961c70d)

**Comment by lodoreds** [comment]
Thanks! Yes, this works, but this is equivalent to decorating `path.extrude`  with vcell.
This however does not solve the issue of placing multiple extruded paths into one cell without having wrapped them in a decorated function beforehand, nor does it help if I just want to place it without a function, which should be a legitimate syntax to prevent excessive nesting (correct me if I am wrong).
After all, if I had to make a decorated function for every extruded path my code would get verbose and at that point decorating the `extrude` method seems like a reasonable idea to me.
Let me know what you think!

**Comment by sebastian-goeldi** [comment]
That's what kfactory is doing for most of the functions in fact.

There are multiple  good ways of handling this:

- give `path.extrude` an optional Component as an input (this woulf require a PR)
- decorate path.extrude yourself. This is as easy as `decorated_path = gf.vcell(
gf.path.extrude)` and then you do `c=decorated_path(**path_kwargs)`

**Comment by lodoreds** [comment]
Great, thanks, that's what I was referring to, sorry for the confusion! I went for the latter, see my PR.

**Comment by sebastian-goeldi** [comment]
Yes, but I disagree. If you go for that option, you take away the opportunity to modify the path component. I think it's bad to only offer the decorated path, hence why the decorator was removed in the first place.

**Comment by lodoreds** [comment]
I see, but why would you want to modify an extruded path a posteriori? It's very flexible and it has its own purpose, so it would be like not decorating a straight because you may want to modify it afterwards.

**Comment by sebastian-goeldi** [comment]
Because if I want an extruded path, I definitely either want it in another cell, or I don't want it named "path_.." if it's a bend or similar.

**Comment by lodoreds** [comment]
An extruded path can be more than a bend (and any other standard component) though. Note that in my case the component is not a strictly bend, even if it looks like it, and I do not want it to be treated as such, otherwise I would have just used a normal bend with a special cross-section. I am using a path because I want to set the equation of the spline, and not because I need to go from point A to B with a component like a bend. If you want to have a standard component with a specific width profile (e.g.: tapered 90 deg bend), you can use the bend component with a tapered cross-section. 
Furthermore, decorating the extrude is precisely allowing you to place any number of paths in another component without the errors that we are getting now.

**Comment by sebastian-goeldi** [comment]
yes, so I fail to see what the big issue is if you have to declare once in your tapeout:

```python
path = gf.vcell(gf.path)
```

And all of this is completely ignoring that path can give you an all-angle component or a standard component/cell. There currently is not a decorator to do that automatically, nor do I know whether that's easy to implement

**Comment by joamatab** [comment]
Closing this for now

Feel free to reach out if there’s anything else we can assist with.
