### ISSUE TITLE
how to convert cells to static?

### ISSUE THREAD

**Issue by SkyLin1020** [gdsfactory/gdsfactory#3066]
how to convert cells to static like kalyout do below?
![image](https://github.com/user-attachments/assets/ed679e55-1cc3-4719-8091-1f2630e1aaf9)

**Comment by sebastian-goeldi** [comment]
Unless you are using kfactory directly, this is already the case. Gdsfactory current does not creat KLayout PCells.

**Comment by sebastian-goeldi** [comment]
Unless you are using kfactory directly, this is already the case. Gdsfactory current does not creat KLayout PCells.

**Comment by SkyLin1020** [comment]
@sebastian-goeldi, thanks.
