### ISSUE TITLE
The "layer" in "cross_section" cannot be set to "None"

### ISSUE THREAD

**Issue by lemonc7** [gdsfactory/gdsfactory#3084]
**Describe the bug**
When I set "layer=None", it doesn't work. In the previous version, it works.

**To Reproduce**
import gdsfactory as gf

c = gf.Component('demo')
cs = gf.cross_section.cross_section(width=1.2,cladding_offsets=(0,3),cladding_layers=((1,0),(2,0)),layer=None)
wg = c << gf.components.straight(cross_section=cs)
c.show()

**Expected behavior**
I need to generate a wavegude including a core(width=1.2, layer=(1,0)) and a cladding(width=7.2(1.2+3+3), layer=(2,0)). If the layer in cross_section is not None, the code will generate two same cores(width=1.2, layer=(1,0) and a cladding.

**Suggested fix**
How could we fix the bug?

**Comment by joamatab** [comment]
Hi, 

i don't think this is a bug

what i think you're trying to do is this

```python
import gdsfactory as gf

c = gf.Component("demo")
cs = gf.cross_section.cross_section(
    width=1.2, cladding_offsets=(3,), cladding_layers=((2, 0),), layer=(1, 0)
)
wg = c << gf.components.straight(cross_section=cs)
c.show()
```
