### ISSUE TITLE
Typo in Doc of Lumerical-plugin

### ISSUE THREAD

**Issue by Jan-David-Black** [gdsfactory/gdsfactory#309]
[here](https://gdsfactory.github.io/gdsfactory/notebooks/plugins/lumerical/1_fdtd_sparameters.html) it says 
``` python
session = luampi.FDTD()
```
instead of 
``` python
session = lumapi.FDTD()
```

**Comment by joamatab** [comment]
Awesome, great find @Jan-David-Black
