### ISSUE TITLE
Is klayout_pyxs still supported?

### ISSUE THREAD

**Issue by m-mcgivney** [gdsfactory/gdsfactory#3109]
Is klayout_pyxs still supported?  I am trying to use klayout_pyxs (for the first time) and I have Klayout v0.29.4.

I installed klayout_pyxs using "pip install klayout_pyxs" and installed the package in KLayout using the Salt Package Manager, but no "pyxs" option has appeared in the KLayout -> Tools dropdown menu as I was led to expect based on this page:  https://gdsfactory.github.io/klayout_pyxs/

Can someone please confirm if klayout_pyxs is still supported, and whether I missed a step in the installation process?

**Comment by joamatab** [comment]
Hi, 

i think some of the latest klayout updates broke the package

![image](https://github.com/user-attachments/assets/ae701455-e09a-4914-be5e-60f02f47a612)

Feel free to send a PR if you find the fix
https://github.com/gdsfactory/klayout_pyxs/


@dimapu
@klayoutmatthias
@sebastian-goeldi

**Comment by m-mcgivney** [comment]
Got it, thanks!

**Comment by sebastian-goeldi** [comment]
I think this might be related to the implicit conversions of Polygon, e.g. if you pass it the constructor to a Box or list of points etc.

**Comment by klayoutmatthias** [comment]
How can I reproduce the problem?

**Comment by joamatab** [comment]
- you can follow the intructions [here](https://gdsfactory.github.io/gdsfactory/notebooks/03_layer_stack.html#klayout-cross-section)

**Comment by joamatab** [comment]
I removed the klayout_pyxs from the recommended plugins until we fix it

**Comment by joamatab** [comment]
i moved the issue [here](https://github.com/gdsfactory/klayout_pyxs/issues/11) as this is more of a klayout issue
