### ISSUE TITLE
Missing f for f-string

### ISSUE THREAD

**Issue by Jan-David-Black** [gdsfactory/gdsfactory#311]
This [line](https://github.com/gdsfactory/gdsfactory/blob/1ba069779f39a6e8183b395a1771041bd068f406/gdsfactory/simulation/lumerical/write_sparameters_lumerical.py#L154) is missing the f in front of the f-string (not a major deal!)
Regards JD

**Comment by joamatab** [comment]
thanks @Jan-David-Black !

fixed in https://github.com/gdsfactory/gdsfactory/pull/312
