### ISSUE TITLE
EOFError: EOF when reading a line

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#3110]
sometimes when testing GDS regression files we get `EOFError: EOF when reading a line`

@sebastian-goeldi

**Comment by sebastian-goeldi** [comment]
This is most likely related to gigantic metainfos and should be fixed in klayout >=0.29.5

See https://github.com/KLayout/klayout/issues/1794

**Comment by joamatab** [comment]
Im still seeing that with klayout==0.29.5
