### ISSUE TITLE
bbox_layers in the bend_circular of Pcells dosen't work

### ISSUE THREAD

**Issue by JinchW** [gdsfactory/gdsfactory#3123]
**Describe the bug**
The `bbox_layers` and `bbox_offsets` parameter in `gf.cross_section.cross_section` is invalid for component `bend_circular`.
However, the bug does not exist in `bend_euler`, `bend_s` and `bend_euler_s`.
**To Reproduce**
```
import gdsfactory as gf
from functools import partial

c = gf.Component()
bend_xs = partial(gf.cross_section.cross_section,
                  bbox_layers = [(2,0)],
                  bbox_offsets = [0])
bend = c << gf.components.bend_circular(angle=90, 
                                        cross_section=bend_xs, 
                                        allow_min_radius_violation=False)
# bend = c << gf.components.bend_euler(angle=90, 
#                                      p=0.5, 
#                                      with_arc_floorplan=True, 
#                                      cross_section=bend_xs, 
#                                      allow_min_radius_violation=False)
# bend = c << gf.components.bend_s(size=(11, 1.8), 
#                                  npoints=99, 
#                                  cross_section=bend_xs, 
#                                  allow_min_radius_violation=False)
c.show()
c.write_gds("test.gds")
```

**Expected behavior**
![image](https://github.com/user-attachments/assets/2fabac43-9a53-40d0-abbe-658a5d127dd0)
![image](https://github.com/user-attachments/assets/3df5cdab-ee03-4759-bb7c-7723d8ea0024)
![image](https://github.com/user-attachments/assets/4ed859fe-bd0f-43ea-8b93-b03f66e44139)

**Suggested fix**
I checked the source code, maybe the following code should add to `bend_circular`, but I am not sure.
```
top = None if int(angle) in {180, -180, -90} else 0
bottom = 0 if int(angle) in {-90} else None
x.add_bbox(c, top=top, bottom=bottom) 
```

**Comment by joamatab** [comment]
Thanks @JinchW for reporting this and for the suggested fix!

See fix [here](https://github.com/gdsfactory/gdsfactory/pull/3124)
