### ISSUE TITLE
Settings for imported gds cells without metadata file

### ISSUE THREAD

**Issue by thomasdorch** [gdsfactory/gdsfactory#315]
Currently, import_gds only adds Settings to imported cells if there is a metadata file available. Because of this, the cells generated this way cause an exception when get_netlist is called. It would be nice to have a way to add Settings to these cells without having to call the cell decorator.

**Comment by joamatab** [comment]
Hi Thomas,

can you use info?

![image](https://user-images.githubusercontent.com/4514346/165833846-3a3aae36-716b-4392-97c3-8f55c3fdf926.png)

**Comment by thomasdorch** [comment]
Yes, info works for what I'm doing. The issue is that get_netlist doesn't copy over the info and throws an error if the component's settings dict is empty. 

PR #316 fixes this

**Comment by joamatab** [comment]
Awesome! thank you Thomas

i merged and released 5.3.4

https://github.com/gdsfactory/gdsfactory/pull/320
