### ISSUE TITLE
RuntimeError: Cannot write layer numbers larger than 65535 to GDS2 streams

### ISSUE THREAD

**Issue by dboriska** [gdsfactory/gdsfactory#3157]
**Describe the bug**

The write_gds function doesn't work.
Simple  code 
`import gdsfactory as gf`
`c = gf.components.grating_coupler_loss_fiber_array4(pitch=127)`
`c.show()`
gives the error
**RuntimeError: Cannot write layer numbers larger than 65535 to GDS2 streams,**

**Environment**
Fresh installation of Anaconda on Win10
>>> print(sys.version)
**3.12.3** | packaged by conda-forge | (main, Apr 15 2024, 18:20:11) [MSC v.1938 64 bit (AMD64)]

![e1](https://github.com/user-attachments/assets/6127fb89-b100-4dc3-8da1-e30be5f62345)

**Comment by joamatab** [comment]
Hi,

can you run `pip install gdsfactory --upgrade` and try again?

**Comment by dboriska** [comment]
problem solved after the upgrade
