### ISSUE TITLE
The get_ports_list() function does not work in the reference device.

### ISSUE THREAD

**Issue by LuYouxi** [gdsfactory/gdsfactory#3163]
The get_ports_list() function does not work in the reference device.

The duplicate code is as follows
```python

import gdsfactory as gf

test =gf.Component()

gc = gf.components.grating_coupler_te()
gc1 = test.add_ref(gc)

ports = gc1.get_ports_list()
```
The error message is as follows:
![image](https://github.com/user-attachments/assets/407702c9-9d2d-4dc8-b8a0-8d78760f0431)

**Environment:**
![image](https://github.com/user-attachments/assets/f041029e-b93a-47e5-b465-05949e394e19)

**Comment by joamatab** [comment]
i added some docs about this into the migration guide

![image](https://github.com/user-attachments/assets/8230971f-57a9-4ac2-b143-228d2634cd57)
