### ISSUE TITLE
The port doesn't seem to work

### ISSUE THREAD

**Issue by niubiworker** [gdsfactory/gdsfactory#3167]
**Describe the bug**
There seems to be an issue. I referenced your DBR (Distributed Bragg Reflector) example, but the final array structure's port position should be ((l1 + l2)*n). However, the actual result shows (l1 + l2) instead. I'm not sure where the problem lies. Thank you very much!

**To Reproduce**
"""DBR gratings.

wavelength = 2*period*neff
period = wavelength/2/neff

dbr default parameters are from Stephen Lin thesis
https://open.library.ubc.ca/cIRcle/collections/ubctheses/24/items/1.0388871

Period: 318nm, width: 500nm, dw: 20 ~ 120 nm.
"""
```
from __future__ import annotations
import gdsfactory as gf
from gdsfactory.component import Component
from gdsfactory.components.straight import straight
from gdsfactory.snap import snap_to_grid
from gdsfactory.typings import CrossSectionSpec
period = 318e-3
w0 = 0.5
dw = 100e-3
w1 = w0 - dw / 2
w2 = w0 + dw / 2
@gf.cell
def dbr_period(w1=0.5, w2=0.6, l1=0.2, l2=0.4, straight=gf.components.straight):
    """Return one DBR period."""
    c = gf.Component()
    r1 = c << straight(length=l1, width=w1)
    r2 = c << straight(length=l2, width=w2)
    r2.connect(port="o1", other=r1.ports["o2"], allow_width_mismatch=True)
    c.add_port("o1", port=r1.ports["o1"])
    c.add_port("o2", port=r2.ports["o2"])
    return c
l1 = 0.2
l2 = 0.4
n = 3
period = dbr_period(l1=l1, l2=l2)
period
dbr = gf.Component("DBR")
dbr.add_ref(period, columns=n, rows=1, spacing=(l1 + l2, 100))
dbr
p0 = dbr.add_port("o1", port=period.ports["o1"])
p1 = dbr.add_port("o2", port=period.ports["o2"])
p1.dcenter = [(l1 + l2) * n, 0]
#dbr.show()
dbr.pprint_ports()
```

**Expected behavior**
What would you like to happen?

**Suggested fix**
How could we fix the bug? As an open-source project, we welcome your suggestions and PRs.

**Environment (please complete the following information):**

- [ ] I have checked the documentation and found no answer
- [ ] I have checked the issues and found no answer
- [x] Im using the latest GDSFactory version and python 3.10, 3.11 or 3.12. Please copy below the output for this code:

```python 
python 3.11.8
gdsfactory 8.8.2
```

**Comment by sebastian-goeldi** [comment]
This should be fixed with the above linked PR. There was a small bug in gdsfactory's `add_port` where it would return the variable with the old port instead of the one created by kfactory. Should be fixed with the next release.
