### ISSUE TITLE
Pass list of the components or references to boolean function 

### ISSUE THREAD

**Issue by rviktor85** [gdsfactory/gdsfactory#3182]
In the previous version of GDSFactory (v7) there was a possibility to pass a list of Component/ComponentReference to a boolean function. It can be a very useful option to add it back to the newest release.

**Comment by joamatab** [comment]
Hi,

this is also true on GDSFactory8
```python
    c0 = gf.Component()
    core = c0 << gf.c.coupler()
    clad = c0 << gf.c.bbox(core, layer=(2, 0))
    clad.dmovex(5)
    c = boolean(clad, core, operation="not", layer=(3, 0), layer1=(2, 0), layer2=(1, 0))
    c.show()
```
