### ISSUE TITLE
Resolve Port Positions Recursively from a Top Component in V8

### ISSUE THREAD

**Issue by LIU-Yinyi** [gdsfactory/gdsfactory#3191]
Hi there,

Glad to see V8 has gained lots of advanced functions from passionate contributors and finally I decided to upgrade my framework based on `gdsfactory` from V7 to V8. During migration, I encountered some problems:

In V7, I could get port positions recursively from a hierarchical component like below:

```python
def get_ports(self, depth: int | None = None) -> list:
        """Return List of Port Information

        Args:
            depth: Port depth to be extracted. Larger value indicates more depth and includes results of inferior depth. None means all-depth extraction.
        """

        def _get_ports(c: gf.Component, d: int | None = None):
            port_list = [p.copy() for p in c.ports.values()]
            for i in range(len(port_list)):
                port_list[i].info['parent'] = []

            if d is None or d > 0:
                for r in c.references:
                    new_depth = None if d is None else d - 1
                    ref_ports = _get_ports(r.parent, new_depth)
                    ref_ports_transformed = []
                    for rp in ref_ports:
                        new_port = rp.copy()
                        new_center, new_orientation = r._transform_port(
                            rp.center,
                            rp.orientation,
                            r.origin,
                            r.rotation,
                            r.x_reflection,
                        )
                        new_port.center = new_center
                        new_port.new_orientation = new_orientation
                        new_port.info['parent'].append(r.name)
                        ref_ports_transformed.append(new_port)
                    port_list += ref_ports_transformed
            return port_list

        ports = _get_ports(self.canvas, depth)

        ports_list = []
        for p in ports:
                ports_list.append({
                    'name': p.name,
                    'center': p.center,
                    'orientation': p.orientation,
                    'parent': p.info['parent'][::-1],
                    'width': p.width,
                    'layer': p.layer,
                    'port_type': p.port_type,
                    'shear_angle': p.shear_angle
                })

        return ports_list
```

The positioning data, such as `center` and `orientation`, are relative to top component's coordinate.

In V8, not sure if I missed some important usage in the document, I cannot find effective alternatives to migrate `Component.references._transform_port()` function to new version that can work well.

## Expected Functions
- **Input**: a `gf.Component` as the top component.
- **Output**: a list of ports that contain the positioning and hierarchical dependency information relative to the top cell.
- **Related**: `get_ports_list` return nothing or ignore children's ports. 

Could anyone give some suggestions or guidance? Thanks!

**Comment by sebastian-goeldi** [comment]
hmm, I usually don't find these kinds of buried ports, but here goes.

```python
import gdsfactory as gf

c = gf.components.mzi()
c.show()

rec_inst_it = c.begin_instances_rec()
rec_inst_it._unmanage
ports: dict[tuple[gf.kdb.InstElement], list[gf.Port]] = {}

for it in rec_inst_it.each():
    _path = tuple(it.path() + [it.current_inst_element()])
    _ports = [
        p.copy(it.dtrans() * it.inst_dtrans())
        for p in gf.kcl[it.inst_cell().cell_index()].ports
    ]
    ports[_path] = _ports

print(ports)
```

The path are [InstElement](https://klayout.de/doc/code/class_InstElement.html) from KLayout. So, be aware they do not directly behave like Components/KCells. Nonetheless, they give you exact information about where and how the instances came to be.

**Comment by tvt173** [comment]
hi @LIU-Yinyi , in gdsfactory 8, Components are based off of Kfactory KCells. those in turn proxy Klayout Cells. so in principle, you can access any of the methods documented here:
https://www.klayout.de/doc-qt5/code/class_Cell.html

however, you should be somewhat careful when accessing the KLayout API directly. I would suggest only doing it for _reading_ attributes from objects, as you are here, but not to construct them

I agree that this could be better documented and it may make sense to promote some of these methods directly to the gdsfactory API

**Comment by sebastian-goeldi** [comment]
Yes, as Troy mentioned, the components (or rather its superclass in this case, KCell, in case of unknown attribute goes for a fishing tour in `KCell._kdb_cell`. It is better to go through this process of accessing the functions like this. Reason being, sometimes the KCell will overwrite functions of pure Cells in order to provide a more kfactory friendly type (e.g. in some cases kfactory classes are return which are superclasses of pure KLayout classses).

And yes, you are right, it's not mentioned in the docs, though kfactory mentions the `__getattr__` behavior https://gdsfactory.github.io/kfactory/reference/kfactory/kcell/#kfactory.kcell.KCell

Also, definitely can second Troy's words of caution. Read is definitely fine, write ops can mess up or break Components/KCells. E.g. if you were to delete Instances on the `_kdb_cell`, that would cause problems.
