### ISSUE TITLE
Colab examples on docs site no longer run after gf requiring python 3.11

### ISSUE THREAD

**Issue by paulxshen** [gdsfactory/gdsfactory#3192]
Colab stuck on Python 3.10 but gdsfactory now requires 3.11 . Maybe roll back compat entry to 3.10?

**Comment by joamatab** [comment]
Hi Paul,

This issue comes from Kfactory backend requiring python3.11 or larger

@sebastian-goeldi

**Comment by sebastian-goeldi** [comment]
Could you try instead whether it would be feasible to install 3.11/12 in colab and see whether that works?

https://www.askpython.com/python/examples/update-python-google-colab

**Comment by paulxshen** [comment]
Thanks Joaquin and Sebastian! I tried variations of it - need to restart session to apply updates but Colab then hangs :( could just wait/nudge on Colab to update to 3.11 lol

**Comment by sebastian-goeldi** [comment]
Sure you want to close this? All the scientific packages start to drop 3.10 support in 2 months :-)
