### ISSUE TITLE
How to Obtain the Rotation of a ComponentReference in V8

### ISSUE THREAD

**Issue by LIU-Yinyi** [gdsfactory/gdsfactory#3200]
## Problem 1: Rotation Retrieval
In V7, the rotation or orientation of a `ComponentReference` can be accessed directly through its attributes. 

```python
c = gf.Component()
ref = c.add_ref(gf.components.rectangle(size=(1,1), layer=(1,0)))
ref.move((2, 4))
ref.rotate(30)

print(ref.rotation)
```

While in V8, I notice that the transformation is kept in `dtrans` or `cplx_trans` object, which is based on `klayout.dbcore.DTrans`. According to its [document](https://www.klayout.de/doc-qt5/code/class_DTrans.html), the `angle` or `rot` indicates the integer multiples of 90 degree rather than floating-point arbitrary angles.  Here comes the problems:

```python
c = gf.Component()
ref = c.add_ref(gf.components.rectangle(size=(1,1), layer=(1,0)))
ref.dmove((2, 4))
ref.drotate(30)

print(ref.dtrans)
```

The output of `dtrans` is `r0 -0.268,4.464`, which can not reflect the real rotation. I understand that they are somehow equivalent through transformation, but this implicitness troubles me a lot. Is there any way to extract the orientation data from `dtrans` or other related attributes? Additionally, it seems that `origin` property is also removed from V8.

## Problem 2: Route Decoupling from Main Component
In V7, routing methods generate a decoupled `Route` object and require manually appending to main component. While in V8, route functions directly complete both steps. Since my EDA framework targeted on layout optimization may need erase-and-reroute operations, a separated route is expected. I have tried the codes like below:

```python
c = gf.Component()
mmi1 = c << gf.components.mmi1x2()
mmi2 = c << gf.components.mmi1x2()
mmi2.dmove((100, 50))

# another component for placing routes separately
cr = gf.Component()
route = gf.routing.route_single(cr, port1=mmi1.ports["o2"], port2=mmi2.ports["o1"])
print(route)
```

It works, but not completely. The netlist seems NOT updated in the main component `c`.

```python
ref_route = c.add_ref(cr)

print(c.get_netlist()['nets'])   # return empty
print(cr.get_netlist()['nets'])  # return nets
```

How can I update the results of nets from `cr` to `c`?

Thanks.

**Comment by joamatab** [comment]
Here are the suggested solutions:

Problem 1: Extracting orientation data from dtrans in V8

There isn't a straightforward built-in method for extracting floating-point rotation data from dtrans. It may be necessary to manage these custom transformations manually.

```python
import gdsfactory as gf 
c = gf.Component()
ref = c.add_ref(gf.components.rectangle(size=(1,1), layer=(1,0)))
ref.dmove((2, 4))
ref.drotate(90)
rotation = ref.dtrans.angle*90
```


Problem 2: Decoupling Routes and Updating Netlist

Here is what i would do
```
import gdsfactory as gf 
c = gf.Component()
mmi1 = c << gf.components.mmi1x2()
mmi2 = c << gf.components.mmi1x2()
mmi2.dmove((100, 50))

route = gf.routing.route_single(c, port1=mmi1.ports["o2"], port2=mmi2.ports["o1"])
print(c.get_netlist()['nets'])
```

**Comment by sebastian-goeldi** [comment]
1. Component is for purely manhattan components (i.e. will be placed only with x * 90° rotation and always on-grid) ComponentAllAngle can have arbitrary rotations and positions. VKCell is just an emulation of what a KCell is for manhattan cells. It is pure python and only offers a fraction of what we can do in a KLayout cell, but it can handle 
2. You theoretically can. But there will be significant drawbacks: Only a very reduced set on geometrical operations (e.g. no booleans) and the operations are very likely to be considerably slower. On top of that you might end up with a 100 cells that each only have one reference in the layout vs 1 cell with 100 references.
3. `add_ref` is the gdsfactory way of handling references, `create_inst` is a wrapper from kfactory for `c.insert(kdb.CellInstArray(ref_cell))` which is the KLayout way of creating a ref. `create_vinst` will force the creation of a a VInstance. A VInstance can refer to a real KCell or a VKCell. This allows to place "real" cells in an off-grid way (rotation wise and position wise)
