### ISSUE TITLE
Bug: error in `gf.components.text_rectangular`

### ISSUE THREAD

**Issue by AlphonseZetta10** [gdsfactory/gdsfactory#3218]
**Describe the bug**

```
File "***\.pixi\envs\default\Lib\site-packages\gdsfactory\components\text_rectangular.py", line 74, in text_rectangular
ref.dmove(origin=ref.dcenter, other=position, axis="x")
│   │            │   │              └ (0, 40)
│   │            │   └ <property object at 0x0000028972A9D620>
│   │            └ Unnamed_16: ports [], Unnamed_12: ports [], 0 instances
│   └ <function Instance.dmove at 0x0000028972AA1940>
└ Unnamed_16: ports [], Unnamed_12: ports [], 0 instances

TypeError: Instance.dmove() got an unexpected keyword argument 'other'
```

**To Reproduce**
```
c= gf.Component()
text0 = c << gf.components.text_rectangular(text="100", size=10, position=(0, 40) , justify='center', layer=(100, 0))
c.plot()
```

**Expected behavior**
What would you like to happen?
generate a text_rectangular cell

**Suggested fix**
How could we fix the bug? As an open-source project, we welcome your suggestions and PRs.
I think there some thing wrong about how to move the cell

**Environment (please complete the following information):**

- [*] I have reviewed the documentation but found no relevant solution.
- [*] I have searched the existing issues and found no resolution.
- [*] I am using the latest version of GDSFactory with Python 3.12. Below is the output for the following code
- [*] I acknowledge that, as an open-source project, the maintainers may not have the capacity to address this issue. I am willing to contribute by fixing it myself or hiring someone to resolve it (contact@gdsfactory.com). Otherwise, I understand that the issue may remain unresolved.

```python
import sys
print(sys.version)
print(sys.executable)

import gdsfactory as gf
gf.config.print_version_plugins()
```
```
3.12.6 | packaged by conda-forge | (main, Sep 22 2024, 14:01:26) [MSC v.1941 64 bit (AMD64)]
p:\OneDrive\***\devENV-GdsFactory\.pixi\envs\default\python.exe

```
<pre style="white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace"><span style="font-style: italic">                                                      Modules                                                      </span>
┏━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃<span style="font-weight: bold">    Package </span>┃<span style="font-weight: bold"> version                                          </span>┃<span style="font-weight: bold">                                            Path </span>┃
┡━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│<span style="color: #008080; text-decoration-color: #008080">     python </span>│<span style="color: #800080; text-decoration-color: #800080"> 3.12.6 | packaged by conda-forge | (main, Sep 22 </span>│<span style="color: #008000; text-decoration-color: #008000"> p:\OneDrive\***\devENV-GdsFactory\.pi… </span>│
│<span style="color: #008080; text-decoration-color: #008080">            </span>│<span style="color: #800080; text-decoration-color: #800080"> 2024, 14:01:26) [MSC v.1941 64 bit (AMD64)]      </span>│<span style="color: #008000; text-decoration-color: #008000">                                                 </span>│
│<span style="color: #008080; text-decoration-color: #008080"> gdsfactory </span>│<span style="color: #800080; text-decoration-color: #800080"> 8.8.8                                            </span>│<span style="color: #008000; text-decoration-color: #008000"> p:\OneDrive\***\devENV-GdsFactory\.pi… </span>│
│<span style="color: #008080; text-decoration-color: #008080">   gplugins </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                    </span>│<span style="color: #008000; text-decoration-color: #008000">                                                 </span>│
│<span style="color: #008080; text-decoration-color: #008080">        ray </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                    </span>│<span style="color: #008000; text-decoration-color: #008000">                                                 </span>│
│<span style="color: #008080; text-decoration-color: #008080">    femwell </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                    </span>│<span style="color: #008000; text-decoration-color: #008000">                                                 </span>│
│<span style="color: #008080; text-decoration-color: #008080">     devsim </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                    </span>│<span style="color: #008000; text-decoration-color: #008000">                                                 </span>│
│<span style="color: #008080; text-decoration-color: #008080">     tidy3d </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                    </span>│<span style="color: #008000; text-decoration-color: #008000">                                                 </span>│
│<span style="color: #008080; text-decoration-color: #008080">       meep </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                    </span>│<span style="color: #008000; text-decoration-color: #008000">                                                 </span>│
│<span style="color: #008080; text-decoration-color: #008080">       meow </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                    </span>│<span style="color: #008000; text-decoration-color: #008000">                                                 </span>│
│<span style="color: #008080; text-decoration-color: #008080">     lumapi </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                    </span>│<span style="color: #008000; text-decoration-color: #008000">                                                 </span>│
│<span style="color: #008080; text-decoration-color: #008080">        sax </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                    </span>│<span style="color: #008000; text-decoration-color: #008000">                                                 </span>│
└────────────┴──────────────────────────────────────────────────┴─────────────────────────────────────────────────┘
</pre>

**Comment by joamatab** [comment]
Thank you for reporting this

see fix https://github.com/gdsfactory/gdsfactory/pull/3388
