### ISSUE TITLE
route_single should error for width mismatch

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#3220]
This code should raise an error

```python
import gdsfactory as gf

c = gf.Component()
s1 = c << gf.c.straight(width=2)
s2 = c << gf.c.straight(width=2)

s2.dmove((20, 20))

gf.routing.route_single(
    component=c,
    port1=s1.ports["o1"],
    port2=s2.ports["o1"],
)

c.show()
```

and it doesn't 

![image](https://github.com/user-attachments/assets/dffb874b-5ff0-40cd-946e-121b0f0e3d88)

@sebastian-goeldi

**Comment by joamatab** [comment]
this PR should fix it by adding automatic tapers

https://github.com/gdsfactory/gdsfactory/pull/3222

**Comment by sebastian-goeldi** [comment]
Sure. I mean in the end I think it's fine however it's solved. connectivity check should find this as well

**Comment by joamatab** [comment]
this is how it looks after PR

![image](https://github.com/user-attachments/assets/4aa6d02b-6a5d-432e-a8e6-746f9bd81bd7)
