### ISSUE TITLE
avoid collisions

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#3227]
when using kfactory==0.20.5

![image](https://github.com/user-attachments/assets/860f9670-ccdd-44ea-a8a2-d5e9f7ead5c8)

avoiding colisions worked

however in latest kfactory==0.20.6 it doesn't

![image](https://github.com/user-attachments/assets/ea4fa665-2d49-4aa4-8551-e98520602641)

@sebastian-goeldi

**Comment by joamatab** [comment]
i can confirm this issue is coming from autotaper

When i use `auto_taper=False` i get:

![image](https://github.com/user-attachments/assets/e841753a-dd92-4925-9d3c-e87af7897390)

**Comment by joamatab** [comment]
this feature will be in implemented in kfactory

**Comment by sebastian-goeldi** [comment]
Yeah, but it's going to take time :D.

What you can do in the meantime is add
```python
box = gf.kdb.Box()
for taper in auto_tapers:
    box += auto_taper.ports["o1"].trans.disp.to_p()
    box += auto_taper.ports["o2"].trans.disp.to_p()
# call to route_bundle function with bboces = other_boxes + [box]
```
