### ISSUE TITLE
auto_rename_ports not working well

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#3247]
Autorename ports does not autorename all ports

```python

    from gdsfactory.samples.big_device import big_device

    c = big_device(nports=2)
    c = add_fiber_single(c)
    c.pprint_ports()
    c.show()


```

![image](https://github.com/user-attachments/assets/ee892e23-4c93-4f6a-aad8-9e0b2de8aec7)

@sebastian-goeldi

**Comment by sebastian-goeldi** [comment]
Correct. Because jt has a different port_type. Autorename only renames optical and electrical

**Comment by joamatab** [comment]
they are both port_type vertical dc

**Comment by sebastian-goeldi** [comment]
And since when is `"optical" == "vertical_te" `?
