### ISSUE TITLE
Unable to import tidy3d mode solver plugin (No module named 'kfactory.routing.generic')

### ISSUE THREAD

**Issue by achuify** [gdsfactory/gdsfactory#3265]
**Describe the bug**
When trying to import tidy3d mode solver plugin for gdsfactory, import statement throws an error due to importing a method from "kfactory.routing.generic" which the code is unable to find.

**To Reproduce**
![image](https://github.com/user-attachments/assets/987ef533-1cd8-4fbf-b143-fe089f21fd2d)

**Expected behavior**
to be able to import gplugins.tidy3d

**Environment (please complete the following information):**

- [X] I have reviewed the documentation but found no relevant solution.
- [X] I have searched the existing issues and found no resolution.
- [X] I am using the latest version of GDSFactory with Python 3.10, 3.11, or 3.12. Below is the output for the following code
- [X] I acknowledge that, as an open-source project, the maintainers may not have the capacity to address this issue. I am willing to contribute by fixing it myself or hiring someone to resolve it (contact@gdsfactory.com). Otherwise, I understand that the issue may remain unresolved.

```python
import sys
print(sys.version)
print(sys.executable)

import gdsfactory as gf
gf.config.print_version_plugins()
```

**Comment by joamatab** [comment]
python3.10 is no longer supported

you need to upgrade to 3.11 or 3.12
