### ISSUE TITLE
Add "layer_slab" and "slab_offset" parameters to the grating_coupler_elliptical_trenches pcell

### ISSUE THREAD

**Issue by LuYouxi** [gdsfactory/gdsfactory#3271]
I find that the grating_coupler_elliptical_trenches pcell in gf8 does not have "layer_slab" and "slab_offset" parameters, and suggest adding this parameter. The reason is that the grating_coupler_elliptical_trenches function in gf7 can respond to cladding layer section, but it is impossible to add cladding in gf8.

gf8 grating_coupler_elliptical_trenches:
![image](https://github.com/user-attachments/assets/99ab4991-932f-4e32-b659-54f5ae134008)

gf7 grating_coupler_elliptical_trenches:
![image](https://github.com/user-attachments/assets/09081210-4cf5-4c16-93fc-ca0c9e7a393f)

**Comment by joamatab** [comment]
Thank you for pointing this out,

see fix [here](https://github.com/gdsfactory/gdsfactory/compare/fix_gc_trenches?expand=1)

this allows you to use this function with trenches

![image](https://github.com/user-attachments/assets/cc38d8f6-0375-4dd1-9d63-81da450bb445)
