### ISSUE TITLE
gf.grid tries to add_ports to returned 'NoneType' from kf.grid when the number of components are less than the shape

### ISSUE THREAD

**Issue by tgustafson-ntnu** [gdsfactory/gdsfactory#3290]
**Describe the bug**
`gf.grid` iterate over all instances returned by `kf.grid` and `add_ports`, but if the components list is less than the shape, `kf.grid` returns a `NoneType` that cannot be assigned a port.

`AttributeError: 'NoneType' object has no attribute 'ports'`

**To Reproduce**
```python
import gdsfactory as gf

@gf.cell
def swatch(index)-> gf.typings.Component:
    _ = gf.components.rectangle(size = (1,1), layer = (index+1,0))
    return _

#components intentionally less than shape
swatches = [swatch(index) for index in range(11)]

@gf.cell
def component_grid(rows: int, columns: int) -> gf.typings.Component:
    
    g = gf.grid(
        components=swatches,
        spacing=(1, 1),
        shape=(rows, columns),
        align_x="x",
        align_y="y")
    return g

c = component_grid(rows=3,columns=4)
```

**Expected behavior**
Return a grid of assigned grid size, with the prescribed number of components. Since `kf.grid` can create the grid, I assume that adding ports is not meant to force the grid to be filled.

**Suggested fix**
I would imagine testing for `not None`?
```python
c = gf.Component()
instances = kf.grid(```stuff``` )
for i, instances_list in enumerate(instances):
  for j, instance in enumerate(instances_list):
     ```
      if instances_list is not None and instance is not None:
      ```
          c.add_ports(instance.ports, prefix=f"{j}_{i}_")
```

**Environment (please complete the following information):**

- [x] I have reviewed the documentation but found no relevant solution.
- [x] I have searched the existing issues and found no resolution.
- [x] I acknowledge that, as an open-source project, the maintainers may not have the capacity to address this issue. I am willing to contribute by fixing it myself or hiring someone to resolve it (contact@gdsfactory.com). Otherwise, I understand that the issue may remain unresolved.
- [x] I am using the latest version of GDSFactory with Python 3.11, or 3.12. Below is the output for the following code

```python
python │ 3.12.6 (tags/v3.12.6:a4a2d2b, Sep  6 2024, 20:11:23) [MSC v.1940 64 bit (AMD64)]          
gdsfactory │ 8.14.0                                          
gplugins, ray, femwell, devsim, tidy3d, meep, meow, lumapi, sax │ not installed 
```

**Comment by joamatab** [comment]
thank you for reporting this and for the suggested fix

I can release a patch with this
