### ISSUE TITLE
`c.plot( )` or `scene.show()` do not work in .py files

### ISSUE THREAD

**Issue by cheng1214** [gdsfactory/gdsfactory#3331]
Hi! @joamatab  @sebastian-goeldi 

I wondred if either `c.plot( )` or `scene.show()` only work in  .ipynb, but not in .py files?

In my case, when using `c.plot( )` in a .py file, no figure is popped up, while using `scene.show()` in a .py file,  an error "ModuleNotFoundError: No module named 'pyglet'" was raised. `c.show()` however works normally.

All of them however works well in .ipynb files...

Another question, I would like to ask, would be why gdsfacotory is automatically downgraded to 8.8.9 after I installed ubcpdk?

**Comment by sebastian-goeldi** [comment]
Because ipynb/ipython do some magic behind the scenes. But I believe you can force it to show a figure in normal python with `return_fig=True` as an argumen.

ubc downgrades because here it has a specific version requirement for gdsfactory  https://github.com/gdsfactory/ubc/blob/main/pyproject.toml#L18

**Comment by cheng1214** [comment]
Thanks the reply. 
But `c.plot(return_fig=True)` still doesn't work and no figure popped up

**Comment by sebastian-goeldi** [comment]
Yes it returns a matplotlib figure in that case, the showing must be handled by you as far as I can tell. Not an expert though, I never use this

**Comment by Neuromystix** [comment]
I had the same issue on Spyder (Anaconda installation), which uses Ipython. If i run the full code with `F5`, containing some `c.plot(return_fig=True)`, the plot is ignored by Spyder. If then I run just the `c.plot(return_fig=True)` line with `F9`, it is plotted ok to _inline_. I assumed something behind the Ipython backend or whatever.  

I ended up using just `c.show()`.
