### ISSUE TITLE
Failed to exclude ports when adding and routing grating couplers

### ISSUE THREAD

**Issue by cheng1214** [gdsfactory/gdsfactory#3334]
Hi!
@joamatab @sebastian-goeldi 

It found that I couldn't exclude any ports using 'excluded_ports' parameter in 'gf.routing.add_fiber_array()' method.

For example, when I ran code below to exclude 'o1' ports in the routing, it raised an error "_ValueError: ports1=4 and ports2=2 must be equal_"

```
import gdsfactory as gf
c = gf.components.crossing()
cc = gf.routing.add_fiber_array(
    component=c,
    grating_coupler=gf.components.grating_coupler_elliptical_te,
    with_loopback=False,
    excluded_ports = [('o1')]
)
cc.plot()
```

Then it raises an error below
![image](https://github.com/user-attachments/assets/a34e4ae1-3d4a-4be8-bada-ba8ec2563b2f)

You help would be greatly apprecaited!

**Comment by cheng1214** [comment]
I just wondered if anyone had an idea how that could be fixed?

**Comment by sebastian-goeldi** [comment]
The error you are getting is because something is trying to route or place 4 ports on one side and 2 ports on the other. But I only know that it comes from the routing function or add fiber array function from gdsfactory and I am not familiar with those.

**Comment by joamatab** [comment]
Hi Cheng,

thank you for reporting this

See fix
https://github.com/gdsfactory/gdsfactory/pull/3355

after the fix it works well

![image](https://github.com/user-attachments/assets/b04d8018-3c59-4bb4-b7d1-9f26dd4a9f02)
