### ISSUE TITLE
Trying to generate multiple ring crows generates a cell name issue. 

### ISSUE THREAD

**Issue by Ceboc** [gdsfactory/gdsfactory#3345]
Trying to generate multiple rings with the function gf.components.ring_crow I got this error:
```python
ValueError: Cellname ring0 already exists. Please make sure the cellname is unique or pass `allow_duplicate` when creating the library
```
This was my script (it contains just dummy values):

```python
import gdsfactory as gf
import numpy as np

gaps_l = np.linspace(0.1,0.5,5)
radii_l = np.linspace(10,20,5)

@gf.cell
def test_rings(radius = 10.0,gap=0.2):
    c=gf.Component()
    ring = c << gf.components.ring_crow(radius=(radius,),gaps=(gap,gap))
    c.add_ports(ring.ports)
    c.auto_rename_ports()
    return c

test = test_rings()
test.show()

components_list = []

for radius in radii_l:
    for gap in gaps_l:
        D = test_rings(radius=radius,gap=gap)
        components_list.append(D)


c = gf.grid(
    tuple(components_list),
    spacing = (15,15),
    shape = (len(radii_l), len(gaps_l)),
    align_x = "x",
    align_y = "y"
)

c.show()
```
I found that this can be solved if the name of the rings is not hard coded as in the source code. I changed line 90 of the function definition from in my PC:
https://github.com/gdsfactory/gdsfactory/blob/cb43f5b1fa380d07577be60c29a2ade6fd7dcff3/gdsfactory/components/ring_crow.py#L90

to :
```python
ring = Component()
```

I'm using gdsfactory==8.17.0 and Python==3.12.0

**Comment by joamatab** [comment]
Thank you for reporting this

See fix here https://github.com/gdsfactory/gdsfactory/pull/3349
