### ISSUE TITLE
improve graphviz

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#3350]
- [x] use corner arrows instead of straight arrows  fixed by https://github.com/gdsfactory/gdsfactory/pull/3354
- [x] fix ortho to connect to correct ports

@Jelly298

**Comment by joamatab** [comment]
using splines 'ortho' i got it working but the edges don't connect to the ports

https://github.com/gdsfactory/gdsfactory/pull/3351

![image](https://github.com/user-attachments/assets/5a6f4109-c2fb-4ab7-a387-24ad336570bf)

**Comment by Jelly298** [comment]
I've reproduced the issue. Also found a similar issue here. 

https://stackoverflow.com/questions/75953069/graphviz-edges-with-ortho-lines-not-aligning-with-ports

Working on the fix

**Comment by joamatab** [comment]
Awesome, the new schematics look beautiful thanks to your PR, [see](https://gdsfactory.github.io/gdsfactory/notebooks/10_schematic.html)
