### ISSUE TITLE
cross_section slab width not adjusted on routes calls (_bend_euler)

### ISSUE THREAD

**Issue by jakubsadilek** [gdsfactory/gdsfactory#3368]
When the cross_section is specified with an internal functional behaviour (e.g. slab is function of width) the some functions does not interpret the width argument correctly. 

**To Reproduce**

Used Xsection:
```
@xsection
def ribY(
    width: float = 0.75,
    layer: LayerSpec = DLAYER,
    layer_slab: LayerSpec = WLAYER,
    radius: float = MINRAD,
    radius_min: float = MINRAD,
    width_slab: float = 6,
    **kwargs,
) -> CrossSection:
    """Return Rib cross_section."""
    sections = (
        Section(width=width_slab+width, layer=layer_slab, name="slab", simplify=50 * nm),
    )
    return gf.cross_section.cross_section(
        width=width,
        layer=layer,
        radius=radius,
        radius_min=radius_min,
        sections=sections,
        **kwargs,
    )
```

![_bend_euler_width1](https://github.com/user-attachments/assets/bb539c97-afe9-4f83-a15b-65e5b9a91f91)
![_bend_euler_width2](https://github.com/user-attachments/assets/991daf95-24f7-491c-8cc0-383328483d25)

**Expected behavior**
The width argument should be passed to every following function (in this case the _bend_euler function ) 

**Suggested fix**
Now, I am patching it by extending row 60 of _bend_euler.py 
`x = gf.get_cross_section(cross_section)
`
by 
```
    if width != None:
        x = gf.get_cross_section(cross_section, width = width)
    else:
        x = gf.get_cross_section(cross_section)
        
```

**Environment (please complete the following information):**
python > 3.12.4
gdsfactory > 8.18.1
gplugins > 1.1.2

**Comment by joamatab** [comment]
Thank you @jakubsadilek  for reporting this and for the suggested fix

See fixes [here](https://github.com/gdsfactory/gdsfactory/compare/fix_bend_width?expand=1)
