### ISSUE TITLE
route_bundle throws error in gf.read.from_yaml

### ISSUE THREAD

**Issue by kuangfio** [gdsfactory/gdsfactory#3382]
**Describe the bug**
route_bundle throws a value error when gf.read.from_yaml is run

gdsfactory\routing\route_bundle.py", line 184, in route_bundle
    raise ValueError(
ValueError: Either cross_section=None or layer=None and route_width=None must be provided

**To Reproduce**
From the 10_yaml_component.ipynb notebook:

```python
import gdsfactory as gf
from IPython.display import Code
filepath = "yaml_pics/pads.pic.yml"
Code(filepath, language="yaml+jinja")
c = gf.read.from_yaml(filepath)
c
```

ValueError: Either cross_section=None or layer=None and route_width=None must be provided

**Expected behavior**
The component should be able to be read from the yaml file.

**Suggested fix**
Can gf.read.from_yaml be changed so that it passes a default value to cross_section or layer and route_width to route_bundle?

**Environment (please complete the following information):**

- [X] I have reviewed the documentation, discussions and issues and found no relevant solution.
- [X] I understand that this is an open-source project, and maintainers may not have the resources to address every issue. I am prepared to contribute by fixing the issue myself or hiring someone to do so, if needed, and accept that the issue may not be resolved otherwise.
- [X] I am using the latest version of GDSFactory, with Python 3.10, 3.11, or 3.12.

Please provide the output for the following code:

```python
import sys
print(sys.version)
print(sys.executable)

import gdsfactory as gf
gf.config.print_version_plugins()
```
<pre style="white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace"><span style="font-style: italic">                                                      Modules                                                      </span>
┏━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃<span style="font-weight: bold">    Package </span>┃<span style="font-weight: bold"> version                                          </span>┃<span style="font-weight: bold">                                            Path </span>┃
┡━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│<span style="color: #008080; text-decoration-color: #008080">     python </span>│<span style="color: #800080; text-decoration-color: #800080"> 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024,       </span>│<span style="color: #008000; text-decoration-color: #008000"> C:\Users\kuang\AppData\Local\Microsoft\Windows… </span>│
│<span style="color: #008080; text-decoration-color: #008080">            </span>│<span style="color: #800080; text-decoration-color: #800080"> 10:12:12) [MSC v.1938 64 bit (AMD64)]            </span>│<span style="color: #008000; text-decoration-color: #008000">                                                 </span>│
│<span style="color: #008080; text-decoration-color: #008080"> gdsfactory </span>│<span style="color: #800080; text-decoration-color: #800080"> 8.18.2                                           </span>│<span style="color: #008000; text-decoration-color: #008000"> C:\Users\kuang\AppData\Local\Packages\PythonSo… </span>│
│<span style="color: #008080; text-decoration-color: #008080">   gplugins </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                    </span>│<span style="color: #008000; text-decoration-color: #008000">                                                 </span>│
│<span style="color: #008080; text-decoration-color: #008080">        ray </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                    </span>│<span style="color: #008000; text-decoration-color: #008000">                                                 </span>│
│<span style="color: #008080; text-decoration-color: #008080">    femwell </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                    </span>│<span style="color: #008000; text-decoration-color: #008000">                                                 </span>│
│<span style="color: #008080; text-decoration-color: #008080">     devsim </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                    </span>│<span style="color: #008000; text-decoration-color: #008000">                                                 </span>│
│<span style="color: #008080; text-decoration-color: #008080">     tidy3d </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                    </span>│<span style="color: #008000; text-decoration-color: #008000">                                                 </span>│
│<span style="color: #008080; text-decoration-color: #008080">       meep </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                    </span>│<span style="color: #008000; text-decoration-color: #008000">                                                 </span>│
│<span style="color: #008080; text-decoration-color: #008080">       meow </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                    </span>│<span style="color: #008000; text-decoration-color: #008000">                                                 </span>│
│<span style="color: #008080; text-decoration-color: #008080">     lumapi </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                    </span>│<span style="color: #008000; text-decoration-color: #008000">                                                 </span>│
│<span style="color: #008080; text-decoration-color: #008080">        sax </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                    </span>│<span style="color: #008000; text-decoration-color: #008000">                                                 </span>│
└────────────┴──────────────────────────────────────────────────┴─────────────────────────────────────────────────┘
</pre>

**Comment by joamatab** [comment]
Hi,

It seems you may need to run a git pull to fetch the latest changes in GDSFactory.

As noted in the documentation, the cross_section is already defined for the example you mentioned.

Let me know if you need further assistance!

![image](https://github.com/user-attachments/assets/cce83835-f56f-49c9-8eac-cd945bc3bbe2)
