### ISSUE TITLE
Spiral bends

### ISSUE THREAD

**Issue by Arka-noid** [gdsfactory/gdsfactory#3394]
**Describe the bug**
The function gdsfactory.components.spiral has a bend parameter that only accepts a function with a radius and a cross-section parameters.
Providing another bend from somewhere else (e.g. another function, or an external gds) cannot be done without screwing the spiral layout.

**To Reproduce**
Create another bend with a different radius of the cross-section you provide.
Example
```python
import gdsfactory as gf

gf.components.spiral(
    cross_section="strip",
    bend=gf.get_component("bend_euler", radius=50),
).show()
```

**Expected behavior**
The spiral adapts to the new bend

**Suggested fix**
The radius for the straight length calculation is done from the cross-section itself
```python
    b = gf.get_component(bend, cross_section=cross_section)
    radius = xs.radius
```
**Proposal**:
Calculate the "radius" from the bend ports itself, assuming that: 

1. the bend has two ports named "o1" and "o2".
2. it is a 90 deg bend

```python
    cross_section_bends = cross_section_bends or cross_section

    if cross_section_bends is None:
        b = gf.get_component(bend)
    else:
        b = gf.get_component(bend, cross_section=cross_section_bends)
    radius = abs(b.ports["o1"].dx - b.ports["o2"].dx)  # Assuming a 90 deg bend
    # radius = xs.radius
```
Here I introduced another parameter, but it may be not necessary.

This method allows you to define also tapers on the bends and still have a working spiral (remove the dependency on the radius).

**Environment (please complete the following information):**

- [x] I have reviewed the documentation, discussions and issues and found no relevant solution.
- [x] I understand that this is an open-source project, and maintainers may not have the resources to address every issue. I am prepared to contribute by fixing the issue myself or hiring someone to do so, if needed, and accept that the issue may not be resolved otherwise.
- [x] I am using the latest version of GDSFactory, with Python 3.10, 3.11, or 3.12.

                                    Modules                                    
┌────────────┬────────────────────────────────┬───────────────────────────────┐
│    Package │ version                        │                          Path │
├────────────┼────────────────────────────────┼───────────────────────────────┤
│     python │ 3.11.7 | packaged by Anaconda, │ C:\ProgramData\Anaconda3\pyt… │
│            │ Inc. | (main, Dec 15 2023,     │                               │
│            │ 18:05:47) [MSC v.1916 64 bit   │                               │
│            │ (AMD64)]                       │                               │
│ gdsfactory │ 8.17.0                         │ C:\ProgramData\Anaconda3\Lib… │
│   gplugins │ 1.0.2                          │ ['C:\\ProgramData\\Anaconda3… │
│        ray │ not installed                  │                               │
│    femwell │ 0.1.11                         │ ['C:\\ProgramData\\Anaconda3… │
│     devsim │ 2.8.2                          │ ['C:\\ProgramData\\Anaconda3… │
│     tidy3d │ 2.7.0                          │ ['C:\\ProgramData\\Anaconda3… │
│       meep │ not installed                  │                               │
│       meow │ 0.9.0                          │ ['C:\\ProgramData\\Anaconda3… │
│     lumapi │ not installed                  │                               │
│        sax │ 0.13.1                         │ ['C:\\ProgramData\\Anaconda3… │
└────────────┴────────────────────────────────┴───────────────────────────────┘

**Comment by joamatab** [comment]
thank you Manuel for reporting this and for the suggested fix,

i went with the port spacing as it's more robust

See
https://github.com/gdsfactory/gdsfactory/pull/3402
