### ISSUE TITLE
Waveguide Separation in get_bundle_from_waypoints.py

### ISSUE THREAD

**Issue by SiHuiAthenaPan** [gdsfactory/gdsfactory#346]
When the separation parameter is set, sometime it reduce the separation of two waveguide to 0. I think it's due to line 234 in this file. np.sign(offsets_start[1]) give 0 if offset_start[1] == 0, which happens sometime. I changed it to the following (see attached screenshot) and it fixes the issue. I'd suggest adding this fix to master.

    if separation and len(ports1) > 1:
        # the default case when we start with the reference port
        offeset_start_sign = np.sign(offsets_start[1]) if np.sign(offsets_start[1]) != 0 else 1
        offsets_mid = [
            offeset_start_sign * separation * i
            for i, o in enumerate(offsets_start)
        ]

**Comment by joamatab** [comment]
Thank you Athena!

updating it in 5.5.1
`gdsfactory/routing/get_bundle_from_waypoints.py`

it would also be great if you could also include some code to reproduce the issue, to make sure we can add a test for it
