### ISSUE TITLE
Cell.py crashes when metadata_child has no "name" field.

### ISSUE THREAD

**Issue by SiHuiAthenaPan** [gdsfactory/gdsfactory#348]
I simply changed metadata_child['name'] to metadata_child.get('name') in line 163 in cell.py file and it bypasses the error. Not sure if this is the best way to fix this, but it works for me.

        if metadata_child and component.get_child_name:
            component_name = f"{metadata_child.get('name')}_{name}"
            component_name = get_name_short(
                component_name, max_name_length=max_name_length
            )
        else:
            component_name = name

**Comment by joamatab** [comment]
Thank you Athena!

releasing 5.5.1 with your improvements
