### ISSUE TITLE
awg and splitter_tree cannot be read from YAML

### ISSUE THREAD

**Issue by kuangfio** [gdsfactory/gdsfactory#3520]
**Describe the bug**
When creating a component from YAML, if it contains an awg or splitter_tree, a TypeError occurs.
`TypeError: 'str' object is not callable`

**To Reproduce**
YAML file: 
example.yaml
```
instances:
  C1:
    component: awg
    info:
      dx: 70.0
      dy: 43.75
    settings:
      arm_spacing: 1
      arms: 10
      cross_section: strip
      fpr_spacing: 50
      free_propagation_region_input_function: Ffree_propagation_region_Mgdsfactorypcomponentspfilterspawg_SI1
      free_propagation_region_output_function: Ffree_propagation_region_Mgdsfactorypcomponentspfilterspawg_SI10_W10_W20
      outputs: 8
  C2:
    component: ring_single
    info:
      dx: 30.0
      dy: 21.8
    settings:
      bend: bend_euler
      coupler_ring: coupler_ring
      cross_section: strip
      gap: 0.2
      length_x: 4
      length_y: 0.6
      radius: 10
      straight: straight
placements:
  C1:
    rotation: 0
    x: 99.72200000000001
    y: 172.917
  C2:
    rotation: 0
    x: 380.833
    y: 111.806
ports:
  o1: C2,o1
routes:
  optical:
    links:
      C1,o1: C2,o2
    routing_strategy: route_bundle
    settings:
      cross_section: strip
```

Python code:
`c = gf.read.from_yaml("example.yaml")`

Output:
```
Traceback (most recent call last):
  File "c:\Users\kuang\Downloads\Code\Code\test2.py", line 58, in <module>
    c = gf.read.from_yaml("example.yaml")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kuang\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gdsfactory\read\from_yaml.py", line 809, in from_yaml
    net = Netlist.model_validate(dct)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kuang\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydantic\main.py", line 596, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kuang\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gdsfactory\schematic.py", line 77, in update_settings_and_info
    c = gf.get_component(component, settings=settings)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kuang\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gdsfactory\pdk.py", line 625, in get_component
    return get_active_pdk().get_component(component, settings=settings, **kwargs_clean)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kuang\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gdsfactory\pdk.py", line 336, in get_component
    return self._get_component(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kuang\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gdsfactory\pdk.py", line 393, in _get_component
    return self.cells[component](**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kuang\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\kfactory\kcell.py", line 4584, in wrapper_autocell
    _cell = wrapped_cell(**params)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kuang\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\cachetools\__init__.py", line 752, in wrapper
    v = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kuang\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\kfactory\kcell.py", line 4436, in wrapped_cell
    cell = f(**params)  # type: ignore[call-arg]
           ^^^^^^^^^^^
  File "C:\Users\kuang\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gdsfactory\components\filters\awg.py", line 129, in awg
    fpr_in = free_propagation_region_input_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'str' object is not callable
```

**Expected behavior**
The component should not throw an exception.

**Suggested fix**
Maybe a yaml tag would be helpful with fixing this issue.

**Environment (please complete the following information):**

- [x] I have reviewed the documentation, discussions and issues and found no relevant solution.
- [x] I understand that this is an open-source project, and maintainers may not have the resources to address every issue. I am prepared to contribute by fixing the issue myself or hiring someone to do so, if needed, and accept that the issue may not be resolved otherwise.
- [x] I am using the latest version of GDSFactory, with Python 3.10, 3.11, or 3.12.

Please provide the output for the following code:

```python
import sys
print(sys.version)
print(sys.executable)

import gdsfactory as gf
gf.config.print_version_plugins()
```
<pre style="white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace"><span style="font-style: italic">                                                      Modules                                                      </span>
┏━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃<span style="font-weight: bold">    Package </span>┃<span style="font-weight: bold"> version                                          </span>┃<span style="font-weight: bold">                                            Path </span>┃
┡━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│<span style="color: #008080; text-decoration-color: #008080">     python </span>│<span style="color: #800080; text-decoration-color: #800080"> 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024,       </span>│<span style="color: #008000; text-decoration-color: #008000"> C:\Users\kuang\AppData\Local\Microsoft\Windows… </span>│
│<span style="color: #008080; text-decoration-color: #008080">            </span>│<span style="color: #800080; text-decoration-color: #800080"> 10:12:12) [MSC v.1938 64 bit (AMD64)]            </span>│<span style="color: #008000; text-decoration-color: #008000">                                                 </span>│
│<span style="color: #008080; text-decoration-color: #008080"> gdsfactory </span>│<span style="color: #800080; text-decoration-color: #800080"> 8.26.2                                           </span>│<span style="color: #008000; text-decoration-color: #008000"> C:\Users\kuang\AppData\Local\Packages\PythonSo… </span>│
│<span style="color: #008080; text-decoration-color: #008080">   gplugins </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                    </span>│<span style="color: #008000; text-decoration-color: #008000">                                                 </span>│
│<span style="color: #008080; text-decoration-color: #008080">        ray </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                    </span>│<span style="color: #008000; text-decoration-color: #008000">                                                 </span>│
│<span style="color: #008080; text-decoration-color: #008080">    femwell </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                    </span>│<span style="color: #008000; text-decoration-color: #008000">                                                 </span>│
│<span style="color: #008080; text-decoration-color: #008080">     devsim </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                    </span>│<span style="color: #008000; text-decoration-color: #008000">                                                 </span>│
│<span style="color: #008080; text-decoration-color: #008080">     tidy3d </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                    </span>│<span style="color: #008000; text-decoration-color: #008000">                                                 </span>│
│<span style="color: #008080; text-decoration-color: #008080">       meep </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                    </span>│<span style="color: #008000; text-decoration-color: #008000">                                                 </span>│
│<span style="color: #008080; text-decoration-color: #008080">       meow </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                    </span>│<span style="color: #008000; text-decoration-color: #008000">                                                 </span>│
│<span style="color: #008080; text-decoration-color: #008080">     lumapi </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                    </span>│<span style="color: #008000; text-decoration-color: #008000">                                                 </span>│
│<span style="color: #008080; text-decoration-color: #008080">        sax </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                    </span>│<span style="color: #008000; text-decoration-color: #008000">                                                 </span>│
└────────────┴──────────────────────────────────────────────────┴─────────────────────────────────────────────────┘
</pre>

**Comment by joamatab** [comment]
Thanks for reporting this.

This should work now if you

```
pip install git+https://github.com/gdsfactory/gdsfactory --force-reinstall
```

```python
import gdsfactory as gf 

d = """
instances:
  C1:
    component: awg
    info:
      dx: 70.0
      dy: 43.75
    settings:
      arm_spacing: 1
      arms: 10
      cross_section: strip
      fpr_spacing: 50
      outputs: 8
  C2:
    component: ring_single
    info:
      dx: 30.0
      dy: 21.8
    settings:
      bend: bend_euler
      coupler_ring: coupler_ring
      cross_section: strip
      gap: 0.2
      length_x: 4
      length_y: 0.6
      radius: 10
      straight: straight
placements:
  C1:
    rotation: 0
    x: 99.72200000000001
    y: 172.917
  C2:
    rotation: 0
    x: 380.833
    y: 111.806
ports:
  o1: C2,o1
routes:
  optical:
    links:
      C1,o1: C2,o2
    routing_strategy: route_bundle
    settings:
      cross_section: strip
"""

c = gf.read.from_yaml(d)
c.show()
```
