### ISSUE TITLE
route_ports_to_side does not accept kwargs

### ISSUE THREAD

**Issue by kuangfio** [gdsfactory/gdsfactory#3545]
**Describe the bug**
Documentation for route_ports_to_side suggests that it can take kwargs, however in practice it does not.

**To Reproduce**
```
c = gf.Component()
ref = c << gf.components.mmi2x2()

routes, ports = gf.routing.route_ports_to_side(
        component=c,
        cross_section="strip",
        ports=ref.ports.filter(orientation=180),
        side="west",
        x=(float(c.bbox_np()[0][0])-100),
        kwargs={"separation":30}
    )

c.plot()
```
TypeError: route_ports_to_side() got an unexpected keyword argument 'kwargs'

I tried passing kwargs another way but it also did not work.
```
c = gf.Component()
ref = c << gf.components.mmi2x2()

routes, ports = gf.routing.route_ports_to_side(
        component=c,
        cross_section="strip",
        ports=ref.ports.filter(orientation=180),
        side="west",
        x=(float(c.bbox_np()[0][0])-100),
        **{"separation":30}
    )

c.plot()
```
TypeError: route_ports_to_side() got an unexpected keyword argument 'separation'

**Expected behavior**
route_ports_to_side should not throw error when passing kwargs.

**Suggested fix**
Please modify route_ports_to_side so kwargs is a parameter it can take.

**Environment (please complete the following information):**

- [x] I have reviewed the documentation, discussions and issues and found no relevant solution.
- [x] I understand that this is an open-source project, and maintainers may not have the resources to address every issue. I am prepared to contribute by fixing the issue myself or hiring someone to do so, if needed, and accept that the issue may not be resolved otherwise.
- [x] I am using the latest version of GDSFactory, with Python 3.10, 3.11, or 3.12.

Please provide the output for the following code:

```python
import sys
print(sys.version)
print(sys.executable)

import gdsfactory as gf
gf.config.print_version_plugins()
```

<pre style="white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace"><span style="font-style: italic">                                                      Modules                                                      </span>
┏━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃<span style="font-weight: bold">        Package </span>┃<span style="font-weight: bold"> version                                        </span>┃<span style="font-weight: bold">                                          Path </span>┃
┡━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│<span style="color: #008080; text-decoration-color: #008080">         python </span>│<span style="color: #800080; text-decoration-color: #800080"> 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024,     </span>│<span style="color: #008000; text-decoration-color: #008000"> C:\Users\kuang\AppData\Local\Microsoft\Windo… </span>│
│<span style="color: #008080; text-decoration-color: #008080">                </span>│<span style="color: #800080; text-decoration-color: #800080"> 10:12:12) [MSC v.1938 64 bit (AMD64)]          </span>│<span style="color: #008000; text-decoration-color: #008000">                                               </span>│
│<span style="color: #008080; text-decoration-color: #008080">     gdsfactory </span>│<span style="color: #800080; text-decoration-color: #800080"> 8.27.1                                         </span>│<span style="color: #008000; text-decoration-color: #008000"> C:\Users\kuang\AppData\Local\Packages\Python… </span>│
│<span style="color: #008080; text-decoration-color: #008080">         devsim </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                  </span>│<span style="color: #008000; text-decoration-color: #008000">                                               </span>│
│<span style="color: #008080; text-decoration-color: #008080">        femwell </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                  </span>│<span style="color: #008000; text-decoration-color: #008000">                                               </span>│
│<span style="color: #008080; text-decoration-color: #008080"> gdsfactoryplus </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                  </span>│<span style="color: #008000; text-decoration-color: #008000">                                               </span>│
│<span style="color: #008080; text-decoration-color: #008080">       gplugins </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                  </span>│<span style="color: #008000; text-decoration-color: #008000">                                               </span>│
│<span style="color: #008080; text-decoration-color: #008080">         lumapi </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                  </span>│<span style="color: #008000; text-decoration-color: #008000">                                               </span>│
│<span style="color: #008080; text-decoration-color: #008080">           meep </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                  </span>│<span style="color: #008000; text-decoration-color: #008000">                                               </span>│
│<span style="color: #008080; text-decoration-color: #008080">           meow </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                  </span>│<span style="color: #008000; text-decoration-color: #008000">                                               </span>│
│<span style="color: #008080; text-decoration-color: #008080">            ray </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                  </span>│<span style="color: #008000; text-decoration-color: #008000">                                               </span>│
│<span style="color: #008080; text-decoration-color: #008080">            sax </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                  </span>│<span style="color: #008000; text-decoration-color: #008000">                                               </span>│
│<span style="color: #008080; text-decoration-color: #008080">         tidy3d </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                  </span>│<span style="color: #008000; text-decoration-color: #008000">                                               </span>│
│<span style="color: #008080; text-decoration-color: #008080">          vlsir </span>│<span style="color: #800080; text-decoration-color: #800080"> not installed                                  </span>│<span style="color: #008000; text-decoration-color: #008000">                                               </span>│
└────────────────┴────────────────────────────────────────────────┴───────────────────────────────────────────────┘
</pre>

**Comment by joamatab** [comment]
Thank you for reporting this!

See fix here
https://github.com/gdsfactory/gdsfactory/pull/3547

You can use `route_ports_to_x` or `route_ports_to_y` as well
