### ISSUE TITLE
complex indices for materials in write_sparameters_lumerical

### ISSUE THREAD

**Issue by Jan-David-Black** [gdsfactory/gdsfactory#363]
**Is your feature request related to a problem? Please describe.**
Cannot use (n,k) Materials in Lumerical in the current state

**Describe the solution you'd like**
Enable passing a complex index to `write_sparameters_lumerical` (thru `material_name_to_lumerical`). This could be done by adding the following snippet to handle the complex index: 
``` python
elif isinstance(material, complex):
            mat = s.addmaterial("(n,k) Material")
            s.setmaterial(mat, "Refractive Index", material.real)
            s.setmaterial(mat, "Imaginary Refractive Index", material.imag)
            s.setnamed(layername, "material", mat)
```

Note that setting the material in lumerical depending whether a str, int or float is used is repeated twice, once for the cladding and once for the layers. It might make sense to refactor that into a function.

**Comment by joamatab** [comment]
Hi @Jan-David-Black ,

yes, that's a great idea, thank you for sharing,

How does this new branch work for you?
https://github.com/gdsfactory/gdsfactory/tree/559 

I made a new function set_material() as you suggested

**Comment by Jan-David-Black** [comment]
Looks Great! I am sorry I only throw stuff in here and don't just open a pull request, with everything set up properly. At some point I will find the time configure a "build environment" so that I can contribute more efficiently!

**Comment by Jan-David-Black** [comment]
What was the problem with using complex instead of a tuple of floats?

**Comment by joamatab** [comment]
now it can do both tuples and complex refractive index

![image](https://user-images.githubusercontent.com/4514346/167162446-6f8a90c6-be3c-452b-b0b2-51532ee84822.png)

**Comment by Jan-David-Black** [comment]
> now it can do both tuples and complex refractive index

ah understood :)
