### ISSUE TITLE
Inform About incompatibility with python<3.7

### ISSUE THREAD

**Issue by Jan-David-Black** [gdsfactory/gdsfactory#384]
**Describe the bug**
When installing on python 3.6 (I assume this holds true for smaller versions also) using pip:
```
pip install gdsfactory
```
the installation fails silently. Afterwards pip lists gdsfactory as an installed module, which however cannot be imported in python. In `site-packages` only a `.dist-info`is added but the source code itself is missing.

**To Reproduce**
Install gdsfactory in an environment wit python 3.6

**Expected behavior**
Fail to install or at least warn about incompatibility

**Suggested fix**
Have not looked into possible fixes yet

**Comment by joamatab** [comment]
python3.6 has reached end of life

We have some options here for dealing with python3.6 installs:

1. we keep it as it is (installs an old version) of gdsfactory
2. we delete if all versions from 1.1.1 to 2.4.9 from pypi
3. we bring back 3.6 compatibility https://github.com/asottile-archive/future-annotations

What do you think?

**Comment by joamatab** [comment]
I like options 1 and 2

@tvt173 
@flaport

**Comment by flaport** [comment]
I think it's never a good idea to remove legacy versions to be honest. So I would be against option 2. Just go for 1 and list clearly in the Readme that gdsfactory is python 3.7+.

**Comment by joamatab** [comment]
yes, 

we already say that on the docs installation section
https://gdsfactory.github.io/gdsfactory/notebooks/_2_klayout.html

**Comment by Jan-David-Black** [comment]
Absolutely, I think, that the statement is already present in the docs. I was unsure about the degree of incompatibility to 3.6 however. Maybe we could add a sentence stating, that 2.4.9 was the last version supported by python 3.6. And that pip will select this version for py 3.6 environments, which is fundamentally and structurally different to the latest version.

**Comment by tvt173** [comment]
sounds good to me, and seems to be the [standard official recommendation](https://packaging.python.org/en/latest/guides/dropping-older-python-versions/#dropping-a-python-release)
