### ISSUE TITLE
Offsets generate route errors

### ISSUE THREAD

**Issue by thomasdorch** [gdsfactory/gdsfactory#396]
get_bundle_waypoints tries to reverse the offset between ports (line 243, 244):

`    if start_angle in [90, 270]:
        offsets_start = [-_d for _d in offsets_start]`

When routing from a set of 270-degree ports to a set of 0-degree ports to their SW, the router throws a route error. Below is a minimum example of this behavour:

`    import gdsfactory as gf

    c = gf.Component("pads_bundle_steps")
    pt = c << gf.components.pad_array(
        gf.partial(gf.components.pad, size=(30, 30)),
        orientation=270,
        columns=3,
        spacing=(50, 0),
    )
    pb = c << gf.components.pad_array(orientation=0, columns=1, rows=3)
    pt.move((500, 500))

    routes = get_bundle_from_steps_electrical(
        pt.ports,
        pb.ports,
        end_straight_length=60,
        separation=30,
        steps=[{"dy": -50}, {"dx": -100}],
    )

    for route in routes:
        c.add(route.references)

    c.show()`

This can be fixed by removing the 270 from the list:
 `   if start_angle in [90]:
        offsets_start = [-_d for _d in offsets_start]`

**Comment by joamatab** [comment]
Awesome, thank you Thomas

**Comment by joamatab** [comment]
the issue with that change is that it breaks the bundle_u_indirect test

![image](https://user-images.githubusercontent.com/4514346/169327464-737e5676-9682-4696-bb2c-01f9aa68ce2a.png)


maybe we can add a flag to remove the offset start with 270 degrees angle,
what do you think?

**Comment by joamatab** [comment]
I think we can change that line

it fixes the issue

![image](https://user-images.githubusercontent.com/4514346/169348183-aab39ad0-e4c8-4521-8d73-3240a7f84d9e.png)

**Comment by joamatab** [comment]
it works for all the tests cases we have, im releasing 5.7.0 with all your new improvements, thank you Thomas!

**Comment by joamatab** [comment]
just released 5.7.0
