### ISSUE TITLE
support routes with `None` orientation ports

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#401]
How can we support bundle routes with ports that have orientation=`None` ?

```
if __name__ == "__main__":
    import gdsfactory as gf

    c = gf.Component("pads_bundle_steps")
    pt = c << gf.components.pad_array(
        gf.partial(gf.components.pad, size=(30, 30)),
        orientation=None,
        columns=3,
        spacing=(50, 0),
    )
    pb = c << gf.components.pad_array(orientation=None, columns=1, rows=3)
    pt.move((500, 500))

    routes = gf.routing.get_bundle_from_steps_electrical(
        pt.ports,
        pb.ports,
        end_straight_length=60,
        separation=30,
        steps=[{"dy": -50}, {"dx": -100}],
    )

    for route in routes:
        c.add(route.references)

    c.show()

```

**Comment by tvt173** [comment]
do we support routes with `None` orientation ports? or neither bundles or routes at the moment? i would think it should just take an extra step of picking the most direct orientation to follow before routing

**Comment by joamatab** [comment]
Not yet

PRs are most welcome:)

@SkandanC

**Comment by SkandanC** [comment]
@joamatab 

I added a piece of code to add waypoints for None orientation ports as an "initial guess". The problem now is sorting the ports. The routing function fails when the port orientation is None, since the relative orientations of the input and output ports cannot be calculated.
![image](https://user-images.githubusercontent.com/100642027/189973485-4c57809f-811d-470c-ab02-8114014a0464.png)

But when I hard code in the port orientations just before sorting, I get this:

![image](https://user-images.githubusercontent.com/100642027/189973658-8292f56f-4f63-469d-91a2-7fa7497419ef.png)

**Comment by SkandanC** [comment]
Fixed it (this is with `None` orientation)
![image](https://user-images.githubusercontent.com/100642027/190045329-e9698483-6d39-4f77-80ac-48c54fa568ec.png)

Another example:
```
import gdsfactory as gf

    c = gf.Component("get_route_from_steps_sample")
    w = gf.components.array(
        gf.partial(gf.components.straight, layer=(2, 0)),
        rows=3,
        columns=1,
        spacing=(0, 50),
    )

    left = c << w
    right = c << w
    right.move((200, 100))
    p1 = left.get_ports_list(orientation=None)
    for port in p1:
        port.orientation = None
    p2 = right.get_ports_list(orientation=None)
    for port in p2:
        port.orientation = None
    routes = get_bundle_from_steps(
        p1,
        p2,
        steps=[{"x": 150}, {"y": 100}],
    )

    for route in routes:
        c.add(route.references)

    c
    c.show()
```
![image](https://user-images.githubusercontent.com/100642027/190045512-5344ba19-add5-41a2-a01d-726819ba524a.png)

@tvt173 @joamatab

**Comment by joamatab** [comment]
Amazing! Thank you Skandan

**Comment by joamatab** [comment]
fixed in https://github.com/gdsfactory/gdsfactory/pull/702
