### ISSUE TITLE
Crosssection not completely applied for MZI

### ISSUE THREAD

**Issue by Jan-David-Black** [gdsfactory/gdsfactory#402]
**Describe the bug**
The `cross_section` property passed to the mzi component is ignored for the x-straights

**To Reproduce**
```python
from gdsfactory.cross_section import heater_metal
gf.components.mzi(cross_section=heater_metal)
```

**Expected behavior**
The crossection is used for all wgs of the MZI

**Suggested fix**
Use `cross_section=cross_section` [here](https://github.com/gdsfactory/gdsfactory/blob/49a9a930756966ee42093893f6c3b058d7da44c8/gdsfactory/components/mzi.py#L103) and [here](https://github.com/gdsfactory/gdsfactory/blob/49a9a930756966ee42093893f6c3b058d7da44c8/gdsfactory/components/mzi.py#L119)

**Comment by joamatab** [comment]
Hi Jan

I added cross-section settings to the mzi as you suggested and released 5.7.1

thank you for your suggestion
