### ISSUE TITLE
Klayout connectivity issue

### ISSUE THREAD

**Issue by PHS0916** [gdsfactory/gdsfactory#450]
When I test the first example in the 'gdsfactory in 5 min', there was no error but nothing happened on the Klayout...
I followed the installation tutorial but there was no output on the Klayout..

**Comment by joamatab** [comment]
How did you install the klayout plug-in?

Through command line or from the klayout package manager?

Did you restart klayout?

**Comment by joamatab** [comment]
Both command line or gui should work

What operating system are you using?

Can you send a screenshot of your klayout macros installed?

When you open the klayout macros, you should see the olive macro running 

What you you see when you run the klive macro?
