### ISSUE TITLE
remove picwriter depedency

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#471]
15% of gdsfactory module load time is on picwriter

`scalene gdsfactory/__init__.py `

![image](https://user-images.githubusercontent.com/4514346/174866993-c6ba7a0e-7925-4007-959e-d325a93d115f.png)

we need to rewrite the picwriter based components natively into gdsfactory

TODO:

- [x] disk.py https://github.com/gdsfactory/gdsfactory/pull/606
- [ ] spiral.py
- [x] dbr_tapered.py https://github.com/gdsfactory/gdsfactory/pull/601
- [x] coupler_full.py  https://github.com/gdsfactory/gdsfactory/pull/600
- [x] coupler_adiabatic.py
- [ ] grating_coupler_circular.py
- [x] cdc.py

**Comment by joamatab** [comment]
the issue with the picwriter components is that it does not use the Path and CrossSection from gdsfactory, so it cannot be extruded with arbitrary cross-sections.

```
disk.py
spiral.py
dbr_tapered.py
coupler_full.py
coupler_adiabatic.py
grating_coupler_circular.py
cdc.py

```

Advantages of porting picwriter components:

- make gdsfactory module faster to load
- components can have arbitrary cross-sections

**Comment by SkandanC** [comment]
@joamatab,

I tried moving the import inside the functions, but that doesn't seem to make a huge difference. I guess rewriting the picwriter-based components natively would be the better option. Would you like me to take a look into that?

Before moving import statements:
![image](https://user-images.githubusercontent.com/100642027/184403245-df448ebd-6287-4f29-b4d6-559ea78bdf26.png)

After moving import statements:
![image](https://user-images.githubusercontent.com/100642027/184403278-e1600dc5-cc26-491d-a9a8-cc9dbe89ea20.png)

**Comment by joamatab** [comment]
Hi Skandan,

Yes,
I think porting the few components that we use would be the best solution

**Comment by joamatab** [comment]
https://github.com/gdsfactory/gdsfactory/pull/600

**Comment by joamatab** [comment]
https://github.com/gdsfactory/gdsfactory/pull/601

We are half way done

Thank you Skandan

**Comment by joamatab** [comment]
2 more to go :)

thank you Skandan!

**Comment by SkandanC** [comment]
![image](https://user-images.githubusercontent.com/100642027/185551775-cf34d2ce-2fce-46a3-bef9-f5804be1e306.png)
Down to 9% now :)

**Comment by joamatab** [comment]
Nice, 

I think we can skip the circular grating coupler 

Once we implement the spiral we can remove picwriter
