### ISSUE TITLE
Snap components to grid

### ISSUE THREAD

**Issue by thomasdorch** [gdsfactory/gdsfactory#474]
Is there currently a function to move components and snap them to a grid automatically? It's easy enough to do that I wonder if there's a reason it's not already implemented. If others agree it's a useful addition, would it be better to have it as a standalone function like below or a flag in the `component.move()` method?

```
import gdsfactory as gf


def move_on_grid(
        component_ref: gf.types.ComponentReference,
        destination: tuple[float, float],
        grid_nm: int = 2,
        origin: tuple[float, float] = (0, 0),
        ) -> gf.types.ComponentReference:

    from gdsfactory.snap import snap_to_grid, is_on_grid

    if (not is_on_grid(origin[0], grid_nm)) or (not is_on_grid(origin[1], grid_nm)):
        raise ValueError(f'Origin needs to be on grid {grid_nm}nm!')

    x_dest = snap_to_grid(destination[0], nm=grid_nm)
    y_dest = snap_to_grid(destination[1], nm=grid_nm)

    component_ref.move(origin=origin, destination=(x_dest, y_dest))
    return component_ref
```

On a similar note, it might be useful to add a `grid_size` property to the PDK BaseModel and have cross sections and movement auto-snap to this value if it is defined.

**Comment by joamatab** [comment]
Hi Thomas,

we have functions for making sure ports endpoints are on grid and I added an issue of ports not being on grid and on manhattan orientation

https://github.com/gdsfactory/gdsfactory/issues/476

let me know if that's good

https://github.com/gdsfactory/gdsfactory/compare/51016c?expand=1


It also includes the `Pdk.grid_size = 0.001` (1nm by default)

For the `move_on_grid` function it looks good to me, when would it be useful?

**Comment by thomasdorch** [comment]
Hi Joaquin,

Thanks for adding that in, I think it's a nice addition! I just set up a PR for some minor changes to the snapping functions ([#478](https://github.com/gdsfactory/gdsfactory/pull/478)) so hopefully that works for you as well.

The issue I am having is that the snapping only really happens when we extrude cross sections, so 
```
gf.components.straight(length=10.0005)
```
will generate a warning (as of #478) because the port `'o2'` is off-grid, but 
```
s1.move((1.0005, 1.0005))
```
will not generate a warning, though the components are not properly placed on the grid. 

Since the minimum grid size is typically a global parameter, I think it would be helpful to, by default, snap components to a global grid when moving components as well as when extruding them. It would also ensure that floating point rounding errors don't creep into components without at least raising a warning. Essentially making this test pass:

```
import gdsfactory as gf
from gdsfactory.snap import is_on_grid

c = gf.Component()
s1 = c << gf.components.straight(length=10)
s2 = c << gf.components.straight(length=10)

s1.move((1.0005, 1.0005))
s2.connect(port='o1', destination=s1.ports['o2'])

c.show(show_ports=True)

assert is_on_grid(x=s2.ports['o1'].midpoint[0], nm=pdk.grid_size)
assert is_on_grid(x=s2.ports['o1'].midpoint[1], nm=pdk.grid_size)
```
