### ISSUE TITLE
The boolean doesn't work well.

### ISSUE THREAD

**Issue by YuleiDing** [gdsfactory/gdsfactory#487]
**Describe the bug**
If I use the boolean to merge the taper and rectangle, the taper will become a rectangle.

**To Reproduce**
Code to reproduce the behavior.
import gdsfactory as gf
c=gf.Component("ding0628")
d=gf.Component("ding0629")
taper1=gf.components.taper(length=100, width1=8, width2=20)
rect1=c<<gf.components.rectangle(size=[20,8])
rect1.move([100,-4]);
t=d<<gf.geometry.boolean(taper1,rect1,operation="A+B")
d.plot()
d.show()
![20220628195427](https://user-images.githubusercontent.com/105275217/176173873-1365ee76-6453-4ecc-87e2-04755384ccd6.png)

**Expected behavior**
I hope when use the boolean to merge the taper and rectangle, the taper is still a taper.

**Suggested fix**
If you have a solution for it.

**Comment by joamatab** [comment]
Hi,

by default the generic pdk adds the siepic layers for connectivity checks, so if you want to make a boolean you have to make sure you only add the layers that you want.

```
import gdsfactory as gf
from gdsfactory.geometry import boolean

c = gf.Component("ding0628")
d = gf.Component("ding0629")
taper1 = gf.components.taper(
    length=100,
    width1=8,
    width2=20,
    with_bbox=False,
    cladding_layers=None,
    add_bbox=None,
    add_pins=None,
)
rect1 = c << gf.components.rectangle(size=[20, 8])
rect1.move([100, -4])
t = d << gf.geometry.boolean(taper1, rect1, operation="A+B")
d.plot()
d.show()
```

![image](https://user-images.githubusercontent.com/4514346/176228771-fdceb208-1f9c-46d2-8cc4-96d58e2eb851.png)


Let me know what you think
