### ISSUE TITLE
extract generating component list for doe into a separate function for use in `pack_doe` and elsewhere

### ISSUE THREAD

**Issue by Jan-David-Black** [gdsfactory/gdsfactory#496]
**Is your feature request related to a problem? Please describe.**
I would like to use the doe generation as in pack_doe but pack multiple does together, which would be very easy if one could use the doe generation without packing the generated components directly

**Describe the solution you'd like**
A separate function to generate the doe, which is then used by `pack_doe` but can also be used elsewhere

**Comment by joamatab** [comment]
Thank you Jan-David!
