### ISSUE TITLE
nicer call signatures

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#503]
How can we render better call signatures?

See for example
https://gdsfactory.github.io/gdsfactory/components.html#mzi1x2-2x2

@flaport

**Comment by flaport** [comment]
Do you mean docstrings or call signatures? For me the call signature looks a lot more scary than the docstringe...

I personally like autodoc_typehints='description' to relieve some of the pressure on the call signature.

**Comment by flaport** [comment]
Also, if the type hint becomes too big it's worth aliasing your type hint for a shorter version.

**Comment by joamatab** [comment]
nice, `autodoc_typehints='description' ` worked great!


how could we also show a better function name for partials?

```
add_pins=functools.partial(<function add_pins_siepic>
```

**Comment by joamatab** [comment]
`autodoc_typehints='description'` merged

i also added a css to do one parameter per line

https://github.com/gdsfactory/gdsfactory/pull/510
