### ISSUE TITLE
Meep integration: automatically use effective refractive index

### ISSUE THREAD

**Issue by HelgeGehring** [gdsfactory/gdsfactory#504]
Using the function calculate_effective_permittivity introduced in #501 3D simulations can be reduced to 2D simulations.
How would we best integrate it into the meep-plugin to set it automatically?

```
from gdsfactory.components import mmi1x2
from gdsfactory.simulation.gmeep import write_sparameters_meep
from gdsfactory.simulation.effective_permittivity import calculate_effective_permittivity

mmi = mmi1x2(width_mmi=5, length_mmi=10, gap_mmi=1, length_taper=2)
mmi.show()
material_name_to_meep = {
    'si': float(calculate_effective_permittivity(3.477 ** 2, 1.444 ** 2, 1.444 ** 2, .22, 1.55, 'te')[0] ** .5)}
write_sparameters_meep(mmi, resolution=20, is_3d=False, animate=True, material_name_to_meep=material_name_to_meep)


```

**Comment by joamatab** [comment]
Hi Helge,

yes, i like it, it's very simple and functional :)

I think material_name_to_meep maps LayerStack layer names to refractive index (not permitivity). I also made some changes to be more consistent in [this branch](https://github.com/gdsfactory/gdsfactory/compare/5125)

let me know what you think
