### ISSUE TITLE
Meep integration: cell size not correctly calculated

### ISSUE THREAD

**Issue by HelgeGehring** [gdsfactory/gdsfactory#505]
The size of the Mode monitor is not correctly taken into account for bends:

```
from gdsfactory.components import bend_euler
from gdsfactory.simulation.gmeep import write_sparameters_meep
from gdsfactory.simulation.effective_permittivity import calculate_effective_permittivity

bend = bend_euler(radius=5)
material_name_to_meep = {
    'si': float(calculate_effective_permittivity(3.477 ** 2, 1.444 ** 2, 1.444 ** 2, .22, 1.55, 'te')[0] ** .5)}
write_sparameters_meep(bend, resolution=20, is_3d=False, animate=True, material_name_to_meep=material_name_to_meep)
```
![image](https://user-images.githubusercontent.com/42973196/176609223-0ddf1520-b45f-4368-b9e3-1a014c17c92c.png)

**Comment by joamatab** [comment]
yes, we could pass some padding, or you can use the bend90 function that we have in the docs

https://gdsfactory.github.io/gdsfactory/notebooks/plugins/meep/001_meep_sparameters.html#Port-symmetries

```
df = gm.write_sparameters_meep_1x1_bend90(c, run=False)
```

**Comment by simbilod** [comment]
See PR #512

**Comment by joamatab** [comment]
Hi Simon

i'd rather set the simulation manually, as we do now

the current solution:

- minimizes extra space
- lets you control the margin

```
write_sparameters_meep_mpi_1x1_bend90 = gf.partial(
    write_sparameters_meep_mpi,
    ymargin_bot=3,
    ymargin=0,
    xmargin_right=3,
    port_symmetries=port_symmetries.port_symmetries_1x1,
)
```
what do you think?

**Comment by simbilod** [comment]
[Agreed](https://github.com/gdsfactory/gdsfactory/pull/512#issuecomment-1171498325)

**Comment by joamatab** [comment]
another way to automatically fix these issues is to add `port_markers` 

![image](https://user-images.githubusercontent.com/4514346/176744084-83bf06e0-53ed-44f5-b97f-db42d7deb6c2.png)
![image](https://user-images.githubusercontent.com/4514346/176744084-83bf06e0-53ed-44f5-b97f-db42d7deb6c2.png)

**Comment by HelgeGehring** [comment]
> another way to automatically fix these issues is to add `port_markers`
> 
> ![image](https://user-images.githubusercontent.com/4514346/176744084-83bf06e0-53ed-44f5-b97f-db42d7deb6c2.png)

seems like the best approach!

**Comment by simbilod** [comment]
This is a good opportunity to allow these port markers to hold height and mode information to allow multilayer and multimode simulations #502

**Comment by joamatab** [comment]
see function to [add port markers in the docs](https://gdsfactory.github.io/gdsfactory/notebooks/plugins/meep/001_meep_sparameters.html#3D-rendering)
