### ISSUE TITLE
AttributeError in `write_sparameters_lumerical` with empty layer stack

### ISSUE THREAD

**Issue by Jan-David-Black** [gdsfactory/gdsfactory#511]
**Describe the bug**
If no layers of the provided component are present in the layer stack provided to `write_sparameters_lumerical` the error 
```
AttributeError: 'list' object has no attribute 'keys'
```
is raised

**To Reproduce**
call "write_sparameters_lumerical" with an empty layerstack

**Expected behavior**
Prints problematic layerstack in the error.  Does not create "meta-error"

**Suggested fix**
change this [line](https://github.com/gdsfactory/gdsfactory/blob/0299984c39a4031d4e05962d8b0cb5b08430618c/gdsfactory/simulation/lumerical/write_sparameters_lumerical.py#L256) to this:
```python
f"in layer stack {layer_to_thickness.keys()}"
```

**Comment by joamatab** [comment]
thank you Jan David!

i think you meant `in layer stack {layer_stack}`

let me know if i fixed it correctly in 5.12.6 (just released)

**Comment by Jan-David-Black** [comment]
Yeah, that is also possible. Wanted to stay as close as possible to the original, as I assumed a Typo. Much more informative with `in layer stack {layer_stack}`

**Comment by joamatab** [comment]
awesome! :)
