### ISSUE TITLE
schematic driven layout

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#516]
![image](https://user-images.githubusercontent.com/4514346/176816816-91ea4ba4-e14d-4739-9dba-d15d144fb813.png)

How can we make schematic capture of the circuits?

we currently support netlist flow

it would be great to support something like this for analog design flow

**Comment by thomasdorch** [comment]
Maybe something like [SchemDraw](https://schemdraw.readthedocs.io/en/latest/index.html)?

**Comment by joamatab** [comment]
Yes, ideally we can get

- automated completion of the circuit elements and ports for the active pdk
- hierarchical schematics 

The current YAML has some limitations 

@tvt173 
@flaport 
@proppy

**Comment by joamatab** [comment]
https://xschem.sourceforge.io/stefan/xschem_man/what_is_xschem.html
https://github.com/StefanSchippers/xschem

Im thinking that with some graphviz visualization on networkx we could support schematic capture

**Comment by proppy** [comment]
For python bases schematic capture, I looked a bit at https://github.com/devbisme/skidl but I think the current component model of gdsfactory might just be enough.

i.e a schematic is really just a graph of `Component` without size or position.

wdyt?

**Comment by proppy** [comment]
PDKMaster also demonstrated python bases schematic capture and layout at FSiC22: https://gitlab.com/Chips4Makers/c4m-pdk-freepdk45/-/blob/master/design/inverter.ipynb

**Comment by joamatab** [comment]
Yes, we can plot netlist from a component with networkX 

Ideally we can also allow users to reorder the graph, either with code or gui-like interactions adding bokeh or plotly callbacks 

@flaport

**Comment by proppy** [comment]
@mithro also pointed us to https://github.com/nturley/netlistsvg before

**Comment by joamatab** [comment]
https://github.com/StefanSchippers/xschem

Xschem is pretty nice for this

**Comment by joamatab** [comment]
Here is a nice schematic driven flow, with auto-place and auto-route

https://www.youtube.com/channel/UCd2faHHQ_OAC0hSqBmIRKUQ/videos

with the YAML flow we have place and AutoRoute

**Comment by joamatab** [comment]
-  https://qucat.org/tutorials/basics.html#Building-the-circuit-programmatically
- https://github.com/ntezak/cirq.git

**Comment by joamatab** [comment]
https://neilturley.dev/netlistsvg/
https://github.com/nturley/netlistsvg

@tvt173

**Comment by joamatab** [comment]
https://github.com/Vlsir/Hdl21Schematics

**Comment by joamatab** [comment]
release 6.3.1 includes schematic driven flow

https://gdsfactory.github.io/gdsfactory/notebooks/20_schematic_driven_layout.html

thank you Troy!
