### ISSUE TITLE
Loss calculation for MPB modes

### ISSUE THREAD

**Issue by thomasdorch** [gdsfactory/gdsfactory#529]
It would be nice to have absorption loss included in the mode calculations for the MPB plugin, similar to how Lumerical FDE calculates this in its mode solver. 

Since MPB doesn't handle complex refractive indices, is there a way to calculate this if complex indices for are passed into the solver?

**Comment by joamatab** [comment]
I think the tidy3d mode solver can handle complex refractive index

i've been using it as the main mode solver instead of MPB
