### ISSUE TITLE
disconnected waveguides in some manhattan routes

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#53]
How can we fix some disconnected waveguides in some manhattan routes?

```python
"""
Some manhattan routes have disconnected waveguides

"""

import gdsfactory as gf


if __name__ == "__main__":
    c = gf.Component()
    # c1 = c << gf.components.straight_array(spacing=200)
    c1 = c << gf.components.straight_array(spacing=50)
    c2 = c << gf.components.straight_array(spacing=5)

    c2.movex(200)
    c1.y = 0
    c2.y = 0

    routes = gf.routing.get_bundle_path_length_match(
        c1.get_ports_list(orientation=0),
        c2.get_ports_list(orientation=180),
        end_straight_length=0,
        start_straight_length=0,
        separation=50,
        radius=10,
        # radius=3 # smaller radius works
        enforce_port_ordering=False
    )

    for route in routes:
        c.add(route.references)

    c.show()
```

![image](https://user-images.githubusercontent.com/4514346/139594929-51caab0e-025b-4dd1-94cb-cb34a28a5f45.png)

![image](https://user-images.githubusercontent.com/4514346/120036625-46a2eb00-bfb5-11eb-8edd-9606caa6aa15.png)

**Comment by joamatab** [comment]
We can extend the new Sven's option to fix the caes with impossible manhattan routes

**Comment by SkandanC** [comment]
@joamatab 

![image](https://user-images.githubusercontent.com/100642027/190209782-401791e7-7990-441e-a1f4-fcc61ccf0019.png)
I added an bit of code to return s_bend bundle routes if a RouteWarning is raised and it gives me this.

What do you think?

**Comment by joamatab** [comment]
For path length matching sbends have different length so it may not be a good solution

**Comment by Hezq23** [comment]
I have encountered the same problem when I'm using the gdsfactory, I just mitigate it by using the partially bent waveguides to route instead of 90' waveguide bend. (I have written the routing function myself.) I know in gdsfactory, the waveguide bend used in route can only be 90', this is unnecessary and will sometimes cause trouble like the issue discussed.

**Comment by joamatab** [comment]
Yes, when this happens I usually change the position of one of the components that we are routing to

**Comment by joamatab** [comment]
here is the updated code for the issue 


```python
"""
Some manhattan routes have disconnected waveguides

"""

import gdsfactory as gf


if __name__ == "__main__":
    c = gf.Component()
    # c1 = c << gf.components.straight_array(spacing=200)
    c1 = c << gf.components.straight_array(spacing=50)
    c2 = c << gf.components.straight_array(spacing=5)

    c2.movex(200)
    c1.y = 0
    c2.y = 0

    routes = gf.routing.get_bundle_path_length_match(
        c1.get_ports_list(orientation=0),
        c2.get_ports_list(orientation=180),
        end_straight_length=0,
        start_straight_length=0,
        separation=50,
        radius=10,
        # radius=3 # smaller radius works
        enforce_port_ordering=False
    )

    for route in routes:
        c.add(route.references)

    c.show()
```
