### ISSUE TITLE
Error when specifying port name as origin for move operation

### ISSUE THREAD

**Issue by tvt173** [gdsfactory/gdsfactory#572]
Hi,
Previously we were able to supply a port name on the component reference as an origin for a move operation. This is now broken because of the renaming of `midpoint` to `center`. The problem is that `str` also has an attribute called `center`. I would recommend we check if the origin is a string first to catch this case.

https://github.com/gdsfactory/gdsfactory/blob/ecac4cf56c3989436428a010e6a60aecaeebdb87/gdsfactory/component_reference.py#L350

**Comment by joamatab** [comment]
Hi Troy, can you provide some code to reproduce the error? That way we can add a test for it:)

**Comment by joamatab** [comment]
i added a test for it and a fix

**Comment by tvt173** [comment]
thanks @joamatab !
