### ISSUE TITLE
Wrong type for connections in NetlistModel

### ISSUE THREAD

**Issue by flaport** [gdsfactory/gdsfactory#591]
Currently the connections field in NetlistModel has type

```python
    connections: Optional[List[Dict[str, str]]] = None
```

As can be seen here: https://github.com/gdsfactory/gdsfactory/blob/bfca5d09be769885ce4ce7f72ff4d5602d674e5a/gdsfactory/types.py#L201

This is wrong. It should have type

```python
    connections: Optional[Dict[str, str]] = None
```

**Comment by joamatab** [comment]
Thank you Floris!

Fixed it
https://github.com/gdsfactory/gdsfactory/commit/207f8e701925eaf827c076ddb35bac77d7095b3f
