### ISSUE TITLE
How to fix binder link?

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#603]
Binding not working,  not sure why

@flaport 

https://github.com/jupyterhub/binder/issues/269

**Comment by flaport** [comment]
Yes, I'm aware of it. I will iterate on the docker images a bit.

**Comment by joamatab** [comment]
The docker image seems to be building okay

**Comment by flaport** [comment]
Haha funny. I actually thought this was an issue for SAX.

**Comment by flaport** [comment]
In any case. I just fixed the SAX docker image. Have a look for some inspiration if you want:

https://github.com/flaport/sax/blob/master/Dockerfile

**Comment by joamatab** [comment]
thank you Floris,
I made a new repo for it

https://github.com/gdsfactory/binder-sandbox
