### ISSUE TITLE
more PCells

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#610]
Add Pcells from papers or other PDKs to the generic PDK

- [x] Mzi modulator
- [x] photodetector 
- [x] coherent tx
- [x] coherent rx
- [x] ring modulator 
- [x] capacitor
- [x] resistor

**Comment by simbilod** [comment]
what layerstack should these be built out of? the generic one here https://gdsfactory.github.io/gdsfactory/notebooks/08_pdk.html#layers ?

**Comment by joamatab** [comment]
Yes, we can use the generic pdk layer stack and then we can re target any fab

**Comment by Xies3** [comment]
Hi Joaquin, I'm currently working with Mehdi in the sky130 project. Is there any documentation of how to generate p cells? Thank you very much.

**Comment by joamatab** [comment]
https://gdsfactory.github.io/gdsfactory/notebooks/03_cells_autoname_and_cache.html
