### ISSUE TITLE
fast fully web based layout viewer

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#621]
How can we enable big layouts rendering in jupyter notebooks?

we could use the klayout python API and use some thing like folium

- https://python-visualization.github.io/folium/quickstart.html#GeoJSON/TopoJSON-Overlays
- https://github.com/klayoutmatthias/canvas2canvas

@flaport 
@proppy
@tvt173

**Comment by proppy** [comment]
I think that https://github.com/KLayout/klayout/issues/1082#issuecomment-1197720698 is the way to go.

Did you see the notebook example?

**Comment by proppy** [comment]
I think ideally we would just implement some of the `_repr` methods so that `Component` just render magically when evaluated at the end of cell.

**Comment by joamatab** [comment]
Where can we find the code for SiliWiz?

https://www.youtube.com/watch?v=V9xCa4RNfCM

@SkandanC 
@mithro 
@mattvenn

**Comment by mattvenn** [comment]
It's not public at the moment

**Comment by joamatab** [comment]
I see, let us know when we can use it,

also the 3D rendering on the browser looks great
https://www.youtube.com/watch?v=GlvlZzjyUGI&t=294s

**Comment by joamatab** [comment]
klayout 0.28 is out

https://pypi.org/project/klayout/

https://github.com/klayoutmatthias/canvas2canvas

**Comment by proppy** [comment]
@joamatab getting this issue when trying to use the new klayout 0.28:
https://github.com/KLayout/klayout/issues/1146#issuecomment-1345445086

Are you able to load a layout on your end?

**Comment by joamatab** [comment]
See MVP here

https://github.com/gdsfactory/kweb/issues/3

**Comment by joamatab** [comment]
TODO:

- [ ] Document how to deploy gdsfactory with kweb
- [ ] make an ipywidget for notebooks using klayout

**Comment by sebastian-goeldi** [comment]
https://stackoverflow.com/questions/74070505/how-to-run-fastapi-application-inside-jupyter

**Comment by joamatab** [comment]
that worked!

```
import asyncio
import uvicorn
from kweb.main import app


if __name__ == "__main__":
    config = uvicorn.Config(app)
    server = uvicorn.Server(config)
    loop = asyncio.get_event_loop()
    loop.create_task(server.serve())
```

**Comment by SkandanC** [comment]
might be too late now but https://github.com/wokwi/siliwiz it's open source.

**Comment by joamatab** [comment]
That looks great!

we have a jupyter demo

![image](https://user-images.githubusercontent.com/4514346/216492211-eb959d8b-faa1-467d-bf36-6ee508ed4ad1.png)

**Comment by joamatab** [comment]
we have 

- https://github.com/gdsfactory/kweb
- gdsfactory webapp in https://github.com/gdsfactory/gplugins/
