### ISSUE TITLE
rotate() got an unexpected keyword argument 'center'

### ISSUE THREAD

**Issue by zhixwang** [gdsfactory/gdsfactory#648]
**Describe the bug**
rotate() got an unexpected keyword argument 'center'

**To Reproduce**
`bar = gf.components.rectangle(size=[bar_length, lw1], centered=True).rotate(ang1, center = [0,0])`

**Expected behavior**
In the Documentation, rotate() supports center as an argument.

**Comment by joamatab** [comment]
Hi,

Where in the documentation?

https://gdsfactory.github.io/gdsfactory/_autosummary/gdsfactory.Component.html#gdsfactory.Component

**Comment by zhixwang** [comment]
https://gdsfactory.github.io/gdsfactory/notebooks/02_movement.html#

```
c = gf.Component("rectangles")
r = gf.components.rectangle(size=(10, 5), layer=(2, 0))
rect1 = c << r
rect2 = c << r

rect1.rotate(45)  # Rotate the first straight by 45 degrees around (0,0)
rect2.rotate(
    -30, center=[1, 1]
)  # Rotate the second straight by -30 degrees around (1,1)
c
```

**Comment by joamatab** [comment]
`rect` is not a `Component` but a `Component Reference`

`ComponentReference.rotate()` has a `center` method
