### ISSUE TITLE
DevSim plugin: using wurlitzer prevents working on Windows

### ISSUE THREAD

**Issue by mdecea** [gdsfactory/gdsfactory#674]
I am trying to use the devsim plugin on Windows, but wurlitzer is not available for Windows platforms (which is a known issue <https://github.com/minrk/wurlitzer/issues/12>).

Since it seems like it is only used to reduce text output, I suggest getting rid of the wurlitzer use or at least having checks in case someone is using Windows.

**Comment by joamatab** [comment]
Hi Marc,

thank you for your feedback

i removed the wurlitzer dependency
[wurlitzer](https://github.com/gdsfactory/gdsfactory/pull/675)
