### ISSUE TITLE
Error in tidy3d.modes.sweep_width

### ISSUE THREAD

**Issue by mdecea** [gdsfactory/gdsfactory#677]
I was trying to reproduce the code for sweeping the waveguide width in the Tidy3d plugin info page of the documentation (here <https://gdsfactory.github.io/gdsfactory/notebooks/plugins/tidy3d/01_tidy3d_modes.html>).

I'm using the code as given:

```
import gdsfactory.simulation.gtidy3d as gt
nm = 1e-3
df = gt.modes.sweep_width(
    width1=200 * nm,
    width2=1000 * nm,
    steps=11,
    wavelength=1.55,
    wg_thickness=220 * nm,
    slab_thickness=0 * nm,
    ncore=gt.modes.si,
    nclad=gt.modes.sio2,
)

gt.modes.plot_sweep_width(
    width1=200 * nm,
    width2=1000 * nm,
    steps=11,
    wavelength=1.55,
    wg_thickness=220 * nm,
    slab_thickness=0 * nm,
    ncore=gt.modes.si,
    nclad=gt.modes.sio2,
)
```

But when I execute the code I get the following error: 

```
Traceback (most recent call last):
  File XXX, line 17, in <module>
    df = gt.modes.sweep_width(
  File "XXX\gdsfactory\gdsfactory\simulation\gtidy3d\modes.py", line 651, in sweep_width
    neff[mode_number].append(np.real(wg.neffs[mode_number]))
IndexError: index 4 is out of bounds for axis 0 with size 4
```

Changing line 651 of gtidy3d/modes.py from `neff[mode_number].append(np.real(wg.neffs[mode_number]))` to `neff[mode_number].append(np.real(wg.neffs[mode_number-1]))` seems to solve the issue.

**Comment by joamatab** [comment]
perfect, thank you Marc!

releasing 5.26.3 with your fix
