### ISSUE TITLE
improve A* router

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#685]
```
import gdsfactory as gf

c = gf.Component("get_route_astar")
w = gf.components.straight()
left = c << w
right = c << w
right.move((100, 80))

obstacle = gf.components.rectangle(size=(100, 10))
obstacle1 = c << obstacle
obstacle2 = c << obstacle
obstacle1.ymin = 40
obstacle2.xmin = 25

port1 = left.ports["o2"]
port2 = right.ports["o2"]

routes = gf.routing.get_route_astar(
    component=c,
    port1=port1,
    port2=port2,
)
c.add(routes.references)
c.show()
```

![image](https://user-images.githubusercontent.com/4514346/189391735-6e05018b-7762-4cd5-982a-72a3d34f3aa8.png)

```
import gdsfactory as gf

cross_section = "metal1"

c = gf.Component("get_route_astar")
w = gf.components.straight(cross_section=cross_section)

left = c << w
right = c << w
right.move((100, 80))

obstacle = gf.components.rectangle(size=(100, 10), layer="M1")
obstacle1 = c << obstacle
obstacle2 = c << obstacle
obstacle1.ymin = 40
obstacle2.xmin = 25

port1 = left.ports["e2"]
port2 = right.ports["e2"]

routes = gf.routing.get_route_astar(
    component=c, port1=port1, port2=port2, cross_section="metal1", resolution=5
)
c.add(routes.references)
c.show()
```

```
"""FIXME.

We need to add an option to avoid specific layers
"""

if __name__ == "__main__":
    import gdsfactory as gf

    c = gf.Component()

    rect1 = c << gf.components.rectangle()
    rect2 = c << gf.components.rectangle()
    rect3 = c << gf.components.rectangle((2, 2), layer=(2, 0))
    rect2.move(destination=(8, 4))
    rect3.move(destination=(5.5, 1.5))

    port1 = gf.Port(
        "o1", 0, rect1.center + (0, 3), cross_section=gf.get_cross_section("strip")
    )
    port2 = port1.copy("o2")
    port2.orientation = 180
    port2.center = rect2.center + (0, -3)
    c.add_ports([port1, port2])
    route = gf.routing.get_route_astar(c, port1, port2, radius=0.5, width=0.5)
    c.add(route.references)

    c.show(show_ports=True)

```

![image](https://user-images.githubusercontent.com/4514346/189392411-3bebc5ee-7e13-436f-a01a-b847e25fbd0f.png)

@SkandanC

**Comment by SkandanC** [comment]
Hello @joamatab,

Thanks for letting me know. I will start working on this right away.

For the first example layout, I made a few minor adjustments, and changing the `resolution` parameter to 10 (a higher resolution minimizes turns/the pixelate-y effect), and changing the radius to 5 gives me this. Admittedly, it is not ideal, but I feel it is better than before. The main issue is that the A* algorithm does not optimize for minimal turns. Modifying it to do this would fix the issues in the first two examples. Could you explain what you mean by "avoid specific layers" in the third example?

![image](https://user-images.githubusercontent.com/100642027/189407300-71108b28-1e7e-4731-9d79-f07f29a4306d.png)

**Comment by joamatab** [comment]
nice, this looks much better, looking forward to your PR

it would be nice to add an optional `List[LayerSpec]` of layers that it needs to avoid, for example, 

metal1 only needs to avoid shapes in  metal1 , and does not need to avoid `waveguide` layer

i would use `c.get_polygons(layers)` so we only compute the bbox for the important layers that we need to avoid

**Comment by SkandanC** [comment]
Okay, I will look into that.

One way to minimize number of turns I think is to compute 4 or 5 shortest paths, sort them by number of turns and pick the one with the least number of turns. I will see if there are other options.

**Comment by SkandanC** [comment]
I added an `avoid_layers` option and `distance` option, and there is a significant improvement.

![image](https://user-images.githubusercontent.com/100642027/189441489-3723738c-5911-426e-baa6-337d1b2bfc86.png)

Doing 
```
cross_section = gf.get_cross_section("metal1", width=3, radius=1)

routes = get_route_astar(component=c, port1=port1, port2=port2, avoid_layers=[cross_section.layer], cross_section=cross_section, resolution=5, distance=5.5)
``` 
for the second example gives this:
![image](https://user-images.githubusercontent.com/100642027/189441796-d512dcf8-7429-4f5f-8063-4c0ce145ca28.png)

There are still a large number of turns, I will work on improving that.

**Comment by joamatab** [comment]
nice :tada: 

looks great Skandan

**Comment by SkandanC** [comment]
I added a cost addition to the heuristic function in the algorithm. Essentially, everytime it detects a turn, it is penalized for it, and so it tries to avoid as many turns as possible. Here are the updated results:

![image](https://user-images.githubusercontent.com/100642027/189471021-5a6bb114-ac71-4431-92e5-ff9011d3ee23.png)
![image](https://user-images.githubusercontent.com/100642027/189471023-9356e7e1-2a4a-432c-9a6e-23ff5cce4cb1.png)
