### ISSUE TITLE
astar router improvements

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#692]
How can we fix the Astar router for the code below?

```
import gdsfactory as gf

c = gf.Component("get_route_astar")
w = gf.components.straight()
left = c << w
right = c << w
right.move((100, 80))

obstacle = gf.components.rectangle(size=(100, 10))
obstacle1 = c << obstacle
obstacle2 = c << obstacle
obstacle1.ymin = 40
obstacle2.xmin = 25

port1 = left.ports["o2"]
port2 = right.ports["o2"]

routes = gf.routing.get_route_astar(
    component=c,
    port1=port1,
    port2=port2,
)
c.add(routes.references)
c.show()
```

@SkandanC

**Comment by SkandanC** [comment]
Doing 
```
routes = gf.routing.get_route_astar(
    component=c,
    port1=port1,
    port2=port2,
    resolution=5,
    distance=5.5,
    radius=5,
)
```
gives me this result in ~0.14 secs.

![image](https://user-images.githubusercontent.com/100642027/189490993-74826284-19c8-468b-b03a-35e0de4dbb55.png)

The resolution decides how many "leaps/hops" the algorithm has to do. For a layout like this, where the default resolution (1 micron) is much larger than the distance between the obstacles (~15+ microns), it has to step through too many points and that takes a long time. Increasing the resolution to about 5 microns fixes it (for this layout).

**Comment by joamatab** [comment]
perfect, thank you Skandan,

i added your comments to the notebook for documentation

im also having issues with separation

```
import gdsfactory as gf


c = gf.Component("get_route_astar")
cross_section = "metal1"
w = gf.components.straight(cross_section=cross_section)

left = c << w
right = c << w
right.move((100, 80))

obstacle = gf.components.rectangle(size=(100, 10), layer="M2")
obstacle1 = c << obstacle
obstacle2 = c << obstacle
obstacle1.ymin = 40
obstacle2.xmin = 25

port1 = left.ports["e2"]
port2 = right.ports["e2"]

routes = gf.routing.get_route_astar(
    component=c,
    port1=port1,
    port2=port2,
    cross_section="metal1",
    resolution=5,
    distance=5,
)
c.add(routes.references)
c.show()
```

![image](https://user-images.githubusercontent.com/4514346/189491460-42756197-42b3-427f-88c3-d2e1e824bb83.png)

**Comment by SkandanC** [comment]
```
routes = gf.routing.get_route_astar(
    component=c,
    port1=port1,
    port2=port2,
    cross_section="metal1",
    resolution=10,
    distance=5
)
```

![image](https://user-images.githubusercontent.com/100642027/189492268-0709b0c5-cc2f-4722-98e0-e294d0510c7e.png)
 I increased the resolution to make the algorithm not take hops too close to the obstacles. I will see what I can do about the part near the output port.

**Comment by SkandanC** [comment]
```
routes = gf.routing.get_route_astar(
    component=c,
    port1=port1,
    port2=port2,
    cross_section="metal1",
    resolution=10,
    distance=7,
)
```
Increasing the distanc to 7 fixed it.

![image](https://user-images.githubusercontent.com/100642027/189492371-bfd0da6b-da17-4307-be4b-d2eff652530e.png)

**Comment by joamatab** [comment]
I see, it's still touching on one side :)

![image](https://user-images.githubusercontent.com/4514346/189493418-7e68ed0b-0f37-43be-9251-0b4010bbb3a5.png)

**Comment by SkandanC** [comment]
That is true. But, there isn't enough space there between the port and the obstacle to resolve the `distance` parameter there.

**Comment by joamatab** [comment]
Yes, you are right, it looks great 

A more useful router would be a global router, I added some links to the issue #57
