### ISSUE TITLE
KLayout Technology

### ISSUE THREAD

**Issue by thomasdorch** [gdsfactory/gdsfactory#695]
I am working on getting our KLayout technology generated through the new klayout_tech module using the new LayerViews and KLayoutLayerProperties models, but there are a few issues because of how the layer properties (.lyp) file and LayerMap are defined currently:

1) Our generic layer properties file has three extra (unnamed) layers not defined in the LayerMap: (1/12), (31, 0), and (99, 0). I don't know what these layers are being used for, but I would like to either remove them or give them names. 

2) Some of the names contained in the layer file have layers in them -- is this necessary? If so, I can add a toggle to the LayerView that turns, for example, "SLAB150" into "SLAB150 2/0". Personally, I don't find it particularly useful to have the layer number on some of the layer names shown in KLayout but if others do, I'll add the toggle.

@joamatab

**Comment by joamatab** [comment]
I find the layer numbers useful when talking to people who don't have the layer map installed

Feel free to name the layers with no name 1/13 we use it for pin markers
