### ISSUE TITLE
The circle is not smooth

### ISSUE THREAD

**Issue by Wang-Clark** [gdsfactory/gdsfactory#72]
circle = gf.components.circle(radius=r, angle_resolution=2, layer=(1, 0))

When the angular resolution is small enough, the arc is not very smooth

![image](https://user-images.githubusercontent.com/75530092/139408027-3b467928-3d4c-442c-b8d6-20294da31df2.png
![circle](https://user-images.githubusercontent.com/75530092/139408221-1e367744-e227-4f2e-9459-3a3ff1da15e8.png)
)

**Comment by joamatab** [comment]
Hi Wang-Clark,

This is coming from the 1nm grid snapping of GDS,

you can use a higher angle resolution to reduce the number of points per degree and keep a smooth circle

```
import gdsfactory as gf

r = 0.1
c1 = gf.components.circle(radius=r, angle_resolution=10, layer=(1, 0))
c1.show()
```

![image](https://user-images.githubusercontent.com/4514346/139594407-df7409d9-f4e1-4c50-a586-1ffcc630158b.png)


You can also change the precision but i recommend not doing that

```
    import gdsfactory as gf

    r = 0.1
    c2 = gf.components.circle(radius=r, angle_resolution=2, layer=(1, 0))
    gdspath1 = c2.write_gds(precision=1e-9)  # 1nm is the default precision for most Photonics fabs
    gdspath2 = c2.write_gds(precision=10e-12) # you can also increase to 10pm resolution
    gf.show(gdspath2)

```

**Comment by Wang-Clark** [comment]
Thank you so much for your interest in my query and your suggestions are extremely helpful

**Comment by Wang-Clark** [comment]
> Hi Wang-Clark,
> 
> This is coming from the 1nm grid snapping of GDS,
> 
> you can use a higher angle resolution to reduce the number of points per degree and keep a smooth circle
> 
> ```
> import gdsfactory as gf
> 
> r = 0.1
> c1 = gf.components.circle(radius=r, angle_resolution=10, layer=(1, 0))
> c1.show()
> ```
> 
> ![image](https://user-images.githubusercontent.com/4514346/139594407-df7409d9-f4e1-4c50-a586-1ffcc630158b.png)
> 
> You can also change the precision but i recommend not doing that
> 
> ```
>     import gdsfactory as gf
> 
>     r = 0.1
>     c2 = gf.components.circle(radius=r, angle_resolution=2, layer=(1, 0))
>     gdspath1 = c2.write_gds(precision=1e-9)  # 1nm is the default precision for most Photonics fabs
>     gdspath2 = c2.write_gds(precision=10e-12) # you can also increase to 10pm resolution
>     gf.show(gdspath2)
> ```
