### ISSUE TITLE
Simpler install

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#723]
How can we simplify the installation process?

Options

- executable window anaconda on packager. Ship anaconda environment, use constructor to create a conda installer, or mambstructor for mamba 

@tvt173 
@HelgeGehring 
@simbilod 
@flaport 
@thomasdorch

**Comment by joamatab** [comment]
We have now releases available with installers for windows, mac and linux
https://github.com/gdsfactory/gdsfactory/releases

thanks to constructor
https://github.com/conda/constructor/blob/main/CONSTRUCT.md

we need to add some sort of menu, launcher, shortcuts

one idea is using anaconda-navigator
https://docs.continuum.io/anaconda/navigator/

**Comment by simbilod** [comment]
On Windows:

After downloading, the program shows up in Start menu:
![image](https://user-images.githubusercontent.com/46427609/191153486-1a6b4c73-febd-4c08-a03e-7585bd279f0b.png)

The provided Spyder has the package:
![image](https://user-images.githubusercontent.com/46427609/191153558-f816e73d-74e5-42c3-a699-87ba3a8122e6.png)

There is also an Anaconda Navigator (albeit not under gdsfactory folder) that crashed for me on launch:
![image](https://user-images.githubusercontent.com/46427609/191154087-588f5823-5999-40e0-bce8-ce459a3a82e5.png)

**Comment by simbilod** [comment]
It would also be nice if there was a quick way to load the docs after a fresh download

**Comment by simbilod** [comment]
Navigator works now, but it does not show up under the "gdsfactory" program (it is under anaconda)

**Comment by joamatab** [comment]
is it worth having it as a menu? 

can you launch jupyterlab and spyder from it?

or shall we remove it and upgrade to python3.10?

**Comment by simbilod** [comment]
Yes jupyterlabs and spyder can both be launched with the right environments from there, which is nice. If you are not a regular Python user and want to use gdsfactory this is a nice option

**Comment by simbilod** [comment]
![image](https://user-images.githubusercontent.com/46427609/191563828-f67568fb-8a97-4820-94f6-c653a2e6e0fd.png)

**Comment by joamatab** [comment]
This looks great, maybe as part of the post-install script we can also git clone the gdsfactory repo into your desktop or home folder, so you can get started with the tutorial,

what do you think?

**Comment by joamatab** [comment]
Hi,

does any of the users on windows see the gdsfactory on their desktop after running the installer?
It would also be great to create desktop shortcuts on windows

What do you think of using anaconda navigator to update gdsfactory?

Another option is to create a new launcher, GUI-like experience,
This would also allow us to do schematic driven flow
https://github.com/qiskit/qiskit-metal


@SkandanC 
@tvt173 
@simbilod

**Comment by SkandanC** [comment]
@joamatab I do not see gdsfactory on my desktop after installation. Also, I feel like the installation time (at least on windows) is a little too long, perhaps it is my old laptop that's the issue, unless others have experienced this as well.

**Comment by joamatab** [comment]
I have heard it's slow on windows, Mac and Linux is super fast compared to windows

**Comment by tcaduser** [comment]
You may have a faster windows install speed by temporarily disabling the antivirus.

**Comment by joamatab** [comment]
We are using conda constructor for building the installer
https://github.com/conda/constructor

For windows we use [install.bat](https://github.com/gdsfactory/gdsfactory/blob/master/install.bat) post install script
what do you get when you run this script by itself?

Did jax and jaxlib got installed too?

**Comment by SkandanC** [comment]
@joamatab 
![image](https://user-images.githubusercontent.com/100642027/192393725-25582461-43bc-41d0-8119-1ae7dd44a1ce.png)

**Comment by joamatab** [comment]
I see, If someone with a windows machine can fix the install.bat script it would be great

**Comment by joamatab** [comment]
I found a VM for windows to debug the installer

https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by SkandanC** [comment]
Turns out the error is because there's a version mismatch problem. The latest available version of jaxlib for Windows is 0.3.7, whereas the latest version of JAX is 0.3.21. So we can only have JAX 0.3.7 (released April 2022) for Windows users as of now 

@joamatab

**Comment by SkandanC** [comment]
Actually, it turns out the latest version is available, the install command just needs to be modified.

**Comment by joamatab** [comment]
Hi Skandan,

can you try again to see if it works?

it would be also great to add shorcuts on the desktop as part of the installer
https://github.com/conda/constructor/issues/573

**Comment by joamatab** [comment]
We are not adding shortcuts yet

Did it installed the klayout macros?

**Comment by joamatab** [comment]
If you uninstall the gdsfactory klayout integration install.bat should install it for you


The integration gives you the generic layer map and Component.show()

**Comment by SkandanC** [comment]
Yep, it works, i'm able to do Component.show() after running the installer.

**Comment by joamatab** [comment]
Awesome, thank You Skandan!
