### ISSUE TITLE
EMEpy integration

### ISSUE THREAD

**Issue by smartalecH** [gdsfactory/gdsfactory#747]
It would be good to add a plugin for [EMEpy](https://github.com/BYUCamachoLab/emepy) for streamlined EME calculations.

We have plans for GPU offloading (once we find a cuda compatible targeted eigensolver that works well with python) and adjoint optimization (using a clever mix of diff-then-disc and disc-then-diff).

(cc @hammy4815)

**Comment by smartalecH** [comment]
Adding a plugin like this would actually be mutually beneficial:
* gdsfactory gets another solver
* EMEpy gets better corner case testing and validation

**Comment by joamatab** [comment]
great idea,

having eme on gdsfactory would be great for modeling tapers, bends, adiabatic couplers ...

@tvt173 
@flaport

**Comment by joamatab** [comment]
Another open sourced another EME plugin that would be great to integrate with gdsfactory
https://github.com/flaport/meow

thank you Floris!

@SkandanC 
@HelgeGehring 
@simbilod 
@thomasdorch

**Comment by simbilod** [comment]
see #1015

**Comment by joamatab** [comment]
I'll close this for now, PRs for simulation interfaces are always welcome
