### ISSUE TITLE
Meep adjoint optimization plugin / gmeep extension

### ISSUE THREAD

**Issue by SkandanC** [gdsfactory/gdsfactory#749]
It would be nice to extend gmeep's capabilities to include Meep's adjoint optimization features. This way, we can optimize some of gdsfactory's primitive components such as mmi1x2, generate a gdsfactory component from them, and eventually gds files.

Things to do:
- [x] Figure out how to setup a Meep adjoint optimization simulation from gdsfactory components
- [x] Figure out how to extract a gdsfactory Component object, and eventually a gds file, from the PNG files generated by Meep

For the latter, we can convert the PNG's to a numpy array, and then use gf.read.from_np to generate a gdsfactory component, as per @joamatab's suggestion. Or, if there's a way to create gds files straight from Meep, we can just turn those into a gdsfactory component.

**Comment by thomasdorch** [comment]
I actually wrote a function to get gdsfactory components from meep sims for doing exactly this, accessing the epsilon grid from the simulation object:

```
def get_component_from_sim(
        sim: mp.Simulation,
        upscale_factor: int = 2,
        threshold_offset_from_max: float = 0.01,
        layer: gf.types.Layer = (1, 0)
):
    grid_resolution = upscale_factor * sim.resolution

    sim_center, sim_size = mp.visualization.get_2D_dimensions(sim, output_plane=None)
    xmin = sim_center.x - sim_size.x / 2
    xmax = sim_center.x + sim_size.x / 2
    ymin = sim_center.y - sim_size.y / 2
    ymax = sim_center.y + sim_size.y / 2

    Nx = int((xmax - xmin) * grid_resolution + 1)
    Ny = int((ymax - ymin) * grid_resolution + 1)

    xtics = np.linspace(xmin, xmax, Nx)
    ytics = np.linspace(ymin, ymax, Ny)
    ztics = np.array([sim_center.z])

    eps_data = np.real(sim.get_epsilon_grid(xtics, ytics, ztics, frequency=fcen))

    return gf.read.from_np(
        eps_data,
        nm_per_pixel=1e3 / grid_resolution,
        layer=layer,
        threshold=np.max(eps_data) - threshold_offset_from_max,
    )
```

Never got around to adding it to gdsfactory but feel free to use it as a starting point :)

**Comment by SkandanC** [comment]
![image](https://user-images.githubusercontent.com/100642027/193435590-6b06607d-4a25-41e3-865b-7f2a045f4094.png)
Managed to do it. Ty @thomasdorch for your help! This is after 72 iterations of the optimization, which probably is a little low, and so the structure may not be the best. But, it serves the purpose of demonstration.

Regular mmi1x2 for comparison:
![image](https://user-images.githubusercontent.com/100642027/193435633-bbd21bb3-34b5-4e18-8e22-3c1b3783fe0c.png)

**Comment by joamatab** [comment]
Hi Skandan, 

this looks great,

can you send a link to the GDS?
There seems to be some self intersecting polygons that foundries won't accept?

have you made sure it passes some min width and min gap DRC rules using klayout? 
You can use 100nm for example both for min width and min gap

@smartalech
@flaport

**Comment by smartalecH** [comment]
How are you specifying the design region, FOM, optimization algorithm, beta scheduling, constraints, etc from within gdsfactory? 

Or is the optimization done externally, and the geometry simply imported after the fact?

We have some contour extraction routines that have yielded numerous fab-friendly results. (cc @joelslaby).

**Comment by SkandanC** [comment]
> Hi Skandan,
> 
> this looks great,
> 
> can you send a link to the GDS? There seems to be some self intersecting polygons that foundries won't accept?
> 
> have you made sure it passes some min width and min gap DRC rules using klayout? You can use 100nm for example both for min width and min gap
> 
> @smartalecH @flaport

@joamatab, I stopped the optimization before it could be done, because I didn't think my old laptop can handle more 😅. That explains why it has self - intersecting polygons and some features smaller than what foundries may accept. I will try to let it run for longer, and then send a link for the updated GDS file.

@smartalecH, as of now, the user defines the objective functions, FOM, optimization algorithm, etc. GDSFactory simply takes in the component, creates a Meep Simulation object, and then runs the optimization. Then the component can be generated from the Simulation object that is returned. I am sure there's a better way to do it, but I will need a couple of days to figure it out.

**Comment by SkandanC** [comment]
![both mmis](https://user-images.githubusercontent.com/100642027/193470976-3134474c-6dae-4de4-af86-b38cbfdbf97a.png)
I adjusted the threshold a bit and it looks better. 

[Here's a link to the GDS file.](https://drive.google.com/file/d/1q88A5JMH_0FPZpwBy51AB3gToWrY8xJ-/view?usp=sharing)

**Comment by joamatab** [comment]
Looks great,

it has some DRC errors
![image](https://user-images.githubusercontent.com/4514346/193609887-702c288e-b99c-4077-b304-a00ba7295882.png)

and some strange things on the edges
![image](https://user-images.githubusercontent.com/4514346/193609984-af1e2162-dcdc-43ba-94a4-0d29f288d548.png)

maybe you need to simplify the contours

**Comment by SkandanC** [comment]
Here is an updated pic after the optimization was complete (I ran it for 97 iterations).
![both mmis](https://user-images.githubusercontent.com/100642027/193614935-b84fcec1-1bb4-4815-9ccc-d68df4104c0d.png)

[Here is the updated GDS file link](https://drive.google.com/file/d/1q88A5JMH_0FPZpwBy51AB3gToWrY8xJ-/view?usp=sharing)

I think if I play around with the optimization hyperparameters I can eventually get a geometry with no DRC errors.

**Comment by smartalecH** [comment]
Note that the filters alone don't enforce DRC. You also need to add the corresponding optimization constraints that work with the filters. 

We don't have an end to end tutorial yet, but are working on it.

**Comment by SkandanC** [comment]
I am almost done with this, and am nearly ready to open a PR.

However, when I try to run a test optimization run, I get this error:
![image](https://user-images.githubusercontent.com/100642027/194155530-19ce289a-a93c-4a86-83d7-6b87f5269164.png)

This is my optimization object for reference:
![image](https://user-images.githubusercontent.com/100642027/194155573-fc3412c6-0af9-4105-80f2-c8c38802cab7.png)

Does anyone have any clues as to why this could be happening?

**Comment by smartalecH** [comment]
What version of meep are you using?

Essentially the simulation hasn't been initialized right. There are some checks in the step routine that ensures everything is as expected.

**Comment by smartalecH** [comment]
(Also you want more space between your PML and device)

**Comment by smartalecH** [comment]
(Also your monitors and source lines are too narrow. They won't calculate the proper mode)

**Comment by SkandanC** [comment]
Thanks Alec! I did some more playing around and found out that generating the `Simulation` object for the optimization directly from Meep, rather than from gdsfactory, seems to fix the problem. Perhaps I am using the `get_simulation` method from gmeep incorrectly.

I also adjusted the port margins and the cell size.

**Comment by SkandanC** [comment]
Also, I am using Meep version 1.24.0

**Comment by SkandanC** [comment]
Figured out what the issue was, the source generated for the Simulation object by gdsfactory couldn't be used in the optimization for some reason. I added a bit of code to generate a source that will, and it runs fine.

I am running this simulation one last time, and then I will add this to the gmeep docs, and open a PR @joamatab

**Comment by SkandanC** [comment]
![download (2)](https://user-images.githubusercontent.com/100642027/194616686-cfdb956a-722a-463e-bdcd-2043698c2ce8.png)

Final optimized structure. 

![image](https://user-images.githubusercontent.com/100642027/194617052-5cf0de3e-0294-441e-acad-9cd5e98ccd0b.png)

Still some areas are way too small, but playing around with the filter and constraint settings should fix it I think.

The FOM can be computed in the cost function:
![image](https://user-images.githubusercontent.com/100642027/194617366-97b3e797-1fa4-40ed-8487-a5ac2b679493.png)

The cost function, and objective arguments and functions are all defined by the user and passed in as arguments.

**Comment by smartalecH** [comment]
Very cool! Nice job, @SkandanC!

**Comment by SkandanC** [comment]
Thank you!
