### ISSUE TITLE
Remove triangle from requirements.txt

### ISSUE THREAD

**Issue by tvt173** [gdsfactory/gdsfactory#76]
The new dependency on `triangle` makes gdsfactory very hard to install into a conda environment. Would it be possible to remove (make optional)?

**Comment by joamatab** [comment]
yes, 

starting from 3.5.3 trimesh and all its dependencies (triangle, pyglet) are marked as optional

so `pip install gdsfactory` will not install them automatically

to install them you can always run

```
pip install gdsfactory[full] 
```
