### ISSUE TITLE
Regarding/importing a GDS file to gdsfactory and creating array

### ISSUE THREAD

**Issue by ratul619** [gdsfactory/gdsfactory#77]
Hi , 

I want to import an already created GDS file , and then create an array of the shapes that are inside the GDS.
Please let me know the relevant sections in the tutorial i should refer to. I was not able to locate the part of "import an already created GDS file" to gdsfactory. 

Thanks

**Comment by joamatab** [comment]
Hi Ratul,

i made a tutorial section specific for showing how to import [GDS files](https://gdsfactory.readthedocs.io/en/latest/notebooks/05_GDS.html)

the array part was already quite well documented in the [references tutorial](https://gdsfactory.readthedocs.io/en/latest/notebooks/01_references.html)

Hope this helps
Joaquin

**Comment by ratul619** [comment]
The link seems broken !

**Comment by joamatab** [comment]
yes, i moved the tutorial from readthedocs to github pages

https://gdsfactory.github.io/gdsfactory/

**Comment by njcoburn** [comment]
Hey @joamatab, can you point me to where the example is exactly? I cannot seem to find it.
Like the above, I have several different .gds files already made. I would like to pull them into gdsfactory, specifically to employ the automated routing through yaml scripts. Like the attached image.
Many thanks for your help![image](https://user-images.githubusercontent.com/63211638/228978831-69c4d207-4d38-473e-a121-ec14cbbdfff4.png)

**Comment by njcoburn** [comment]
Just a follow up... I believe that the answer is here: https://gdsfactory.github.io/gdsfactory/_autosummary/gdsfactory.read.import_gds.html?highlight=gf+import_gds
