### ISSUE TITLE
component.is_locked() is a misnomer

### ISSUE THREAD

**Issue by tvt173** [gdsfactory/gdsfactory#770]
**Describe the bug**
One would expect `component.is_locked()` to return a boolean, however it throws an error when "false" and returns nothing.

**To Reproduce**
```python
c = gf.components.straight()
c.is_locked()
```

**Expected behavior**
`is_locked()` should return a boolean, and would be useful to have. Maybe we rename the existing `is_locked()` function to `check_unlocked()` or something like that.

**Suggested fix**
See above

**Comment by joamatab** [comment]
great catch, thank you Troy!
