### ISSUE TITLE
dbr_tapered bug

### ISSUE THREAD

**Issue by SkandanC** [gdsfactory/gdsfactory#774]
**Describe the bug**
dbr_tapered periodic structures are offset from the correct position if the duty cycle is not 0.5

**To Reproduce**
When duty cycle is 0.5:
![image](https://user-images.githubusercontent.com/100642027/195871501-1b1b7d8a-d3e8-446e-8477-263e20ab3ac2.png)
When duty cycle is not 0.5:
```
dbr_tapered(length=5, period=0.85, dc=0.8, w1=0.4, w2=1, taper_length=5, fins=False, fin_size=(0.2, 0.05)).show()
```
![image](https://user-images.githubusercontent.com/100642027/195871954-1ae6f814-6fb8-4d50-94ac-eaf4255b3372.png)

**Expected behavior**
The periodic structures must be positioned in the "centre" of the taper + straight section

**Suggested fix**
A simple fix would be to rewrite the component to be similar to dbr, wherein the user passes in the number and widths of the periodic structures, and it creates an array of the periodic structures cells. 

I can open a PR with this fix if this sounds good @joamatab

**Comment by SkandanC** [comment]
I modified by making it use `array` instead of manually adding the periodic structures. I will open a PR soon.

**Comment by joamatab** [comment]
Thank you Skandan
