### ISSUE TITLE
Add optional decay cutoff argument to `write_sparameters_meep`

### ISSUE THREAD

**Issue by SkandanC** [gdsfactory/gdsfactory#779]
**Is your feature request related to a problem? Please describe.**
Sometimes when running gmeep simulations, there are "wavy artefacts" in the signal
![image](https://user-images.githubusercontent.com/100642027/196821668-0b1dc228-a41c-4d4f-9477-eb02fd7be3b0.png)

This is because of the default `decay_by` setting in the function's source code, which is set to 1e-3 by default, which might be too high for some cases. There is too much energy left in the simulation region, causing these ripples.

Changing this to 1e-8 in the source code fixes the issue:
![download (5)](https://user-images.githubusercontent.com/100642027/196821980-1538c266-0f9a-4f93-92eb-2ce01968b567.png)

Code to repoduce:
[Code file](https://drive.google.com/file/d/1I-ZiqqBnOQw9AKSsr4wAcAaxQsbWxxX3/view?usp=sharing)

**Describe the solution you'd like**
Add an optional `decay_cutoff` argument so the user can set it if they like.

I can open a PR with this if you'd like.

@joamatab

**Comment by joamatab** [comment]
Thank you Skandan!
