### ISSUE TITLE
show_subports causes error with CellArray references 

### ISSUE THREAD

**Issue by tvt173** [gdsfactory/gdsfactory#791]
**Describe the bug**
When a cell has a CellArray reference, i.e. added with `c.add_array()`, and then it is shown with `show_subports=True`, it throws an error: `AttributeError: 'CellArray' object has no attribute 'get_ports_list'`

**To Reproduce**
```python
    c = gf.Component()
    c.add_array(gf.components.straight())
    c.show(show_ports=True, show_subports=True)
```

**Expected behavior**
In this case, the reference type is actually a gdspy CellArray, which doesn't have ports, so we should probably just skip the references which are not of type ComponentReference.

**Suggested fix**
On line 1231 of component.py, only call `add_pins_triangle()` if the reference is of type ComponentReference

**Comment by joamatab** [comment]
Thank you Troy!

fixed here
https://github.com/gdsfactory/gdsfactory/pull/794
