### ISSUE TITLE
GUI layout driven flow improvements

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#800]
Thanks to flayout and Thomas' [PR](https://github.com/gdsfactory/gdsfactory/pull/797) we can now link gdsfactory inside klayout and instantiate all the generic cells.
This allows to convert any code driven gdsfactory PDK into a klayout GUI editable layouts. 
(Disclaimer: we still recommend a pure python code driven flow for complex layouts.)

- [x] modify Pcell values without getting a strange error due to deleting cells [klayout issue](https://github.com/KLayout/klayout/issues/1176)
- [ ] convert gdspy paths into klayout compatible paths
![image](https://user-images.githubusercontent.com/4514346/199026244-79779048-1b8c-40de-af47-4273036e0806.png)
- [x] remember gdsfactory packages path. So it does not ask you for their location everytime
- [x] Test on Linux
- [x] Test on Windows
- [ ] Test on MacOs
- [x] show in menu and group all gdsfactory macro menus inside a `gdsfactory` menu [PR](https://github.com/gdsfactory/gdsfactory/pull/801)
- [x] name is automatically computed, instead of entered, so we can live update cell parameters without having to change the name

![image](https://user-images.githubusercontent.com/4514346/199263620-efb597aa-006e-4cf3-903d-2e7ed2d6cf7b.png)

@thomasdorch 
@flaport 
@lukasc-ubc

**Comment by joamatab** [comment]
Can someone test it on Windows and MacOs?

**Comment by thomasdorch** [comment]
It doesn't work on Windows, I'm getting 'circular import' errors when trying to import gdspy.

**Comment by Jan-David-Black** [comment]
I cannot get it to work on mac either :/
I would assume I am doing something wrong:

<img width="719" alt="Screenshot 2022-11-05 at 13 50 27" src="https://user-images.githubusercontent.com/92856893/200120728-7ef36303-a006-4cf3-9d4d-42dd37367dbe.png">

Selecting the python3.9 folder that comes with gdsfactory. When I run import_generic_PCells subsequently I get the following warnings/errors.

<img width="431" alt="Screenshot 2022-11-05 at 13 41 58" src="https://user-images.githubusercontent.com/92856893/200120663-a7afcfca-128c-4e90-b363-cb5df14c8b6a.png">
<img width="550" alt="Screenshot 2022-11-05 at 13 42 08" src="https://user-images.githubusercontent.com/92856893/200120667-f7ea55d9-ba94-4cb7-9409-903077afe848.png">

I installed `ubcpdk` in `~/gdsfactory/lib/python3.9/site-packages` but it doesn't make a difference.
Probbly I am doing something wrong. Let me know, if you have suggestions.

**Comment by Jan-David-Black** [comment]
It seems that somehow the numpy integration wit KLayout got damaged in the process
<img width="409" alt="Screenshot 2022-11-05 at 14 13 11" src="https://user-images.githubusercontent.com/92856893/200121716-2850c9f0-b3c0-4ecf-9fb0-8760a8dddc5e.png">

**Comment by thomasdorch** [comment]
Try uninstalling the `klayout` python package in your python environment. That should fix the `name gfc is not defined` error.

**Comment by SkandanC** [comment]
![image](https://user-images.githubusercontent.com/100642027/201491472-ab118e59-2a6f-458a-a47b-47504d49986e.png)

Running into this error on Ubuntu 22 WSL. Not sure if something is wrong with one of the files, or if I did something wrong.

**Comment by SkandanC** [comment]
Hi @joamatab,

I think most of the stuff on the checklist are completed by my latest PR, except for test on MacOS and test on Windows. We know it does not work on Windows, but idk if anyone has got it to work on MacOS yet. It wold be nice if someone with access to a MacOS computer can test it with the latest release.

**Comment by Jan-David-Black** [comment]
I can do that. Could you tell me exactly what to test?
1. install new release
2. the try the gdsfactory menus in layout
or anything else?

**Comment by SkandanC** [comment]
Thanks!

1, install new release
2. `gf tool install` in your terminal
3. Open KLayout -> gdsfactory 6.2.1 -> import generic PCells
4. Open new layout -> try importing random PCells from the gdsfactory library

**Comment by Jan-David-Black** [comment]
release: 6.2.3
running `gf tool install` once everything seems fine
running it again gives:
```
NotADirectoryError: [Errno 20] Not a directory: '/Users/j.fischbach/.klayout/macros/gdsfactory'
```
`import generic PCells` prompts a file selector dialog

**Comment by Jan-David-Black** [comment]
![Screenshot 2022-11-22 at 21 01 10](https://user-images.githubusercontent.com/92856893/203410691-4fddbcb9-883c-4dd4-a05f-a7254962ca39.png)

An I somehow have duplicate menu entries

**Comment by Jan-David-Black** [comment]
After canceling the file dialog I now get
```
No module named 'flayout'
```

**Comment by SkandanC** [comment]
I think the duplicate must be because the macro files must've been duplicated elsewhere, I will open a PR for this right away. They both should do the same thing.


The dialog box is expected - it wants you to select the directory where the `site-packages` directory sits in. This `site-packages` should also have gdsfactory and flayout in it. After the appropriate directory is selected, it should import the PCells automatically, displaying a progress bar.

**Comment by Jan-David-Black** [comment]
I think I have selected the wrong path the first time. To reset it I have to delete the config json?

**Comment by SkandanC** [comment]
Yes, it should be under ~/.gdsfactory

**Comment by Jan-David-Black** [comment]
Hm it was installed...

**Comment by Jan-David-Black** [comment]
Ah ok: I had the wrong directory: one level too deep...
now I get
```
No module named 'gdstk'
```
even though it is installed

**Comment by Jan-David-Black** [comment]
sorry for the trouble

**Comment by SkandanC** [comment]
> sorry for the trouble

No worries!

**Comment by Jan-David-Black** [comment]
It seems that gdstk is not linked to klayout
I tried `lygadgets_link gdstk`
but it only gave me:
```
Did not recognize the klayout relevance of /User/<path to gdstk>
```

**Comment by Jan-David-Black** [comment]
Ok now I only have the menu entries once: seemed to have been a double install also in salt.

**Comment by SkandanC** [comment]
It must've been from your previous installation of the older version

**Comment by Jan-David-Black** [comment]
So I cleaned everything
It still complains about gdstk missing

**Comment by Jan-David-Black** [comment]
also in the macro ide:

<img width="206" alt="Screenshot 2022-11-22 at 21 31 18" src="https://user-images.githubusercontent.com/92856893/203415190-54e2c3a7-1f34-4f48-bc5e-4421318e2aa7.png">

**Comment by SkandanC** [comment]
Are you able to import gdsfactory in python? If not, it must be an issue with the gdstk installation. If yes, then it must be an issue with KLayout's Python [similar to this](https://github.com/gdsfactory/gdsfactory/issues/891).

**Comment by Jan-David-Black** [comment]
Yes I am able to run gdsfactory from my terminal

**Comment by SkandanC** [comment]
Then it is the same issue as on Windows KLayout. I am glad we tested this, or else we could've overlooked this!

**Comment by Jan-David-Black** [comment]
I might try a different gdstk install: instead of mamba directly pip. give me a sec

**Comment by Jan-David-Black** [comment]
Ok, so tried pip and compile from source. Both didn't help...

**Comment by joamatab** [comment]
I think you need to install gdsfactory on your MacOS python 

@lukasc-ubc

**Comment by SkandanC** [comment]
I managed to install klayout-gui on Windows using @thomasdorch's conda install. I can import gdstk now 🎉:
![image](https://user-images.githubusercontent.com/100642027/203617223-1385e587-b72f-4f13-ad56-13a458e7940b.png)


But, it only is available on python3.11. The issue is gdsfactory does not support python3.11 because [one of our dependencies does not support python3.11](https://github.com/lxml/lxml/pull/356) https://github.com/lxml/lxml/pull/362 Once they make a new release, we can add support for python3.11, and then get gdsfactory on KLayout working on all 3 OS. @lukasc-ubc 

![image](https://user-images.githubusercontent.com/100642027/203617374-9c1eb805-c503-42f3-ad0f-4f39da8e7a63.png)

@Jan-David-Black can you try this on MacOS too, and see if gdstk can be imported there too?

**Comment by Jan-David-Black** [comment]
> I think you need to install gdsfactory on your MacOS python

I seem to not fully understand: do you mean system level python? Should it not work with conda environments?

> @Jan-David-Black can you try this on MacOS too, and see if gdstk can be imported there too?
I will. (I'll edit as soon as it's done)

Due to relatively poor adaption of 3.11 so far I would prefer having the opportunity to stay with 3.10. Which will be possible as soon as @thomasdorch's build is up.

**Comment by lukasc-ubc** [comment]
Can you folks help me get this running on Mac OSX?  Below is what I tried, and the error.    It would be helpful if there was a document that had the installation instructions.    Including which versions, which tools, etc.  

Thank you!
Lukas


* Installed v6.2.5 with the 1 GB installer.
* Installed in ~/gdsfactory
* ~/gdsfactory/bin/conda update GDSfactory
* Downloaded KLayout, “Anaconda3-environment based” LW 0.27.12
    * Copy and rename klayout to klayout-0.27.12-macOS-BigSur-1-qt5Ana3-Rana3Pana3.app
    * Copy and open the KLayoutAna3.app using Automator, and edit: export PYTHONHOME=/Users/lukasc/gdsfactory, and myklayout=/Applications/klayout-0.27.12-macOS-BigSur-1-qt5Ana3-Rana3Pana3.app
      * Can't save, error: The document “KLayoutAna3” could not be saved. A code signing error occurred.  /Applications/KLayoutAna3.app.sb-39bc65bd-FHY3tL: replacing existing signature
/Applications/KLayoutAna3.app.sb-39bc65bd-FHY3tL: unsealed contents present in the bundle root

    * Manually running in the terminal:
    * `export PYTHONHOME=/Users/lukasc/gdsfactory` 
    * `myklayout=/Applications/klayout-0.27.12-macOS-BigSur-1-qt5Ana3-Rana3Pana3.app`
    *  `myconfig=$HOME/.klayout/klayoutrc`
    * `open -n -a $myklayout --args -e -c $myconfig -style=fusion $@`
      * Errors: Termination Reason:    Namespace DYLD, Code 1 Library missing
      * Library not loaded: @rpath/libpython3.8.dylib
      * Referenced from: /Applications/klayout-0.27.12-macOS-BigSur-1-qt5Ana3-Rana3Pana3.app/Contents/MacOS/klayout
      * Reason: tried: '/Applications/klayout-0.27.12-macOS-BigSur-1-qt5Ana3-Rana3Pana3.app/Contents/MacOS/../Frameworks/libpython3.8.dylib' (no such file), '/Applications/klayout-0.27.12-macOS-BigSur-1-qt5Ana3-Rana3Pana3.app/Contents/MacOS/../Frameworks/libpython3.8.dylib' (no such file), '/Applications/klayout-0.27.12-macOS-BigSur-1-qt5Ana3-Rana3Pana3.app/Contents/MacOS/../Frameworks/libpython3.8.dylib' (no such file), '/Applications/anaconda3/lib/libpython3.8.dylib' (no such file), '/Applications/klayout-0.27.12-macOS-BigSur-1-qt5Ana3-Rana3Pana3.app/Contents/MacOS/../Frameworks/libpython3.8.dylib' (no such file), '/Applications/klayout-0.27.12-macOS-BigSur-1-qt5Ana3-Rana3Pana3.app/Contents/MacOS/../Frameworks/libpython3.8.dylib' (no such file), '/Applications/klayout-0.27.12-macOS-BigSur-1-qt5Ana3-Rana3Pana3.app/Contents/MacOS/../Frameworks/libpython3.8.dyli

**Comment by SkandanC** [comment]
Hi Prof. Chrostowski @lukasc-ubc,

By "Anconda3-environment based", do you mean the conda install by Thomas Dorch that I mentioned? Afaik, that is only meant for Windows as of now.

**Comment by joamatab** [comment]
Hi Skandan, 

any changes I make on the Pcell I get a `NoneType` error

does it work well on your end?

**Comment by SkandanC** [comment]
Hi @joamatab,

It works well on my end, could you post a screenshot, or the error message so I can debug it?

**Comment by joamatab** [comment]
yes,

https://github.com/gdsfactory/gdsfactory/pull/957

whenever i change any parameter this is what happens


![image](https://user-images.githubusercontent.com/4514346/205536089-d37dbdd3-400d-4f3c-b4d3-11fba44ea9eb.png)

**Comment by joamatab** [comment]
@nikosavola 

I think you had a way of making this work
