### ISSUE TITLE
create shortcuts during installation

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#802]
How can we create shortcuts during installation?

we can use `menuinst` as suggested [here](https://github.com/conda/constructor/issues/573)

This continues the [simpler install](https://github.com/gdsfactory/gdsfactory/issues/723) effort

**Comment by SkandanC** [comment]
@joamatab I'm just curious, do we know what the shortcut is supposed to do? As in, will it be used to open the docs upon clicking on it, or something else?

**Comment by joamatab** [comment]
Hi Skandan, we can add shortcuts to spyder, anaconda navigator and jupyter lab

**Comment by SkandanC** [comment]
![image](https://user-images.githubusercontent.com/100642027/199888771-346ac828-9052-4439-9c79-06a4ace100fd.png)
After clicking on this icon:
![image](https://user-images.githubusercontent.com/100642027/199889039-b3db5c55-9180-4e87-812e-8e142bcc022f.png)

I got Spyder shortcut installed :). I now have a template for adding shortcuts to all executables, so adding them for Anaconda Navigator and Jupyter lab should just be a matter of replacing "Spyder" in my script with these.

**Comment by joamatab** [comment]
Great work Skandan :)

**Comment by SkandanC** [comment]
Thanks Joaquin! Should we rename this icon as something like "Spyder with GDSFactory"?

**Comment by joamatab** [comment]
yes, that would be great,

How about `gdsfactory spyder` `gdsfactory jupyterlab` and `gdsfactory navigator` for spyder, jupyterlab and anaconda navigator
?

**Comment by joamatab** [comment]
Thank you Skandan!

there were some hard coded paths that i tried fixing in release  v5.54.0

let me know if that release creates the shortcuts correctly :)

**Comment by SkandanC** [comment]
Woops, sorry about that, I must've double checked before sending it!

**Comment by joamatab** [comment]
Thank you Skandan,

I will mark this as done
