### ISSUE TITLE
port issues when absorbing

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#816]
This code produces some pins that don't rotate

```
import gdsfactory as gf

@gf.cell
def test():
    c = gf.Component()
    bend = c << gf.components.bend_circular()
    bend.rotate(-90)
    c.add_ports(bend.ports)
    c.absorb(bend)
    return c


if __name__ == "__main__":
    c = gf.Component("demo")
    bend = c << test()
    c.add_ports(bend.ports)
    c.show(show_ports=True)
```

![image](https://user-images.githubusercontent.com/4514346/199858082-cabde9df-4f07-42dc-935b-dab6a6c85ad6.png)

**Comment by tvt173** [comment]
is that the fault of `absorb()`? the ports are being added via `c.add_ports(bend.ports)` and not through absorb, right?

**Comment by joamatab** [comment]
I think the issue is that the pins are defined as paths and not as polygons so they don't rotate

**Comment by tvt173** [comment]
Ah, I see. I was confused. I thought you were talking about the actual port objects, but you're talking about pin shapes. That makes sense

**Comment by SkandanC** [comment]
![image](https://user-images.githubusercontent.com/100642027/200148381-a3929b99-0a9d-45c7-8520-388648e97b3f.png)
I was able to fix it. Final result after fix :)

**Comment by joamatab** [comment]
Hi Skandan, 

yes, replacing the paths by polygons would fix the issue, ideally we keep them as rotated paths

**Comment by SkandanC** [comment]
Got it, I will try to figure out a way to do that, I have some free time, I can work on this.

**Comment by SkandanC** [comment]
Small update: I found that if I turn off all the layers except pinrec, I can see the pins be repeated twice:
![image](https://user-images.githubusercontent.com/100642027/200432467-ef5d32c7-fb67-49b9-b36c-6388e7d195bb.png)
One pair of them is in the correct orientation, which means the pins are being rotated as they should be, even thoguh they are FlexPaths.
However, the `absorb` method absorbs paths from the parent component, but it does not absorb the rotated paths for soem reason.

**Comment by joamatab** [comment]
great, thank you Skandan!
