### ISSUE TITLE
Extrude based on RobustPath

### ISSUE THREAD

**Issue by tvt173** [gdsfactory/gdsfactory#872]
**Is your feature request related to a problem? Please describe.**
In a sample test suite, I see that the `extrude` function takes roughly 30% of the entire runtime with the new gdstk backend. This is mainly due to RDP simplification of bends. I'm wondering if this could be sped up by instead using gdstk's `RobustPath`: https://heitzmann.github.io/gdstk/geometry/gdstk.RobustPath.html

**Describe the solution you'd like**
It seems that `RobustPath` supports all the options offered by `extrude`, including functionalized widths and end caps, and also a tolerance parameter, which should have the same effect as simplification (it seems). Maybe we can make an alternate implementation first which we can try out based on RobustPath, and potentially we can switch our default implementation later on if it is promising.

**Comment by joamatab** [comment]
Why not use flexpath instead?

https://heitzmann.github.io/gdstk/geometry/gdstk.FlexPath.html
