### ISSUE TITLE
How to fix font_free_type?

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#877]
```
    from gdsfactory.components.text_freetype import text_freetype
    c2 = text_freetype(
        "hello",
        font="Times New Roman"
    )
    c2.show(show_ports=True)
```

Returns
```
File ~/gdsfactory/gdsfactory/component.py:137, in Component.__init__(self, name, with_uuid)
    134 if with_uuid or name == "Unnamed":
    135     name += f"_{self.uid}"
--> 137 self._cell = gdstk.Cell(name=name)
    138 self.name = name
    139 self.info: Dict[str, Any] = {}

ValueError: embedded null character

```

**Comment by joamatab** [comment]
Try to fix it in here

https://github.com/gdsfactory/gdsfactory/pull/878

but still has some issues

**Comment by JinWallner** [comment]
When I try to use text_freetype with ttf file.
    t = c << gf.components.text_freetype(text=text, size=size, layer=layer, font=currentdir+"/DEPLOF.ttf")
I got a different kind of error:
  File "/Users/jin/opt/anaconda3/lib/python3.9/site-packages/gdsfactory/components/text_freetype.py", line 89, in text_freetype
    letter_dev.add_polygon(poly.polygons, layer=layer)
AttributeError: 'gdstk.Polygon' object has no attribute 'polygons'

**Comment by joamatab** [comment]
Hi Jin, this needs fix since we migrated to gdstk 

@SkandanC 
@tvt173

**Comment by wuzhonghan** [comment]
this issue still there

**Comment by joamatab** [comment]
yes, we are looking forward to having someone help fixing this

**Comment by SkandanC** [comment]
![hellotext](https://user-images.githubusercontent.com/100642027/225751374-4e89539a-b387-4a75-901d-f7ba73fd7259.png)

Hello @JinWallner!

I will open a PR for this!
