### ISSUE TITLE
KLayout on Windows struggles to import gdstk while running gf macros

### ISSUE THREAD

**Issue by SkandanC** [gdsfactory/gdsfactory#891]
**Describe the bug**
When trying to import PCell library in KLayout, it fails to import gdstk, and the entire process doesn't work.

**To Reproduce**
gdsfactory menu -> import_generic_PCells. I modified the error message only to make it more verbose.
![image](https://user-images.githubusercontent.com/100642027/202551850-570e4bac-d0f4-4fcd-8174-419e6fff96b9.png)

**Suggested fix**
This is a known issue with KLayout's Python. 
https://www.klayout.de/forum/discussion/1834/nazca-module-is-not-recognized

**Comment by SkandanC** [comment]
It can import flayout perfectly fine, it just can't import gdstk because it is stored as a .pyd under the same directory. KLayout's Python cannot import .pyd

**Comment by thomasdorch** [comment]
Yeah this is the same issue I had with gdspy before :/

**Comment by tvt173** [comment]
have you tried setting the PYTHONPATH to the directory with the *.pyd files?
https://stackoverflow.com/questions/50278029/how-to-import-a-pyd-file-as-a-python-module

**Comment by SkandanC** [comment]
Hey @tvt173,

According to Matthias in the link I posted, this won't work.
![image](https://user-images.githubusercontent.com/100642027/202651071-47f5f0c3-3328-4452-af05-cea0d54d69f4.png)

**Comment by thomasdorch** [comment]
My understanding is that the KLayout Windows program is compiled with MSYS2 while Python C-extensions are all compiled with the MSVS compilers, hence no binary-compatibility.

**Comment by tvt173** [comment]
> My understanding is that the KLayout Windows program is compiled with MSYS2 while Python C-extensions are all compiled with the MSVS compilers, hence no binary-compatibility.

does that mean you could potentially fix the issue by compiling Klayout with the MSVS compiler?

better long term solution might be to launch a gdsfactory server on a separate process (choose which python you like) and communicate with Klayout via a client API.

**Comment by thomasdorch** [comment]
> > My understanding is that the KLayout Windows program is compiled with MSYS2 while Python C-extensions are all compiled with the MSVS compilers, hence no binary-compatibility.
> 
> does that mean you could potentially fix the issue by compiling Klayout with the MSVS compiler?

Absolutely! I've been able to get the [GUI version built on Windows](https://github.com/thomasdorch/klayout-conda) using the MSVC2017 compiler and it works just fine with gdstk :)

**Comment by tvt173** [comment]
@thomasdorch I think a conda install is a great option. nice work on getting that running! but it would also be great for the standard Klayout to have better support for these packages as well. I'd imagine this would be an issue for many compiled python packages and not just the ones we're dealing with here, right?

@klayoutmatthias, is there any particular reason for choosing MSYS2 as the compiler for Klayout Windows version, or would you be open to changing to get better python support?

**Comment by tvt173** [comment]
thanks Matthias. sounds good
