### ISSUE TITLE
Improve IntelliSense on "wrapping" functions

### ISSUE THREAD

**Issue by jan-david-fischbach** [gdsfactory/gdsfactory#906]
**Is your feature request related to a problem? Please describe.**
Currently we are passing lots of parameters down chains of functions using the `**kwargs` syntax. This yields minimal function signatures, however, IntelliSense and introspection get less informative also. Currently, the approach is to document the variables of the underlying components in the docstring of the wrapping function. To do this is however cumbersome and prone to be outdated: When a child component is changed (e.g. another parameter is added) one has to "propagate" up the whole tree and change all parent docstrings.

**Describe the solution you'd like**
If we could somehow construct a decorator or similar to automatically "annotate" the `**kwargs` such that it looks to the introspection and IntelliSense etc. as if the wrapping function had the respective arguments. 
Going even further it would be great if the parameter documentation could be appended to the docstring of the wrapping function (maybe in a dedicated section at the end).
 
**Suggested fix**
So far I tried dynamically overwriting the function signature. Which works with `help` and `?` however not with pylance I my case. My other approach was to try something similar to the following:

``` python
from typing import TypeVar, ParamSpec, Callable, Concatenate
P = ParamSpec('P')
R = TypeVar('R')

def old(a: str = "test_a", b: str = "test_b") -> str:
    """old docstring"""
    return a+b

def with_extra(f: Callable[P, R]) -> Callable[Concatenate[str, P], R]:
    '''function that runs on'''
    def inner(extra: str = "extra", *args: P.args, **kwargs: P.kwargs) -> R:
        """new docstring"""
        print(extra)
        return f(*args, **kwargs)
    return inner

new = with_extra(old)

help(new)
```

However, the default values are not correctly displayed in IntelliSense and it is also not fully consistent in other regards. 
Does anyone else have a better idea?
Regards JD

**Comment by tvt173** [comment]
what's a concrete example where you are having this issue and which IDE are you using?

For example, functions wrapped with `@cell` should still maintain their signature , because they use `@functools.wraps`, and I can confirm that in pycharm they correctly get autocompletion, etc.

Functions wrapped in `functools.partial`, I believe will give you issues. The best way to avoid this is to not use partials, IMHO.
