### ISSUE TITLE
Add tests for delay lines

### ISSUE THREAD

**Issue by simbilod** [gdsfactory/gdsfactory#911]
**Describe the bug**
Some delay line components lay out a different length than the one passed as argument (see e.g. #909 for a quick fix to delay_snake3)

**Suggested fix**
We need tests specificlaly for delays that is **independent** of just tallying length, for instance compute the component area with c.area() and dividing by waveguide width.

More generally, we need more robust LVS, or some comparison of layout to design intent

**Comment by joamatab** [comment]
https://github.com/gdsfactory/gdsfactory/issues?q=is%3Aissue+is%3Aopen+lvs

@damienbonneau
@tvt173 
@sebastian-goeldi
