### ISSUE TITLE
Cell.absorb does not preserve hierarchy

### ISSUE THREAD

**Issue by flaport** [gdsfactory/gdsfactory#919]
**Describe the bug**
Not sure if truly a bug, but definitely is confusing. Currently, the `Cell.absorb` method does not preserve hierarchy. In stead it just flattens the to be absorbed reference and adds the polygons to the cell. In my opinion, only the top-level reference should be absorbed and any hierarchical references should be added to the cell on which we called `absorb` 

**To Reproduce**
```python
cell1 = gf.Component()
cell2 = gf.components.mzi()
cell1.absorb(cell2)
```

**Expected behavior**
after the absorb, you're only left with polygons in cell1. In stead we should have references to the individual components in cell2.

**Suggested fix**
Make a PR that changes the behavior of cell.absorb or if you're afraid to break things, at least add a flag to preserve hierarchy.

**Comment by joamatab** [comment]
Hi Floris, 

absorb only works for references that are inside a cell

```
import gdsfactory as gf

cell1 = gf.Component()
ref = cell1 << gf.components.mzi()
cell1.absorb(ref)
cell1.show()
```
