### ISSUE TITLE
Is this a minor bug?

### ISSUE THREAD

**Issue by HWOde** [gdsfactory/gdsfactory#938]
After I run the following code

import gdsfactory as gf
gf.config.set_plot_options(show_subports=False)

c = gf.Component('two_reference')
wr1 = c << gf.components.straight(width=0.6)
wr2 = c << gf.components.straight(width=0.6)
wr2.movey(2)
c.add_ports(wr1.get_ports_list(), prefix='top_')
c.add_ports(wr2.get_ports_list(), prefix='bot_')
c.ports
c.auto_rename_ports()
c.ports
c.show()
c.plot(blocking=True)

I get this picture in matplotlib drawing window, from the picture, we can see that the port is correctly named.
![image](https://user-images.githubusercontent.com/114547985/204772528-7c3ea472-16a6-48d7-b7e5-9dd72e472642.png)
However, when I check the layout in klayout, it is clear that the port names of the upper and lower waveguides are still o1 and o2. I don't know whether this is a minor bug？
![image](https://user-images.githubusercontent.com/114547985/204773590-32b06cf2-3daf-4da7-abc4-433d1cadfc83.png)

**Comment by joamatab** [comment]
Hi, you are seeing the pins from the references

You can run

c.show(show_ports=True)

And it will show the port names of the top level cell
