### ISSUE TITLE
gf tool install issues

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#943]
Hello @joamatab ,

I installed the latest version and did a fresh install of klayout, and tried to use the cli tool to install the salt package. I ran into a couple of issues:

1. The cli tool is broken and does not take in any commands and errors out. I had to manually fix it by opening the gf file and changin `gf` to `cli` everywhere.

![Screenshot 2022-11-30 2.37.26 PM.png](https://user-images.githubusercontent.com/100642027/204896801-590ed6c3-bad6-4329-918b-368aaf2a36ad.png)

2. After getting this working, I ran `gf tool install` and it was installed in the salt directory. Opening klayout did not show the menu item for gdsfactory:

![Screenshot 2022-11-30 2.39.37 PM.png](https://user-images.githubusercontent.com/100642027/204897395-b66b0d64-65a8-40f0-a048-eebd3efce6b2.png)

Moving the gdsfactory folder to `macros` rather than `salt` brings the menu back:

![Screenshot 2022-11-30 2.41.03 PM.png](https://user-images.githubusercontent.com/100642027/204897519-5312133a-6165-4186-9574-c8da1c2fc3df.png)

Is there a reason we have to keep this under salt? Does it change it's functionality in any way by moving it to macros? Atleast keeping it under macros brings it in toolbar. Having it under salt makes it inaccessible.

Perhaps @thomasdorch knows?

_Originally posted by @SkandanC in https://github.com/gdsfactory/gdsfactory/issues/937#issuecomment-1332682864_

**Comment by sebastian-goeldi** [comment]
If you want it installable by the package manager it needs to go to the salt folder, that's where all packages managed by the saltmine live. I believe though you have an error in your setup. Python macros need to go thw `pymacros` folder. `macros` is for ruby. That might be the problem. I think the standard packages might detect this and can run it successfully anyway, but not for packages.

**Comment by joamatab** [comment]
Skandan,

is it working now?

**Comment by sebastian-goeldi** [comment]
I believe this will not work. Klayout has two kinds of python files. `.py` and `.lym` They get loaded differently. `.py` are the "traditional" python files and go into `/python`. `.lym` are the xml wrapped python files that also hold klayout information. These are the ones called by the macro class (forgot the exact name) and can be set to autoexecute etc. They need tp be in `/pymacros`. I believe if they are in `/python`, they won't be properly executed on startup anymore.

**Comment by SkandanC** [comment]
@joamatab yes it works now.
