### ISSUE TITLE
A bug in gf.components.die funtion.

### ISSUE THREAD

**Issue by HWOde** [gdsfactory/gdsfactory#967]
When parameter size not equal to (10000, 5000), gf.components.die function cannot return the correct Component. For example, after running the following code, I got the following graph.

```
import gdsfactory as gf

D = gf.components.die(
    size=(13000, 3000),  # Size of die
    street_width=100,  # Width of corner marks for die-sawing
    street_length=1000,  # Length of corner marks for die-sawing
    die_name="chip99",  # Label text
    text_size=500,  # Label text size
    text_location="SW",  # Label text compass location e.g. 'S', 'SE', 'SW'
    layer=(2, 0),
    bbox_layer=(3, 0),
)
D.plot(blocking=True)
```

![image](https://user-images.githubusercontent.com/114547985/206110655-79a05118-a5d7-432d-a37d-d858f48a4249.png)

Then I checked the gf.components.die function. I found some problems with the code marked with red circles.

![image](https://user-images.githubusercontent.com/114547985/206112095-42cd9106-4817-4217-8b14-66eb192eeece.png)

I modified them (see the picture below) so that the gf.components.die function will work normally no matter what the value of the parameter size is.
![image](https://user-images.githubusercontent.com/114547985/206113023-2055e3e2-587e-4c6a-abf3-e3eb50c018c5.png)
![image](https://user-images.githubusercontent.com/114547985/206114643-9f205f70-2bab-4994-a888-0a8736810829.png)

As a non-professional developer, I don't know how to use Git to commit modified files, so I hope you can fix this tiny bug for me, thank you!

**Comment by joamatab** [comment]
Thank you @HWOde 

releasing 6.6.1 with your fix
