### ISSUE TITLE
database improvements

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#992]
As we simulate different devices we would like to build models for the simulations using [JAX](https://gdsfactory.github.io/gdsfactory/notebooks/plugins/sax/02_model_extraction.html) and correlate simulations with measurements in [database](https://gdsfactory.github.io/gdsfactory/notebooks/12_database.html)

At the moment we store modes we store the data in npz. (numpy format) and the settings in YAML in a separate repo, See for [example](https://github.com/gdsfactory/gdslib/tree/main/sp)

How can we move that into the gdsfactory database?

TODO:

- [ ] add examples on how to add and query simulations https://gdsfactory.github.io/gdsfactory/notebooks/12_database.html
- [ ] add examples on how to bring up and connect your own database. Maybe using radlab? @proppy
- [ ] Build restful API to access database [similar to this one](https://github.com/EHVAAutomation/ehva-python/blob/Master/ehva/ehva_api.py)

Maybe:

- [ ] look at https://github.com/tiangolo/sqlmodel
- [ ] support other database models (graph database), Big Query
- [ ]  Expand database to serialize GDS data (polygons, references, labels), simulations and measurements
- [ ] Document test sequence information in the database

@tvt173 
@flaport 
@nikosavola

**Comment by Jan-David-Black** [comment]
How would we deal with development compiles? In a previous work environment of mine, we had a similar system. But we had the problem, that repeated compiles (e.g. for testing) lead to enormous amounts of components in the database, that are completely irrelevant but hard to purge from the DB without affecting interesting data. 
We adopted a `--production` flag. Such a flag could then be used with CI to write to the DB for a taged commit (the tapeout).

**Comment by joamatab** [comment]
I think for development one could use a local sqlite version of the database

**Comment by proppy** [comment]
Thinks worth exploring:
- SQLite replication to GCS using https://litestream.io/
- JSON streaming to BigQuery https://cloud.google.com/bigquery/docs/loading-data#streaming

**Comment by joamatab** [comment]
Niko,

the database notebook example is not running and I had to deactivate its execution

https://gdsfactory.github.io/gdsfactory/notebooks/12_database.html

@nikosavola

**Comment by proppy** [comment]
Also saw https://blog.turso.tech/sqlite-based-databases-on-the-postgres-protocol-yes-we-can-358e61171d65 recently.

**Comment by joamatab** [comment]
moved to gplugins
