### ISSUE TITLE
Shapely 2.0 breaks meshing

### ISSUE THREAD

**Issue by simbilod** [gdsfactory/gdsfactory#993]
The meshing plugin does not work with the new version of shapely (2.0)

For now, I have pinned the [gmsh] requirement to shapely 1.8.4

**Comment by simbilod** [comment]
See #994

**Comment by joamatab** [comment]
How about https://github.com/gdsfactory/gdsfactory/pull/996?

**Comment by simbilod** [comment]
Yes we can close now

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by simbilod** [comment]
Fixed in #996 #997
